# Generated by Django 3.2.14 on 2022-12-06 04:52

import common.db.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdHoc',
            fields=[
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('tasks', common.db.fields.JsonListTextField(verbose_name='Tasks')),
                ('pattern', models.CharField(default='{}', max_length=64, verbose_name='Pattern')),
                ('options', common.db.fields.JsonDictCharField(default='', max_length=1024, verbose_name='Options')),
                ('run_as_admin', models.BooleanField(default=False, verbose_name='Run as admin')),
                ('run_as', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Username')),
                ('become', common.db.fields.EncryptJsonDictCharField(blank=True, default='', max_length=1024, null=True, verbose_name='Become')),
                ('created_by', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Create by')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'AdHoc',
                'db_table': 'ops_adhoc',
                'get_latest_by': 'date_created',
            },
        ),
        migrations.CreateModel(
            name='AdHocExecution',
            fields=[
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('task_display', models.CharField(blank=True, default='', max_length=128, verbose_name='Task display')),
                ('celery_task_id', models.UUIDField(default=None, null=True)),
                ('hosts_amount', models.IntegerField(default=0, verbose_name='Host amount')),
                ('date_start', models.DateTimeField(auto_now_add=True, verbose_name='Start time')),
                ('date_finished', models.DateTimeField(blank=True, null=True, verbose_name='End time')),
                ('timedelta', models.FloatField(default=0.0, null=True, verbose_name='Time')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Is finished')),
                ('is_success', models.BooleanField(default=False, verbose_name='Is success')),
                ('result', common.db.fields.JsonDictTextField(blank=True, null=True, verbose_name='Adhoc raw result')),
                ('summary', common.db.fields.JsonDictTextField(blank=True, null=True, verbose_name='Adhoc result summary')),
            ],
            options={
                'verbose_name': 'AdHoc execution',
                'db_table': 'ops_adhoc_execution',
                'get_latest_by': 'date_start',
            },
        ),
        migrations.CreateModel(
            name='CeleryTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024)),
                ('status', models.CharField(choices=[('waiting', 'waiting'), ('running', 'running'), ('finished', 'finished')], db_index=True, max_length=128)),
                ('log_path', models.CharField(blank=True, max_length=256, null=True)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('date_start', models.DateTimeField(null=True)),
                ('date_finished', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('is_periodic', models.BooleanField(default=False, verbose_name='Periodic perform')),
                ('interval', models.IntegerField(blank=True, default=24, null=True, verbose_name='Cycle perform')),
                ('crontab', models.CharField(blank=True, max_length=128, null=True, verbose_name='Regularly perform')),
                ('callback', models.CharField(blank=True, max_length=128, null=True, verbose_name='Callback')),
                ('is_deleted', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('total_run_amount', models.IntegerField(default=0)),
                ('success_run_amount', models.IntegerField(default=0)),
                ('latest_adhoc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_latest', to='ops.adhoc')),
                ('latest_execution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_latest', to='ops.adhocexecution')),
            ],
            options={
                'verbose_name': 'Task',
                'db_table': 'ops_task',
                'ordering': ('-date_updated',),
                'permissions': [('view_taskmonitor', 'Can view task monitor')],
                'get_latest_by': 'date_created',
            },
        ),
        migrations.CreateModel(
            name='CommandExecution',
            fields=[
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('command', models.TextField(verbose_name='Command')),
                ('_result', models.TextField(blank=True, null=True, verbose_name='Result')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Is finished')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('date_start', models.DateTimeField(null=True, verbose_name='Date start')),
                ('date_finished', models.DateTimeField(null=True, verbose_name='Date finished')),
                ('hosts', models.ManyToManyField(to='assets.Asset')),
                ('run_as', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.systemuser')),
            ],
            options={
                'verbose_name': 'Command execution',
            },
        ),
    ]
