# Generated by Django 3.2.14 on 2022-12-06 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('ops', '0001_initial'),
        ('assets', '0002_auto_20180105_1807'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commandexecution',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adhocexecution',
            name='adhoc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution',
                                    to='ops.adhoc'),
        ),
        migrations.AddField(
            model_name='adhocexecution',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution',
                                    to='ops.task'),
        ),
        migrations.AddField(
            model_name='adhoc',
            name='hosts',
            field=models.ManyToManyField(to='assets.Asset', verbose_name='Host'),
        ),
        migrations.AddField(
            model_name='adhoc',
            name='run_system_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.systemuser'),
        ),
        migrations.AddField(
            model_name='adhoc',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adhoc', to='ops.task'),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('name', 'org_id')},
        ),
    ]
