# Generated by Django 4.1.13 on 2024-09-06 08:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ops', '0002_celerytask'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adhoc',
            unique_together={('name', 'creator')},
        ),
        migrations.AlterUniqueTogether(
            name='playbook',
            unique_together={('name', 'creator')},
        ),
        migrations.AddField(
            model_name='adhoc',
            name='scope',
            field=models.CharField(default='public', max_length=64, verbose_name='Scope'),
        ),
        migrations.AddField(
            model_name='playbook',
            name='scope',
            field=models.CharField(default='public', max_length=64, verbose_name='Scope'),
        ),
        migrations.RemoveField(
            model_name='adhoc',
            name='org_id',
        ),
        migrations.RemoveField(
            model_name='playbook',
            name='org_id',
        ),
    ]
