# Generated by Django 4.1.13 on 2024-10-21 08:02
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0006_database_pg_ssl_mode'),
        ('ops', '0003_alter_adhoc_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='nodes',
            field=models.ManyToManyField(blank=True, to='assets.node', verbose_name='Node'),
        ),
        migrations.AlterField(
            model_name='job',
            name='assets',
            field=models.ManyToManyField(blank=True, to='assets.asset', verbose_name='Assets'),
        ),
        migrations.AlterUniqueTogether(
            name='job',
            unique_together={('name', 'org_id', 'creator', 'type')},
        ),
    ]
