# Generated by Django 2.1 on 2018-12-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0004_adhoc_run_as'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='adhoc',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='celerytask',
            name='status',
            field=models.CharField(
                choices=[('waiting', 'waiting'), ('running', 'running'),
                         ('finished', 'finished')], db_index=True,
                max_length=128),
        ),
    ]
