# Generated by Django 4.1.13 on 2024-10-15 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0005_historicaljob_periodic_variable_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljob",
            name="start_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Datetime when the schedule should begin triggering the task to run",
                null=True,
                verbose_name="Start Datetime",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="start_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Datetime when the schedule should begin triggering the task to run",
                null=True,
                verbose_name="Start Datetime",
            ),
        ),
    ]
