# Generated by Django 2.1.7 on 2019-07-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0006_auto_20190318_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhoc',
            name='_become',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Become'),
        ),
        migrations.AlterField(
            model_name='adhoc',
            name='created_by',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Create by'),
        ),
        migrations.AlterField(
            model_name='adhoc',
            name='run_as',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Username'),
        ),
    ]
