# Generated by Django 2.1.7 on 2019-09-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0007_auto_20190724_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Date updated'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date created'),
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'get_latest_by': 'date_created',
                     'ordering': ('-date_updated',)},
        ),
    ]
