# Generated by Django 4.1.13 on 2026-09-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0007_alter_historicaljob_crontab_alter_job_crontab"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adhoc",
            name="args",
            field=models.TextField(default="", max_length=65536, verbose_name="Args"),
        ),
        migrations.AlterField(
            model_name="historicaljob",
            name="args",
            field=models.TextField(
                blank=True,
                default="",
                max_length=65536,
                null=True,
                verbose_name="Args",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="args",
            field=models.TextField(
                blank=True,
                default="",
                max_length=65536,
                null=True,
                verbose_name="Args",
            ),
        ),
        migrations.AlterField(
            model_name="jobexecution",
            name="material",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Material"
            ),
        ),
    ]
