# Generated by Django 2.2.7 on 2020-01-06 07:34

import common.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0010_auto_20191217_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhoc',
            name='become',
            field=common.db.fields.EncryptJsonDictCharField(blank=True, default='', max_length=1024, null=True, verbose_name='Become'),
        ),
    ]
