# Generated by Django 2.2.7 on 2020-01-08 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0013_auto_20200108_1706'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdHocRunHistory',
            new_name='AdHocExecution',
        ),
    ]
