# Generated by Django 2.2.10 on 2020-02-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0015_auto_20200108_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandexecution',
            name='org_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization'),
        ),
    ]
