# Generated by Django 2.2.10 on 2020-05-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0017_auto_20200306_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandexecution',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='commandexecution',
            name='date_finished',
            field=models.DateTimeField(null=True, verbose_name='Date finished'),
        ),
        migrations.AlterField(
            model_name='commandexecution',
            name='date_start',
            field=models.DateTimeField(null=True, verbose_name='Date start'),
        ),
        migrations.AlterField(
            model_name='commandexecution',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='Is finished'),
        ),
    ]
