# Generated by Django 2.2.10 on 2020-05-08 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0017_auto_20200306_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandexecution',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='commandexecution',
            name='date_finished',
            field=models.DateTimeField(null=True, verbose_name='Date finished'),
        ),
        migrations.AlterField(
            model_name='commandexecution',
            name='date_start',
            field=models.DateTimeField(null=True, verbose_name='Date start'),
        ),
        migrations.AlterField(
            model_name='commandexecution',
            name='hosts',
            field=models.ManyToManyField(to='assets.Asset', verbose_name='Hosts'),
        ),
        migrations.AlterField(
            model_name='commandexecution',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='Is finished'),
        ),
        migrations.AlterField(
            model_name='commandexecution',
            name='run_as',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.SystemUser', verbose_name='Run as'),
        ),
        migrations.AlterField(
            model_name='commandexecution',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
