# Generated by Django 3.1 on 2020-12-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0018_auto_20200509_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhocexecution',
            name='celery_task_id',
            field=models.UUIDField(default=None, null=True),
        ),
    ]
