# Generated by Django 3.1.6 on 2021-07-14 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0076_delete_assetuser'),
        ('ops', '0019_adhocexecution_celery_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhoc',
            name='run_system_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.systemuser'),
        ),
    ]
