# Generated by Django 3.1.13 on 2021-11-30 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0020_adhoc_run_system_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adhoc',
            options={'get_latest_by': 'date_created', 'verbose_name': 'AdHoc'},
        ),
        migrations.AlterModelOptions(
            name='adhocexecution',
            options={'get_latest_by': 'date_start', 'verbose_name': 'AdHoc execution'},
        ),
        migrations.AlterModelOptions(
            name='commandexecution',
            options={'verbose_name': 'Command execution'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'get_latest_by': 'date_created', 'ordering': ('-date_updated',), 'verbose_name': 'Task'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'get_latest_by': 'date_created', 'ordering': ('-date_updated',), 'permissions': [('view_taskmonitor', 'Can view task monitor')], 'verbose_name': 'Task'},
        ),
    ]
