# Generated by Django 3.1.12 on 2022-02-11 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0021_auto_20211130_1037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'get_latest_by': 'date_created', 'ordering': ('-date_updated',), 'permissions': [('view_taskmonitor', 'Can view task monitor')], 'verbose_name': 'Task'},
        ),
    ]
