# Generated by Django 3.2.14 on 2022-08-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ops', '0021_auto_20211130_1037'),
    ]

    operations = [
        migrations.DeleteModel('CommandExecution'),
        migrations.RemoveField(model_name='adhocexecution', name='adhoc'),
        migrations.RemoveField(model_name='adhocexecution', name='task'),
        migrations.DeleteModel('AdHocExecution'),
        migrations.DeleteModel('AdHoc'),
        migrations.DeleteModel('Task'),
        migrations.DeleteModel('CeleryTask'),
    ]
