# Generated by Django 3.2.14 on 2022-09-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0022_auto_20220817_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celerytask',
            name='log_path',
        ),
        migrations.RemoveField(
            model_name='celerytask',
            name='status',
        ),
        migrations.AddField(
            model_name='celerytask',
            name='args',
            field=models.JSONField(default=[], verbose_name='Args'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='celerytask',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='Finished'),
        ),
        migrations.AddField(
            model_name='celerytask',
            name='kwargs',
            field=models.JSONField(default={}, verbose_name='Kwargs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='celerytask',
            name='state',
            field=models.CharField(default='SUCCESS', max_length=16, verbose_name='State'),
            preserve_default=False,
        ),
    ]
