# Generated by Django 3.2.14 on 2022-10-08 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0106_auto_20220916_1556'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ops', '0023_auto_20220929_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adhocexecution',
            name='adhoc',
        ),
        migrations.RemoveField(
            model_name='adhocexecution',
            name='task',
        ),
        migrations.RemoveField(
            model_name='commandexecution',
            name='hosts',
        ),
        migrations.RemoveField(
            model_name='commandexecution',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='task',
            name='latest_adhoc',
        ),
        migrations.RemoveField(
            model_name='task',
            name='latest_execution',
        ),
        migrations.DeleteModel(
            name='AdHoc',
        ),
        migrations.DeleteModel(
            name='AdHocExecution',
        ),
        migrations.DeleteModel(
            name='CommandExecution',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
