# Generated by Django 3.2.16 on 2022-12-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0023_auto_20220912_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celerytask',
            name='date_last_publish',
            field=models.DateTimeField(null=True, verbose_name='Date last publish'),
        ),
        migrations.AlterField(
            model_name='celerytaskexecution',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='Name'),
        ),
    ]
