# Generated by Django 3.2.14 on 2023-01-17 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0024_alter_celerytask_date_last_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbook',
            name='create_method',
            field=models.CharField(choices=[('blank', 'Blank'), ('upload', 'Upload'), ('vcs', 'VCS')], default='blank', max_length=128, verbose_name='CreateMethod'),
        ),
        migrations.AddField(
            model_name='playbook',
            name='vcs_url',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='VCS URL'),
        ),
    ]
