# Generated by Django 3.2.14 on 2022-10-08 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0106_auto_20220916_1556'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ops', '0024_auto_20221008_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdHoc',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('is_periodic', models.BooleanField(default=False)),
                ('interval', models.IntegerField(blank=True, default=24, null=True, verbose_name='Cycle perform')),
                ('crontab', models.CharField(blank=True, max_length=128, null=True, verbose_name='Regularly perform')),
                ('account', models.CharField(default='root', max_length=128, verbose_name='Account')),
                ('account_policy', models.CharField(default='root', max_length=128, verbose_name='Account policy')),
                ('date_last_run', models.DateTimeField(null=True, verbose_name='Date last run')),
                ('pattern', models.CharField(default='all', max_length=1024, verbose_name='Pattern')),
                ('module', models.CharField(default='shell', max_length=128, verbose_name='Module')),
                ('args', models.CharField(default='', max_length=1024, verbose_name='Args')),
                ('assets', models.ManyToManyField(to='assets.Asset', verbose_name='Assets')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdHocExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.CharField(default='running', max_length=16, verbose_name='Status')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='Result')),
                ('summary', models.JSONField(default=dict, verbose_name='Summary')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('date_start', models.DateTimeField(db_index=True, null=True, verbose_name='Date start')),
                ('date_finished', models.DateTimeField(null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='ops.adhoc', verbose_name='Adhoc')),
            ],
            options={
                'verbose_name': 'AdHoc execution',
                'db_table': 'ops_adhoc_execution',
                'get_latest_by': 'date_start',
            },
        ),
        migrations.AddField(
            model_name='adhoc',
            name='last_execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ops.adhocexecution', verbose_name='Last execution'),
        ),
        migrations.AddField(
            model_name='adhoc',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
    ]
