# Generated by Django 3.2.17 on 2023-04-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0024_alter_celerytask_date_last_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhoc',
            name='args',
            field=models.CharField(default='', max_length=8192, verbose_name='Args'),
        ),
        migrations.AlterField(
            model_name='historicaljob',
            name='args',
            field=models.CharField(blank=True, default='', max_length=8192, null=True, verbose_name='Args'),
        ),
        migrations.AlterField(
            model_name='job',
            name='args',
            field=models.CharField(blank=True, default='', max_length=8192, null=True, verbose_name='Args'),
        ),
        migrations.AlterField(
            model_name='jobexecution',
            name='material',
            field=models.CharField(blank=True, default='', max_length=8192, null=True, verbose_name='Material'),
        ),
    ]
