# Generated by Django 3.2.14 on 2023-02-03 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0025_auto_20230117_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobexecution',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='ops.job'),
        ),
    ]
