# Generated by Django 4.1.10 on 2023-09-22 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0026_auto_20230810_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='celerytaskexecution',
            options={'ordering': ['-date_start'], 'verbose_name': 'Celery Task Execution'},
        ),
    ]
