# Generated by Django 3.2.14 on 2022-10-24 09:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0026_auto_20221009_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTaskExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024)),
                ('args', models.JSONField(verbose_name='Args')),
                ('kwargs', models.JSONField(verbose_name='Kwargs')),
                ('state', models.CharField(max_length=16, verbose_name='State')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Finished')),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('date_start', models.DateTimeField(null=True)),
                ('date_finished', models.DateTimeField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='celerytask',
            old_name='date_finished',
            new_name='date_last_published',
        ),
        migrations.RemoveField(
            model_name='celerytask',
            name='args',
        ),
        migrations.RemoveField(
            model_name='celerytask',
            name='date_published',
        ),
        migrations.RemoveField(
            model_name='celerytask',
            name='date_start',
        ),
        migrations.RemoveField(
            model_name='celerytask',
            name='is_finished',
        ),
        migrations.RemoveField(
            model_name='celerytask',
            name='kwargs',
        ),
        migrations.RemoveField(
            model_name='celerytask',
            name='state',
        ),
        migrations.AddField(
            model_name='celerytask',
            name='description',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='celerytask',
            name='verbose_name',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
