# Generated by Django 3.2.14 on 2022-12-05 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0027_auto_20221024_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='owner',
            new_name='creator',
        ),
        migrations.RemoveField(
            model_name='adhoc',
            name='org_id',
        ),
        migrations.RemoveField(
            model_name='job',
            name='org_id',
        ),
        migrations.RemoveField(
            model_name='jobexecution',
            name='org_id',
        ),
        migrations.RemoveField(
            model_name='playbook',
            name='org_id',
        ),
    ]
