# Generated by Django 3.2.14 on 2022-10-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0027_auto_20221024_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='celerytask',
            name='last_published_time',
            field=models.DateTimeField(null=True),
        ),
    ]
