# Generated by Django 3.2.14 on 2022-10-24 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0027_auto_20221024_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celerytask',
            name='date_last_published',
        ),
        migrations.RemoveField(
            model_name='celerytask',
            name='description',
        ),
        migrations.RemoveField(
            model_name='celerytask',
            name='verbose_name',
        ),
    ]
