# Generated by Django 3.2.16 on 2023-02-13 07:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ops', '0027_auto_20230206_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playbook',
            options={'ordering': ['date_created']},
        ),
        migrations.AlterUniqueTogether(
            name='adhoc',
            unique_together={('name', 'org_id', 'creator')},
        ),
        migrations.AlterUniqueTogether(
            name='job',
            unique_together={('name', 'org_id', 'creator')},
        ),
        migrations.AlterUniqueTogether(
            name='playbook',
            unique_together={('name', 'org_id', 'creator')},
        ),
    ]
