# Generated by Django 3.2.14 on 2022-11-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0029_auto_20221111_1919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='celerytask',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='job',
            name='variables',
            field=models.JSONField(default=dict, verbose_name='Variables'),
        ),
        migrations.AlterField(
            model_name='celerytask',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='celerytaskexecution',
            name='date_finished',
            field=models.DateTimeField(null=True, verbose_name='Date finished'),
        ),
        migrations.AlterField(
            model_name='celerytaskexecution',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date published'),
        ),
        migrations.AlterField(
            model_name='celerytaskexecution',
            name='date_start',
            field=models.DateTimeField(null=True, verbose_name='Date start'),
        ),
    ]
