# Generated by Django 3.2.14 on 2022-12-20 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0029_auto_20221215_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAuditLog',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ops.jobexecution',),
        ),
    ]
