# Generated by Django 3.2.14 on 2022-11-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0031_auto_20221116_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='variables',
        ),
        migrations.AddField(
            model_name='job',
            name='parameters_define',
            field=models.JSONField(default=dict, verbose_name='Parameters define'),
        ),
        migrations.AddField(
            model_name='jobexecution',
            name='parameters',
            field=models.JSONField(default=dict, verbose_name='Parameters'),
        ),
    ]
