# Generated by Django 3.2.14 on 2022-12-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0031_auto_20221220_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaljob',
            name='created_by',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='historicaljob',
            name='updated_by',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by'),
        ),
    ]
