# Generated by Django 3.2.16 on 2022-12-23 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0032_auto_20221221_1513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adhoc',
            options={'verbose_name': 'AdHoc'},
        ),
        migrations.AlterModelOptions(
            name='celerytask',
            options={'ordering': ('name',), 'verbose_name': 'Celery Task'},
        ),
        migrations.AlterModelOptions(
            name='celerytaskexecution',
            options={'verbose_name': 'Celery Task Execution'},
        ),
        migrations.AlterModelOptions(
            name='historicaljob',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Job', 'verbose_name_plural': 'historical Jobs'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['date_created'], 'verbose_name': 'Job'},
        ),
        migrations.AlterModelOptions(
            name='jobauditlog',
            options={'verbose_name': 'Job audit log'},
        ),
        migrations.AlterModelOptions(
            name='jobexecution',
            options={'ordering': ['-date_created'], 'verbose_name': 'Job Execution'},
        ),
    ]
