# Generated by Django 3.2.14 on 2022-11-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0032_auto_20221117_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='crontab',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Regularly perform'),
        ),
        migrations.AddField(
            model_name='job',
            name='interval',
            field=models.IntegerField(blank=True, default=24, null=True, verbose_name='Cycle perform'),
        ),
        migrations.AddField(
            model_name='job',
            name='is_periodic',
            field=models.BooleanField(default=False),
        ),
    ]
