# Generated by Django 3.2.16 on 2022-12-27 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0033_auto_20221223_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='celerytask',
            options={'ordering': ('name',), 'permissions': [('view_taskmonitor', 'Can view task monitor')], 'verbose_name': 'Celery Task'},
        ),
    ]
