# Generated by Django 3.2.14 on 2022-11-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0034_job_org_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobexecution',
            name='org_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization'),
        ),
    ]
