# Generated by Django 3.2.14 on 2022-11-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0035_jobexecution_org_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['date_created']},
        ),
        migrations.AlterModelOptions(
            name='jobexecution',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='job',
            name='use_parameter_define',
            field=models.BooleanField(default=False, verbose_name='Use Parameter Define'),
        ),
    ]
