# Generated by Django 3.2.14 on 2022-11-28 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0035_jobexecution_org_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['date_created']},
        ),
        migrations.AlterModelOptions(
            name='jobexecution',
            options={'ordering': ['-date_created']},
        ),
    ]
