# Generated by Django 3.2.14 on 2022-11-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0036_auto_20221129_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adhoc',
            old_name='owner',
            new_name='creator',
        ),
        migrations.AddField(
            model_name='adhoc',
            name='org_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization'),
        ),
        migrations.DeleteModel(
            name='AdHocExecution',
        ),
    ]
