# Generated by Django 3.2.14 on 2022-11-29 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ops', '0038_playbook_org_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playbook',
            name='owner',
        ),
        migrations.AddField(
            model_name='playbook',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
    ]
