# Generated by Django 3.2.14 on 2022-11-29 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0036_auto_20221128_1839'),
        ('ops', '0039_auto_20221129_1932'),
    ]

    operations = [
    ]
