# Generated by Django 3.2.14 on 2022-11-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0040_merge_0036_auto_20221128_1839_0039_auto_20221129_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhoc',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='playbook',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Comment'),
        ),
    ]
