# Generated by Django 3.2.14 on 2022-12-06 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('applications', '0003_auto_20191210_1659'),
        ('assets', '0002_auto_20180105_1807'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perms', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userassetgrantedtreenoderelation',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetpermission',
            name='assets',
            field=models.ManyToManyField(blank=True, related_name='granted_by_permissions', to='assets.Asset',
                                         verbose_name='Asset'),
        ),
        migrations.AddField(
            model_name='assetpermission',
            name='nodes',
            field=models.ManyToManyField(blank=True, related_name='granted_by_permissions', to='assets.Node',
                                         verbose_name='Nodes'),
        ),
        migrations.AddField(
            model_name='assetpermission',
            name='system_users',
            field=models.ManyToManyField(blank=True, related_name='granted_by_permissions', to='assets.SystemUser',
                                         verbose_name='System user'),
        ),
        migrations.AddField(
            model_name='assetpermission',
            name='user_groups',
            field=models.ManyToManyField(blank=True, related_name='assetpermissions', to='users.UserGroup',
                                         verbose_name='User group'),
        ),
        migrations.AddField(
            model_name='assetpermission',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='assetpermissions', to=settings.AUTH_USER_MODEL,
                                         verbose_name='User'),
        ),
        migrations.AddField(
            model_name='applicationpermission',
            name='applications',
            field=models.ManyToManyField(blank=True, related_name='granted_by_permissions',
                                         to='applications.Application', verbose_name='Application'),
        ),
        migrations.AddField(
            model_name='applicationpermission',
            name='system_users',
            field=models.ManyToManyField(blank=True, related_name='granted_by_application_permissions',
                                         to='assets.SystemUser', verbose_name='System user'),
        ),
        migrations.AddField(
            model_name='applicationpermission',
            name='user_groups',
            field=models.ManyToManyField(blank=True, related_name='applicationpermissions', to='users.UserGroup',
                                         verbose_name='User group'),
        ),
        migrations.AddField(
            model_name='applicationpermission',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='applicationpermissions', to=settings.AUTH_USER_MODEL,
                                         verbose_name='User'),
        ),
        migrations.AlterUniqueTogether(
            name='assetpermission',
            unique_together={('org_id', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='applicationpermission',
            unique_together={('org_id', 'name')},
        ),
    ]
