# Generated by Django 4.1.13 on 2024-05-09 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_auto_20180105_1807'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('perms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userassetgrantedtreenoderelation',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetpermission',
            name='assets',
            field=models.ManyToManyField(blank=True, related_name='granted_by_permissions', to='assets.asset', verbose_name='Asset'),
        ),
        migrations.AddField(
            model_name='assetpermission',
            name='nodes',
            field=models.ManyToManyField(blank=True, related_name='granted_by_permissions', to='assets.node', verbose_name='Node'),
        ),
        migrations.AddField(
            model_name='assetpermission',
            name='user_groups',
            field=models.ManyToManyField(blank=True, related_name='%(class)ss', to='users.usergroup', verbose_name='User group'),
        ),
        migrations.AddField(
            model_name='assetpermission',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterUniqueTogether(
            name='assetpermission',
            unique_together={('org_id', 'name')},
        ),
    ]
