# Generated by Django 4.1.13 on 2026-06-17

from django.db import migrations, models
import perms.models.asset_permission


class Migration(migrations.Migration):

    dependencies = [
        ('perms', '0003_alter_assetpermission_date_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetpermission',
            name='clipboard_policy',
            field=models.JSONField(default=perms.models.asset_permission.default_clipboard_policy, verbose_name='Clipboard policy'),
        ),
    ]