# Generated by Django 2.1.7 on 2019-04-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perms', '0003_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetpermission',
            name='actions',
            field=models.ManyToManyField(blank=True, related_name='permissions', to='perms.Action', verbose_name='Action'),
        ),
    ]
