# Generated by Django 2.1.7 on 2019-05-21 03:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perms', '0005_auto_20190520_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetpermission',
            name='user_groups',
            field=models.ManyToManyField(blank=True, to='users.UserGroup', verbose_name='User group'),
        ),
        migrations.AlterField(
            model_name='assetpermission',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='remoteapppermission',
            name='user_groups',
            field=models.ManyToManyField(blank=True, to='users.UserGroup', verbose_name='User group'),
        ),
        migrations.AlterField(
            model_name='remoteapppermission',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
