# Generated by Django 2.0.7 on 2018-08-07 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perms', '0006_auto_20180606_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetpermission',
            name='org_id',
            field=models.CharField(blank=True, default=None, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='nodepermission',
            name='org_id',
            field=models.CharField(blank=True, default=None, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='assetpermission',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Name'),
        ),
        migrations.AlterUniqueTogether(
            name='assetpermission',
            unique_together={('org_id', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='nodepermission',
            unique_together=set(),
        ),

    ]
