# Generated by Django 2.1.7 on 2019-05-21 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perms', '0006_auto_20190521_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remoteapppermission',
            name='remote_apps',
            field=models.ManyToManyField(blank=True, related_name='granted_by_permissions', to='applications.RemoteApp', verbose_name='RemoteApp'),
        ),
    ]
