# Generated by Django 2.1.7 on 2019-06-28 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perms', '0006_auto_20190628_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetpermission',
            name='actions',
        ),
        migrations.RenameField(
            model_name='assetpermission',
            old_name='action',
            new_name='actions',
        ),
        migrations.DeleteModel('action'),
    ]
