# Generated by Django 2.1.7 on 2019-09-11 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perms', '0007_remove_assetpermission_actions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetpermission',
            options={'ordering': ('name',), 'verbose_name': 'Asset permission'},
        ),
    ]
