# Generated by Django 2.1.7 on 2019-09-11 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perms', '0007_remove_assetpermission_actions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodepermission',
            name='node',
        ),
        migrations.RemoveField(
            model_name='nodepermission',
            name='system_user',
        ),
        migrations.RemoveField(
            model_name='nodepermission',
            name='user_group',
        ),
        migrations.AlterModelOptions(
            name='assetpermission',
            options={'ordering': ('name',), 'verbose_name': 'Asset permission'},
        ),
        migrations.DeleteModel(
            name='NodePermission',
        ),
    ]
