# Generated by Django 2.1 on 2018-09-03 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perms', '0008_auto_20180816_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetpermission',
            options={'verbose_name': 'Asset permission'},
        ),
    ]
