# Generated by Django 2.2.13 on 2020-08-21 08:20

from django.db import migrations
from perms.tasks import build_users_perm_tree_celery_task


def start_build_users_perm_tree_task(apps, schema_editor):
    build_users_perm_tree_celery_task.delay()


class Migration(migrations.Migration):

    dependencies = [
        ('perms', '0013_rebuildusertreetask_usergrantedmappingnode'),
    ]

    operations = [
        migrations.RunPython(start_build_users_perm_tree_task)
    ]
