# Generated by Django 2.2.13 on 2020-08-17 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perms', '0013_grantednode'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantednode',
            name='asset_granted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
