# Generated by Django 2.2.13 on 2020-08-21 08:20

from django.db import migrations
from perms.utils.user_node_tree import rebuild_mapping_nodes


def build_users_perm_tree(apps, schema_editor):
    from users.models import User
    for user in User.objects.all():
        print(f'build_mapping_nodes for {user} begin')
        rebuild_mapping_nodes(user)
        print(f'build_mapping_nodes for {user} finish')


class Migration(migrations.Migration):

    dependencies = [
        ('perms', '0013_rebuildusertreetask_usergrantedmappingnode'),
    ]

    operations = [
        migrations.RunPython(build_users_perm_tree)
    ]
