# Generated by Django 2.2.13 on 2020-09-29 09:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perms', '0014_build_users_perm_tree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetpermission',
            name='user_groups',
            field=models.ManyToManyField(blank=True, related_name='%(class)ss', to='users.usergroup', verbose_name='User group'),
        ),
        migrations.AlterField(
            model_name='assetpermission',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='databaseapppermission',
            name='user_groups',
            field=models.ManyToManyField(blank=True, related_name='databaseapppermissions', to='users.UserGroup', verbose_name='User group'),
        ),
        migrations.AlterField(
            model_name='databaseapppermission',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='databaseapppermissions', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='k8sapppermission',
            name='user_groups',
            field=models.ManyToManyField(blank=True, related_name='k8sapppermissions', to='users.UserGroup', verbose_name='User group'),
        ),
        migrations.AlterField(
            model_name='k8sapppermission',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='k8sapppermissions', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='remoteapppermission',
            name='user_groups',
            field=models.ManyToManyField(blank=True, related_name='remoteapppermissions', to='users.UserGroup', verbose_name='User group'),
        ),
        migrations.AlterField(
            model_name='remoteapppermission',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='remoteapppermissions', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
