# Generated by Django 2.2.13 on 2020-08-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perms', '0014_grantednode_asset_granted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grantednode',
            name='asset_granted',
        ),
        migrations.AddField(
            model_name='grantednode',
            name='asset_granted_count',
            field=models.IntegerField(default=0),
        ),
    ]
