# Generated by Django 2.2.13 on 2020-08-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perms', '0015_auto_20200817_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantednode',
            name='key',
            field=models.CharField(db_index=True, max_length=64, verbose_name='Key'),
        ),
    ]
