# Generated by Django 3.1 on 2021-01-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0066_auto_20210130_1426'),
        ('perms', '0017_auto_20210104_0435'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'assets_asset_nodes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PermAsset',
            fields=[
                ('asset_id', models.UUIDField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'perms_assetpermission_assets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PermNode',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('assets.node',),
        ),
        migrations.AddField(
            model_name='usergrantedmappingnode',
            name='org_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization'),
        ),
    ]
