# Generated by Django 3.1.12 on 2021-09-06 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perms', '0018_auto_20210208_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationpermission',
            name='from_ticket',
            field=models.BooleanField(default=False, verbose_name='From ticket'),
        ),
        migrations.AddField(
            model_name='assetpermission',
            name='from_ticket',
            field=models.BooleanField(default=False, verbose_name='From ticket'),
        ),
    ]
