# Generated by Django 3.1 on 2021-01-30 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perms', '0018_auto_20210130_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergrantedmappingnode',
            name='org_id',
        ),
    ]
