# Generated by Django 3.1.12 on 2021-08-31 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perms', '0018_auto_20210208_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationpermission',
            name='authorization_rules',
            field=models.CharField(choices=[('manual', 'Manual authorization'), ('ticket', 'Ticket authorization')], default='manual', max_length=64, verbose_name='Authorization rules'),
        ),
        migrations.AddField(
            model_name='assetpermission',
            name='authorization_rules',
            field=models.CharField(choices=[('manual', 'Manual authorization'), ('ticket', 'Ticket authorization')], default='manual', max_length=64, verbose_name='Authorization rules'),
        ),
    ]
