# Generated by Django 3.1.12 on 2021-09-10 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0076_delete_assetuser'),
        ('perms', '0019_auto_20210906_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetpermission',
            name='system_users',
            field=models.ManyToManyField(blank=True, related_name='granted_by_permissions', to='assets.SystemUser', verbose_name='System user'),
        ),
        migrations.AlterField(
            model_name='applicationpermission',
            name='system_users',
            field=models.ManyToManyField(blank=True, related_name='granted_by_application_permissions', to='assets.SystemUser', verbose_name='System user'),
        ),
    ]
