# Generated by Django 3.1 on 2021-01-30 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0009_auto_20201023_1628'),
        ('perms', '0019_remove_usergrantedmappingnode_org_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergrantedmappingnode',
            name='org',
            field=models.ForeignKey(db_constraint=False, default='', on_delete=django.db.models.deletion.CASCADE, to='orgs.organization'),
        ),
    ]
