# Generated by Django 3.1 on 2021-01-30 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0066_auto_20210130_1426'),
        ('perms', '0021_userassetgrantedtreenoderelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeAssetThrouth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'assets_asset_nodes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PermAssetThrouth',
            fields=[
                ('asset_id', models.UUIDField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'perms_assetpermission_assets',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='NodeAsset',
        ),
        migrations.DeleteModel(
            name='PermAsset',
        ),
        migrations.AlterModelOptions(
            name='permnode',
            options={'ordering': []},
        ),
        migrations.RemoveField(
            model_name='userassetgrantedtreenoderelation',
            name='id',
        ),
        migrations.AlterField(
            model_name='userassetgrantedtreenoderelation',
            name='node',
            field=models.ForeignKey(db_constraint=False, default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='assets.node'),
        ),
    ]
