# Generated by Django 3.1.13 on 2022-02-17 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perms', '0023_auto_20220112_2035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationpermission',
            options={'ordering': ('name',), 'verbose_name': 'Application permission'},
        ),
        migrations.AlterModelOptions(
            name='assetpermission',
            options={'ordering': ('name',), 'verbose_name': 'Asset permission'},
        ),
    ]
