# Generated by Django 3.1.14 on 2022-03-10 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0018_auto_20220223_1539'),
        ('perms', '0026_auto_20220307_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermedApplication',
            fields=[
            ],
            options={
                'verbose_name': 'Permed application',
                'permissions': [('view_myapps', 'Can view my apps'), ('view_userapps', 'Can view user apps'), ('view_usergroupapps', 'Can view usergroup apps')],
                'proxy': True,
                'default_permissions': [],
                'indexes': [],
                'constraints': [],
            },
            bases=('applications.application',),
        ),
        migrations.AlterModelOptions(
            name='applicationpermission',
            options={'ordering': ('name',), 'permissions': [], 'verbose_name': 'Application permission'},
        ),
        migrations.AlterModelOptions(
            name='assetpermission',
            options={'ordering': ('name',), 'permissions': [], 'verbose_name': 'Asset permission'},
        ),
    ]
