# Generated by Django 3.1.14 on 2022-03-09 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0019_databaseapp_kubernetesapp_remoteapp'),
        ('perms', '0026_auto_20220307_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermedApplication',
            fields=[
            ],
            options={
                'verbose_name': 'Permed application',
                'permissions': [('view_userapps', 'Can view user apps'), ('view_usergroupapps', 'Can view usergroup apps')],
                'proxy': True,
                'default_permissions': [],
                'indexes': [],
                'constraints': [],
            },
            bases=('applications.application',),
        ),
        migrations.CreateModel(
            name='PermedDatabaseApp',
            fields=[
            ],
            options={
                'verbose_name': 'Database application',
                'permissions': [('view_mydatabaseapp', 'Can view my database application'), ('connect_mydatabaseapp', 'Can connect my database application')],
                'proxy': True,
                'default_permissions': [],
                'indexes': [],
                'constraints': [],
            },
            bases=('applications.application',),
        ),
        migrations.CreateModel(
            name='PermedKubernetesApp',
            fields=[
            ],
            options={
                'verbose_name': 'Kubernetes',
                'permissions': [('view_mykubernetesapp', 'Can view my kubernetes application'), ('connect_mykubernetesapp', 'Can connect my kubernetes application')],
                'proxy': True,
                'default_permissions': [],
                'indexes': [],
                'constraints': [],
            },
            bases=('applications.application',),
        ),
        migrations.CreateModel(
            name='PermedRemoteApp',
            fields=[
            ],
            options={
                'verbose_name': 'Permed remote application',
                'permissions': [('view_myremoteapp', 'Can view my remoteapp'), ('connect_myremoteapp', 'Can connect my remoteapp')],
                'proxy': True,
                'default_permissions': [],
                'indexes': [],
                'constraints': [],
            },
            bases=('applications.application',),
        ),
        migrations.AlterModelOptions(
            name='applicationpermission',
            options={'ordering': ('name',), 'permissions': [('view_permuserapplication', 'Can view application of permission to user')], 'verbose_name': 'Application permission'},
        ),
        migrations.AlterModelOptions(
            name='assetpermission',
            options={'ordering': ('name',), 'permissions': [('view_permuserasset', 'Can view asset of permission to user'), ('view_permusergroupasset', 'Can view asset of permission to user group')], 'verbose_name': 'Asset permission'},
        ),
    ]
