# Generated by Django 3.2.14 on 2022-07-28 09:10

from django.db import migrations, models


def migrate_system_user_to_accounts(apps, schema_editor):
    # Todo: 迁移 系统用户为账号
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('perms', '0028_auto_20220316_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetpermission',
            name='accounts',
            field=models.JSONField(default=list, verbose_name='Accounts'),
        ),
        migrations.RunPython(migrate_system_user_to_accounts),
        migrations.RemoveField(
            model_name='assetpermission',
            name='system_users',
        ),
    ]
