# Generated by Django 3.2.14 on 2022-08-16 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perms', '0030_auto_20220816_1132'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applicationpermission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='applicationpermission',
            name='applications',
        ),
        migrations.RemoveField(
            model_name='applicationpermission',
            name='system_users',
        ),
        migrations.RemoveField(
            model_name='applicationpermission',
            name='user_groups',
        ),
        migrations.RemoveField(
            model_name='applicationpermission',
            name='users',
        ),
        migrations.DeleteModel(
            name='PermedApplication',
        ),
        migrations.DeleteModel(
            name='ApplicationPermission',
        ),
    ]
