# Generated by Django 3.2.14 on 2022-11-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0111_alter_automationexecution_status'),
        ('perms', '0031_auto_20220816_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermedAccount',
            fields=[
            ],
            options={
                'verbose_name': 'Permed account',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('assets.account',),
        ),
        migrations.AlterField(
            model_name='assetpermission',
            name='actions',
            field=models.IntegerField(default=0, verbose_name='Actions'),
        ),
    ]
