# Generated by Django 3.2.14 on 2022-11-18 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perms', '0032_auto_20221111_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetpermission',
            name='actions',
            field=models.IntegerField(default=1, verbose_name='Actions'),
        ),
    ]
