# Generated by Django 3.2.17 on 2023-05-25 09:34

from django.db import migrations


def migrate_asset_permission_delete_perm(apps, *args):
    asset_permission_cls = apps.get_model('perms', 'AssetPermission')
    asset_permission_cls.objects.filter(actions__gte=31).update(actions=63)


class Migration(migrations.Migration):
    dependencies = [
        ('perms', '0033_auto_20221220_1956'),
    ]

    operations = [
        migrations.RunPython(migrate_asset_permission_delete_perm)
    ]
