# Generated by Django 3.1 on 2021-03-05 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0002_loginassetacl_org_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginacl',
            options={'ordering': ('priority', 'name')},
        ),
        migrations.AlterModelOptions(
            name='loginassetacl',
            options={'ordering': ('priority', 'name')},
        ),
    ]
