# Generated by Django 3.1 on 2021-03-26 07:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Created by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
                ('category', models.CharField(choices=[('operating_system', 'Operating System'), ('cloud_service', 'Cloud Service'), ('website', ' Website'), ('database', 'Database'), ('application', 'Application'), ('network_device', 'Network Device')], default='operating_system', max_length=128, verbose_name='Category')),
                ('protocol', models.CharField(max_length=128, verbose_name='Protocol')),
                ('secret_type', models.CharField(choices=[('ssh_key', 'SSH Key'), ('password', 'Password'), ('cert', 'Certificate'), ('token', 'Token'), ('text', 'Text')], default='password', max_length=128, verbose_name='Secret type')),
                ('fields_definition', models.JSONField(default=list)),
                ('is_builtin', models.BooleanField(default=False, verbose_name='Built-in')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Safe',
            fields=[
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Created by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
            ],
            options={
                'unique_together': {('name', 'org_id')},
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Created by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('username', models.CharField(max_length=2048, verbose_name='Username')),
                ('secret', models.TextField(max_length=4096, verbose_name='Secret')),
                ('address', models.CharField(max_length=4096, verbose_name='Address')),
                ('attrs', models.JSONField(default=dict, verbose_name='Attributes')),
                ('is_privileged', models.BooleanField(default=False, verbose_name='Privileged')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('safe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.safe', verbose_name='Safe')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.accounttype', verbose_name='Type')),
            ],
            options={
                'unique_together': {('name', 'safe')},
            },
        ),
    ]
