# Generated by Django 3.1 on 2021-03-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='secret_type',
            field=models.CharField(choices=[('ssh_keys', 'SSH Keys'), ('password', 'Password'), ('cert', 'Certificate'), ('token', 'Token'), ('text', 'Text')], default='password', max_length=128, verbose_name='Secret type'),
        ),
    ]
