# Generated by Django 2.2.13 on 2020-10-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='secret_type',
        ),
        migrations.AddField(
            model_name='accounttype',
            name='secret_type',
            field=models.CharField(choices=[('password', 'Password'), ('ssh-key', 'SSH Key'), ('token', 'Token'), ('cert', 'Cert')], default=1, max_length=32, verbose_name='Secret type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='category',
            field=models.CharField(choices=[('os', 'Operation System'), ('database', 'Database'), ('network_device', 'Network Device'), ('app', 'Application'), ('cloud', 'Cloud'), ('other', 'Other')], default='os', max_length=64, verbose_name='Category'),
        ),
    ]
