# Generated by Django 3.2.14 on 2023-01-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_automation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automationexecution',
            options={'permissions': [('view_changesecretexecution', 'Can view change secret execution'), ('add_changesecretexection', 'Can add change secret execution'), ('view_gatheraccountsexecution', 'Can view gather accounts execution'), ('add_gatheraccountsexecution', 'Can add gather accounts execution'), ('view_pushaccountexecution', 'Can view push account execution'), ('add_pushaccountexecution', 'Can add push account execution')], 'verbose_name': 'Automation execution', 'verbose_name_plural': 'Automation executions'},
        ),
        migrations.AlterModelOptions(
            name='changesecretrecord',
            options={'ordering': ('-date_started',), 'verbose_name': 'Change secret record'},
        ),
        migrations.AddField(
            model_name='pushaccountautomation',
            name='action',
            field=models.CharField(default='create_and_push', max_length=16, verbose_name='Action'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pushaccountautomation',
            name='triggers',
            field=models.JSONField(default=list, max_length=16, verbose_name='Triggers'),
        ),
    ]
