# Generated by Django 4.1.13 on 2024-08-26 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_myasset'),
        ('accounts', '0003_automation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changesecretrecord',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='changesecretrecord',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='changesecretrecord',
            name='execution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.automationexecution'),
        ),
    ]
