# Generated by Django 3.2.16 on 2022-12-29 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_automationexecution_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountbackupexecution',
            options={'ordering': ('-date_start',), 'verbose_name': 'Account backup execution'},
        ),
    ]
