# Generated by Django 3.1 on 2021-04-29 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210407_1831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='safe',
            options={'ordering': ('name',)},
        ),
        migrations.RenameField(
            model_name='accounttype',
            old_name='fields_definition',
            new_name='properties',
        ),
    ]
