# Generated by Django 3.2.16 on 2023-01-10 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20230106_1507'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changesecretrecord',
            options={'ordering': ('-date_created',), 'verbose_name': 'Change secret record'},
        ),
    ]
