# Generated by Django 4.1.13 on 2025-03-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0005_accountrisk_backupaccountautomation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountrisk',
            name='username',
            field=models.CharField(max_length=128, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='gatheredaccount',
            name='address_last_login',
            field=models.CharField(default='', max_length=45, null=True, verbose_name='Address login'),
        ),
        migrations.AlterField(
            model_name='gatheredaccount',
            name='username',
            field=models.CharField(blank=True, db_index=True, max_length=128, verbose_name='Username'),
        ),
    ]
