# Generated by Django 4.1.13 on 2024-10-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_accountcheckautomation_accountrisk"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="date_change_secret",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date change secret"
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="date_discovery",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date discovery"
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="connectivity",
            field=models.CharField(
                choices=[
                    ("-", "Unknown"),
                    ("na", "N/A"),
                    ("ok", "OK"),
                    ("err", "Error"),
                ],
                default="-",
                max_length=16,
                verbose_name="Connectivity",
            ),
        ),
    ]
