# Generated by Django 3.2.16 on 2023-02-23 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_account_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gatheredaccount',
            options={'ordering': ['asset'], 'verbose_name': 'Gather account automation'},
        ),
    ]
