# Generated by Django 4.1.13 on 2024-11-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_accountrisk_risk"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accountrisk",
            name="confirmed",
        ),
        migrations.AddField(
            model_name="accountrisk",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("confirmed", "Confirmed"), ("ignored", "Ignored")],
                default="",
                max_length=32,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="accountrisk",
            name="risk",
            field=models.CharField(
                choices=[
                    ("zombie", "Long time no login"),
                    ("ghost", "Not managed"),
                    ("long_time_password", "Long time no change"),
                    ("weak_password", "Weak password"),
                    ("password_error", "Password error"),
                    ("password_expired", "Password expired"),
                    ("group_changed", "Group change"),
                    ("sudo_changed", "Sudo changed"),
                    ("authorized_keys_changed", "Authorized keys changed"),
                    ("account_deleted", "Account delete"),
                    ("no_admin_account", "No admin account"),
                    ("others", "Others"),
                ],
                max_length=128,
                verbose_name="Risk",
            ),
        ),
        migrations.AddField(
                    model_name='changesecretautomation',
                    name='check_conn_after_change',
                    field=models.BooleanField(default=True, verbose_name='Check connection after change'),
                ),
                migrations.AddField(
                    model_name='pushaccountautomation',
                    name='check_conn_after_change',
                    field=models.BooleanField(default=True, verbose_name='Check connection after change'),
                ),
    ]
