# Generated by Django 4.1.13 on 2026-06-08 00:00

import common.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_account_connectivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='otp_secret_key',
            field=common.db.fields.EncryptCharField(blank=True, max_length=128, null=True, verbose_name='OTP secret key'),
        ),
    ]
