# Generated by Django 4.1.13 on 2024-10-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_account_date_change_secret_account_date_discovery_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="access_by",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Access by"
            ),
        ),
    ]
