# Generated by Django 5.2.15 on 2026-08-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_vault_secret_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='secret_type',
            field=models.CharField(choices=[('password', 'Password'), ('ssh_key', 'SSH key'), ('ssh_certificate', 'SSH certificate'), ('access_key', 'Access key'), ('token', 'Token'), ('api_key', 'API key')], default='password', max_length=16, verbose_name='Secret type'),
        ),
        migrations.AlterField(
            model_name='accounttemplate',
            name='secret_type',
            field=models.CharField(choices=[('password', 'Password'), ('ssh_key', 'SSH key'), ('ssh_certificate', 'SSH certificate'), ('access_key', 'Access key'), ('token', 'Token'), ('api_key', 'API key')], default='password', max_length=16, verbose_name='Secret type'),
        ),
        migrations.AlterField(
            model_name='changesecretautomation',
            name='secret_type',
            field=models.CharField(choices=[('password', 'Password'), ('ssh_key', 'SSH key'), ('ssh_certificate', 'SSH certificate'), ('access_key', 'Access key'), ('token', 'Token'), ('api_key', 'API key')], default='password', max_length=16, verbose_name='Secret type'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='secret_type',
            field=models.CharField(choices=[('password', 'Password'), ('ssh_key', 'SSH key'), ('ssh_certificate', 'SSH certificate'), ('access_key', 'Access key'), ('token', 'Token'), ('api_key', 'API key')], default='password', max_length=16, verbose_name='Secret type'),
        ),
        migrations.AlterField(
            model_name='pushaccountautomation',
            name='secret_type',
            field=models.CharField(choices=[('password', 'Password'), ('ssh_key', 'SSH key'), ('ssh_certificate', 'SSH certificate'), ('access_key', 'Access key'), ('token', 'Token'), ('api_key', 'API key')], default='password', max_length=16, verbose_name='Secret type'),
        ),
    ]
