# Generated by Django 3.2.16 on 2023-03-07 07:36

from django.db import migrations


def migrate_account_usernames_to_ids(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    execution_model = apps.get_model('accounts', 'AutomationExecution')
    account_model = apps.get_model('accounts', 'Account')
    executions = execution_model.objects.using(db_alias).all()
    executions_update = []
    for execution in executions:
        snapshot = execution.snapshot
        automation = execution.automation
        accounts = account_model.objects.none()
        account_usernames = automation.accounts
        for asset in automation.get_all_assets():
            accounts = accounts | asset.accounts.all()
        secret_type = snapshot.get('secret_type')
        if secret_type:
            ids = accounts.filter(
                username__in=account_usernames,
                secret_type=secret_type
            ).values_list('id', flat=True)
        else:
            ids = accounts.filter(
                username__in=account_usernames
            ).values_list('id', flat=True)
        snapshot['accounts'] = [str(_id) for _id in ids]
        execution.snapshot = snapshot
        executions_update.append(execution)

    execution_model.objects.bulk_update(executions_update, ['snapshot'])




class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_gatheredaccount_options'),
    ]

    operations = [
        migrations.RunPython(migrate_account_usernames_to_ids),
    ]
