# Generated by Django 4.1.13 on 2024-10-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_account_access_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="date_discovery",
        ),
        migrations.AddField(
            model_name="account",
            name="change_secret_status",
            field=models.CharField(
                blank=True,
                max_length=16,
                null=True,
                verbose_name="Change secret status",
            ),
        ),
    ]
