# Generated by Django 5.2.13 on 2026-07-29 10:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_vault_secret_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationapplication',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_applications', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.CreateModel(
            name='IntegrationApplicationAgent',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('hostname', models.CharField(blank=True, max_length=255, verbose_name='Hostname')),
                ('platform', models.CharField(blank=True, max_length=64, verbose_name='Platform')),
                ('version', models.CharField(blank=True, max_length=64, verbose_name='Version')),
                ('date_last_used', models.DateTimeField(blank=True, null=True, verbose_name='Date last used')),
                ('error', models.TextField(blank=True, verbose_name='Error')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='accounts.integrationapplication', verbose_name='Application')),
            ],
            options={
                'verbose_name': 'Integration application Agent',
            },
        ),
        migrations.CreateModel(
            name='ApplicationAccountSwitch',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('status', models.CharField(choices=[('running', 'Running'), ('waiting_confirmation', 'Waiting for confirmation'), ('completed', 'Completed'), ('rolling_back', 'Rolling back'), ('rolled_back', 'Rolled back'), ('ended', 'Manually ended')], default='running', max_length=32, verbose_name='Status')),
                ('date_finished', models.DateTimeField(blank=True, null=True, verbose_name='Date finished')),
                ('source_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_switches_as_source', to='accounts.account', verbose_name='Source account')),
                ('target_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_switches_as_target', to='accounts.account', verbose_name='Target account')),
            ],
            options={
                'verbose_name': 'Application account switch',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationAccountBinding',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_bindings', to='accounts.integrationapplication', verbose_name='Application')),
                ('current_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_bindings', to='accounts.account', verbose_name='Current account')),
            ],
            options={
                'verbose_name': 'Application account binding',
                'ordering': ['application__name', 'current_account__name'],
                'unique_together': {('application', 'current_account')},
            },
        ),
        migrations.CreateModel(
            name='ApplicationAccountSwitchItem',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('status', models.CharField(choices=[('pending', 'Pending delivery'), ('delivered', 'Waiting for confirmation'), ('failed', 'Delivery failed'), ('confirmed', 'Confirmed'), ('rollback_pending', 'Rollback pending'), ('rollback_delivered', 'Rollback waiting for confirmation'), ('rolled_back', 'Rolled back')], default='pending', max_length=32, verbose_name='Status')),
                ('error', models.TextField(blank=True, verbose_name='Error')),
                ('date_delivered', models.DateTimeField(blank=True, null=True, verbose_name='Date delivered')),
                ('date_confirmed', models.DateTimeField(blank=True, null=True, verbose_name='Date confirmed')),
                ('binding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='switch_items', to='accounts.applicationaccountbinding', verbose_name='Application account binding')),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.applicationaccountswitch', verbose_name='Account switch')),
            ],
            options={
                'verbose_name': 'Application account switch item',
                'ordering': ['binding__application__name'],
                'unique_together': {('switch', 'binding')},
            },
        ),
        migrations.CreateModel(
            name='IntegrationApplicationAgentEvent',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('event_type', models.CharField(choices=[('switch', 'Switch account'), ('rollback', 'Rollback account')], max_length=16, verbose_name='Event type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered')], default='pending', max_length=16, verbose_name='Status')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Attempts')),
                ('error', models.TextField(blank=True, verbose_name='Error')),
                ('date_delivered', models.DateTimeField(blank=True, null=True, verbose_name='Date delivered')),
                ('desired_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_agent_events', to='accounts.account', verbose_name='Desired account')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='accounts.applicationaccountswitchitem', verbose_name='Account switch item')),
            ],
            options={
                'verbose_name': 'Integration application Agent event',
                'ordering': ['date_created'],
            },
        ),
    ]
