# Generated by Django 4.1.13 on 2024-10-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_remove_account_date_discovery_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accountrisk",
            options={"verbose_name": "Account risk"},
        ),
        migrations.RenameField(
            model_name="account",
            old_name="date_last_access",
            new_name="date_last_login",
        ),
        migrations.RenameField(
            model_name="account",
            old_name="access_by",
            new_name="login_by",
        ),
        migrations.AddField(
            model_name="gatheredaccount",
            name="action",
            field=models.CharField(
                choices=[("confirmed", "Confirmed"), ("ignored", "Ignored")],
                default="",
                max_length=32,
                verbose_name="Status",
            ),
        ),
    ]
