# Generated by Django 3.2.17 on 2023-03-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_account_usernames_to_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='source_id',
            field=models.CharField(max_length=128, null=True, blank=True, verbose_name='Source ID'),
        ),
    ]
