# Generated by Django 5.2.15 on 2026-09-01 03:41

import common.db.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_merge_0009_account_migrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationapplication',
            name='credential_access_mode',
            field=models.CharField(choices=[('sdk', 'SDK'), ('agent', 'Agent')], default='sdk', max_length=16, verbose_name='Credential access mode'),
        ),
        migrations.CreateModel(
            name='CredentialClientInstance',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('type', models.CharField(choices=[('sdk', 'SDK'), ('agent', 'Agent')], max_length=16, verbose_name='Type')),
                ('instance_id', models.CharField(max_length=128, verbose_name='Instance ID')),
                ('secret', common.db.fields.EncryptTextField(blank=True, default='', verbose_name='Secret')),
                ('date_last_seen', models.DateTimeField(blank=True, null=True, verbose_name='Date last seen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credential_clients', to='accounts.integrationapplication', verbose_name='Integration application')),
            ],
            options={
                'verbose_name': 'Credential client instance',
                'ordering': ['application__name', 'instance_id'],
                'unique_together': {('application', 'instance_id')},
            },
        ),
        migrations.CreateModel(
            name='CredentialPolicy',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('key', models.CharField(default='', max_length=64, unique=True, verbose_name='Key')),
                ('revision', models.PositiveIntegerField(default=1, verbose_name='Revision')),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('waiting_backup', 'Waiting for backup account'), ('ready_for_change', 'Ready for secret change'), ('waiting_primary', 'Waiting for primary account')], default='idle', max_length=32, verbose_name='Status')),
                ('primary_version_at_start', models.IntegerField(blank=True, null=True, verbose_name='Primary version at start')),
                ('rotation_cancelled', models.BooleanField(default=False, verbose_name='Rotation cancelled')),
                ('date_rotation_started', models.DateTimeField(blank=True, null=True, verbose_name='Date rotation started')),
                ('date_last_rotated', models.DateTimeField(blank=True, null=True, verbose_name='Date last rotated')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('backup_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='backup_credential_policies', to='accounts.account', verbose_name='Backup account')),
                ('primary_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_credential_policies', to='accounts.account', verbose_name='Primary account')),
                ('published_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='published_credential_policies', to='accounts.account', verbose_name='Published account')),
            ],
            options={
                'verbose_name': 'Credential policy',
                'ordering': ['name'],
                'unique_together': {('org_id', 'name'), ('org_id', 'primary_account')},
            },
        ),
        migrations.CreateModel(
            name='CredentialApplicationBinding',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credential_bindings', to='accounts.integrationapplication', verbose_name='Integration application')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_bindings', to='accounts.credentialpolicy', verbose_name='Credential policy')),
            ],
            options={
                'verbose_name': 'Credential application binding',
                'ordering': ['application__name'],
                'unique_together': {('policy', 'application')},
            },
        ),
        migrations.CreateModel(
            name='CredentialClientStatus',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('fetched_revision', models.PositiveIntegerField(default=0, verbose_name='Fetched revision')),
                ('applied_revision', models.PositiveIntegerField(default=0, verbose_name='Applied revision')),
                ('required_revision', models.PositiveIntegerField(blank=True, null=True, verbose_name='Required revision')),
                ('is_rotation_participant', models.BooleanField(default=False, verbose_name='Rotation participant')),
                ('date_last_seen', models.DateTimeField(blank=True, null=True, verbose_name='Date last seen')),
                ('date_fetched', models.DateTimeField(blank=True, null=True, verbose_name='Date fetched')),
                ('date_applied', models.DateTimeField(blank=True, null=True, verbose_name='Date applied')),
                ('applied_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.account', verbose_name='Applied account')),
                ('binding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_statuses', to='accounts.credentialapplicationbinding', verbose_name='Application binding')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credential_statuses', to='accounts.credentialclientinstance', verbose_name='Client instance')),
            ],
            options={
                'verbose_name': 'Credential client status',
                'ordering': ['binding__application__name', 'client__instance_id'],
                'unique_together': {('binding', 'client')},
            },
        ),
    ]
