# Generated by Django 3.2.17 on 2023-05-06 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_gatheraccountsautomation_is_sync_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttemplate',
            name='su_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='su_to', to='accounts.accounttemplate', verbose_name='Su from'),
        ),
        migrations.AlterField(
            model_name='changesecretautomation',
            name='ssh_key_change_strategy',
            field=models.CharField(choices=[('add', 'Append SSH KEY'), ('set', 'Empty and append SSH KEY'), ('set_jms', 'Replace (Replace only keys pushed by JumpServer) ')], default='add', max_length=16, verbose_name='SSH key change strategy'),
        ),
        migrations.AlterField(
            model_name='pushaccountautomation',
            name='ssh_key_change_strategy',
            field=models.CharField(choices=[('add', 'Append SSH KEY'), ('set', 'Empty and append SSH KEY'), ('set_jms', 'Replace (Replace only keys pushed by JumpServer) ')], default='add', max_length=16, verbose_name='SSH key change strategy'),
        ),
    ]
