# Generated by Django 4.1.13 on 2024-10-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_accountrisk_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gatheredaccount",
            name="action",
        ),
        migrations.AddField(
            model_name="gatheredaccount",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("confirmed", "Confirmed"), ("ignored", "Ignored")],
                default="",
                max_length=32,
                verbose_name="Action",
            ),
        ),
    ]
