# Generated by Django 4.1.13 on 2024-10-30 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_accountrisk_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gatheredaccount",
            name="authorized_keys",
            field=models.TextField(
                blank=True, default="", verbose_name="Authorized keys"
            ),
        ),
        migrations.AddField(
            model_name="gatheredaccount",
            name="groups",
            field=models.TextField(blank=True, default="", verbose_name="Groups"),
        ),
        migrations.AddField(
            model_name="gatheredaccount",
            name="sudo",
            field=models.TextField(default=False, verbose_name="Sudo"),
        ),
        migrations.CreateModel(
            name="GatheredAccountDiff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diff", models.TextField(default="", verbose_name="Diff")),
                (
                    "item",
                    models.CharField(default="", max_length=32, verbose_name="Item"),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date created"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.gatheredaccount",
                        verbose_name="Gathered account",
                    ),
                ),
            ],
        ),
    ]
