# Generated by Django 3.2.16 on 2023-03-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_gatheraccountsautomation_is_sync_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushaccountautomation',
            name='params',
            field=models.JSONField(default=dict, verbose_name='Params'),
        ),
    ]
