# Generated by Django 4.1.13 on 2024-10-31 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_remove_gatheredaccount_action_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gatheredaccount",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("confirmed", "Confirmed"), ("ignored", "Ignored")],
                default="",
                max_length=32,
                verbose_name="Status",
            ),
        ),
    ]
