# Generated by Django 3.2.19 on 2023-06-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20230506_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='secret',
            new_name='_secret',
        ),
        migrations.RenameField(
            model_name='accounttemplate',
            old_name='secret',
            new_name='_secret',
        ),
        migrations.RenameField(
            model_name='historicalaccount',
            old_name='secret',
            new_name='_secret',
        ),
    ]
