# Generated by Django 3.2.16 on 2023-04-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_account_source_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushaccountautomation',
            name='params',
            field=models.JSONField(default=dict, verbose_name='Params'),
        ),
    ]
