# Generated by Django 3.2.19 on 2023-07-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0012_auto_20230627_2011'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accounttemplateprotocolconfig',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='accounttemplateprotocolconfig',
            name='account_template',
        ),
        migrations.RemoveField(
            model_name='accounttemplateprotocolconfig',
            name='config',
        ),
        migrations.AlterUniqueTogether(
            name='protocolconfig',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='account',
            name='configs',
        ),
        migrations.RemoveField(
            model_name='accounttemplate',
            name='configs',
        ),
        migrations.AddField(
            model_name='accounttemplate',
            name='auto_push',
            field=models.BooleanField(default=False, verbose_name='Auto push'),
        ),
        migrations.AddField(
            model_name='accounttemplate',
            name='push_params',
            field=models.JSONField(default=dict, verbose_name='Push params'),
        ),
        migrations.AddField(
            model_name='accounttemplate',
            name='secret_strategy',
            field=models.CharField(choices=[('specific', 'Specific password'), ('random', 'Random')],
                                   default='specific', max_length=16, verbose_name='Secret strategy'),
        ),
        migrations.DeleteModel(
            name='AccountProtocolConfig',
        ),
        migrations.DeleteModel(
            name='AccountTemplateProtocolConfig',
        ),
        migrations.DeleteModel(
            name='ProtocolConfig',
        ),
    ]
