# Generated by Django 4.1.13 on 2024-10-31 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_gatheredaccount_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gatheredaccount",
            name="sudo",
        ),
        migrations.AddField(
            model_name="gatheredaccount",
            name="sudoers",
            field=models.TextField(default=False, verbose_name="Sudoers"),
        ),
    ]
