# Generated by Django 5.2.15 on 2026-09-04 01:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_application_credential'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationcredential',
            options={'ordering': ['name'], 'verbose_name': 'Application credential'},
        ),
        migrations.AddField(
            model_name='applicationcredential',
            name='applications',
            field=models.ManyToManyField(related_name='application_credentials', through='accounts.CredentialApplicationBinding', to='accounts.integrationapplication', verbose_name='Integration applications'),
        ),
        migrations.AddField(
            model_name='applicationcredential',
            name='change_execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.automationexecution', verbose_name='Change secret execution'),
        ),
        migrations.AddField(
            model_name='applicationcredential',
            name='rotation_mode',
            field=models.CharField(blank=True, choices=[('single', 'Single account'), ('dual', 'Dual accounts')], default='dual', max_length=16, verbose_name='Rotation mode'),
        ),
        migrations.AddField(
            model_name='applicationcredential',
            name='type',
            field=models.CharField(choices=[('fixed', 'Fixed account'), ('rotation', 'Account rotation')], default='rotation', max_length=16, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='applicationcredential',
            name='backup_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='backup_application_credentials', to='accounts.account', verbose_name='Backup account'),
        ),
        migrations.AlterField(
            model_name='applicationcredential',
            name='primary_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_application_credentials', to='accounts.account', verbose_name='Primary account'),
        ),
        migrations.AlterField(
            model_name='applicationcredential',
            name='published_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='published_application_credentials', to='accounts.account', verbose_name='Published account'),
        ),
        migrations.AlterField(
            model_name='applicationcredential',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('waiting_backup', 'Waiting for backup account'), ('ready_for_change', 'Ready for secret change'), ('changing_secret', 'Changing secret'), ('waiting_primary', 'Waiting for primary account')], default='idle', max_length=32, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='credentialapplicationbinding',
            name='credential',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_bindings', to='accounts.applicationcredential', verbose_name='Application credential'),
        ),
        migrations.CreateModel(
            name='ClientAccessConfiguration',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('type', models.CharField(choices=[('sdk', 'SDK'), ('agent', 'Agent')], max_length=16, verbose_name='Type')),
                ('language', models.CharField(choices=[('python', 'Python')], default='python', max_length=16, verbose_name='Language')),
                ('app_user', models.CharField(blank=True, default='', max_length=128, verbose_name='Application user')),
                ('install_path', models.CharField(default='/opt/jumpserver-pam', max_length=256, verbose_name='Install path')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_configurations', to='accounts.integrationapplication', verbose_name='Integration application')),
                ('credentials', models.ManyToManyField(related_name='access_configurations', to='accounts.applicationcredential', verbose_name='Application credentials')),
            ],
            options={
                'verbose_name': 'Client access configuration',
                'ordering': ['name'],
                'unique_together': {('application', 'name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='credentialclientinstance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='credentialclientinstance',
            name='configuration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='accounts.clientaccessconfiguration', verbose_name='Client access configuration'),
        ),
        migrations.AlterUniqueTogether(
            name='credentialclientinstance',
            unique_together={('configuration', 'instance_id')},
        ),
        migrations.CreateModel(
            name='CredentialRotationRecord',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='running', max_length=16, verbose_name='Status')),
                ('date_finished', models.DateTimeField(blank=True, null=True, verbose_name='Date finished')),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotation_records', to='accounts.applicationcredential', verbose_name='Application credential')),
            ],
            options={
                'verbose_name': 'Credential rotation record',
                'ordering': ['-date_created'],
            },
        ),
    ]
