# Generated by Django 3.2.19 on 2023-07-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0119_assets_add_default_node'),
        ('accounts', '0013_auto_20230704_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttemplate',
            name='platforms',
            field=models.ManyToManyField(related_name='account_templates', to='assets.Platform', verbose_name='Platforms'),
        ),
    ]
