# Generated by Django 4.1.13 on 2024-11-18 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_checkaccountautomation_recipients"),
    ]

    operations = [
        migrations.AddField(
            model_name="gatheraccountsautomation",
            name="check_risk",
            field=models.BooleanField(default=True, verbose_name="Check risk"),
        ),
    ]
