# Generated by Django 4.1.10 on 2023-08-25 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0122_auto_20230803_1553'),
        ('accounts', '0014_virtualaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttemplate',
            name='auto_push',
            field=models.BooleanField(default=False, verbose_name='Auto push'),
        ),
        migrations.AddField(
            model_name='accounttemplate',
            name='platforms',
            field=models.ManyToManyField(related_name='account_templates', to='assets.platform', verbose_name='Platforms', blank=True),
        ),
        migrations.AddField(
            model_name='accounttemplate',
            name='push_params',
            field=models.JSONField(default=dict, verbose_name='Push params'),
        ),
        migrations.AddField(
            model_name='accounttemplate',
            name='secret_strategy',
            field=models.CharField(choices=[('specific', 'Specific secret'), ('random', 'Random generate')], default='specific', max_length=16, verbose_name='Secret strategy'),
        ),
    ]
