# Generated by Django 5.2.15 on 2026-09-04 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_bind_existing_client_configurations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integrationapplication',
            name='credential_access_mode',
        ),
    ]
