# Generated by Django 5.2.15 on 2026-09-28 08:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_credential_event_cycles'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='date_last_secret_access',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last application Secret API access'),
        ),
        migrations.AddField(
            model_name='applicationcredential',
            name='standby_no_traffic_days',
            field=models.PositiveIntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3650)], verbose_name='Standby account no-traffic duration (days)'),
        ),
        migrations.AlterField(
            model_name='applicationcredential',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('preparing', 'Aligning accounts'), ('waiting_standby', 'Observing standby account usage'), ('ready_to_switch', 'Ready for account switch'), ('waiting_switch', 'Waiting for account switch'), ('ready_for_change', 'Ready for secret change'), ('changing_secret', 'Changing secret'), ('change_failed', 'Secret change failed'), ('recovery_required', 'Recovery required'), ('waiting_revert', 'Waiting for account revert')], default='idle', max_length=32, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='credentialrotationrecord',
            name='status',
            field=models.CharField(choices=[('preparing', 'Preparing'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='running', max_length=16, verbose_name='Status'),
        ),
    ]
