# Generated by Django 4.1.13 on 2024-11-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_alter_accountrisk_risk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountrisk",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("0", "Pending"), ("1", "Confirmed"), ("2", "Ignored")],
                default="0",
                max_length=32,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="gatheredaccount",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("0", "Pending"), ("1", "Confirmed"), ("2", "Ignored")],
                default="0",
                max_length=32,
                verbose_name="Status",
            ),
        ),
    ]
