# Generated by Django 4.1.10 on 2023-10-24 05:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0016_accounttemplate_password_rules'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automationexecution',
            options={
                'permissions': [
                    ('view_changesecretexecution', 'Can view change secret execution'),
                    ('add_changesecretexecution', 'Can add change secret execution'),
                    ('view_gatheraccountsexecution', 'Can view gather accounts execution'),
                    ('add_gatheraccountsexecution', 'Can add gather accounts execution'),
                    ('view_pushaccountexecution', 'Can view push account execution'),
                    ('add_pushaccountexecution', 'Can add push account execution')
                ],
                'verbose_name': 'Automation execution', 'verbose_name_plural': 'Automation executions'},
        ),
    ]
