# Generated by Django 5.2.15 on 2026-09-28 09:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_credential_rotation_preparation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationCommand',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('event', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('recipients', models.JSONField(default=list)),
                ('expires_at', models.DateTimeField()),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commands', to='accounts.integrationapplication')),
                ('source_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='command', to='accounts.applicationaudit')),
            ],
            options={
                'ordering': ['-date_created', '-id'],
            },
        ),
    ]
