# Generated by Django 4.1.13 on 2024-12-02 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_serviceintegration'),
    ]

    operations = [
        migrations.AddField(
            model_name='changesecretrecord',
            name='ignore_fail',
            field=models.BooleanField(default=False, verbose_name='Ignore fail'),
        ),
        migrations.AlterField(
            model_name='changesecretrecord',
            name='date_finished',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Date finished'),
        ),
    ]
