# Generated by Django 4.1.10 on 2023-11-03 07:10

import common.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0067_alter_replaystorage_type'),
        ('accounts', '0017_alter_automationexecution_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbackupautomation',
            name='backup_type',
            field=models.CharField(choices=[('email', 'Email'), ('object_storage', 'Object Storage')], default='email', max_length=128),
        ),
        migrations.AddField(
            model_name='accountbackupautomation',
            name='is_password_divided_by_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='accountbackupautomation',
            name='is_password_divided_by_obj_storage',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='accountbackupautomation',
            name='obj_recipients_part_one',
            field=models.ManyToManyField(blank=True, related_name='obj_recipient_part_one_plans', to='terminal.replaystorage', verbose_name='Object Storage Recipient part one'),
        ),
        migrations.AddField(
            model_name='accountbackupautomation',
            name='obj_recipients_part_two',
            field=models.ManyToManyField(blank=True, related_name='obj_recipient_part_two_plans', to='terminal.replaystorage', verbose_name='Object Storage Recipient part two'),
        ),
        migrations.AddField(
            model_name='accountbackupautomation',
            name='zip_encrypt_password',
            field=common.db.fields.EncryptCharField(blank=True, max_length=4096, null=True, verbose_name='Zip Encrypt Password'),
        ),
    ]
