# Generated by Django 4.1.13 on 2024-12-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_changesecretrecord_ignore_fail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gatheredaccount',
            name='authorized_keys',
        ),
        migrations.RemoveField(
            model_name='gatheredaccount',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='gatheredaccount',
            name='sudoers',
        ),
        migrations.AddField(
            model_name='gatheredaccount',
            name='detail',
            field=models.JSONField(blank=True, default=dict, verbose_name='Detail'),
        ),
    ]
