# Generated by Django 4.1.13 on 2024-12-04 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_backupaccountautomation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automationexecution',
            options={'permissions': [('view_changesecretexecution', 'Can view change secret execution'), ('add_changesecretexecution', 'Can add change secret execution'), ('view_gatheraccountsexecution', 'Can view gather accounts execution'), ('add_gatheraccountsexecution', 'Can add gather accounts execution'), ('view_pushaccountexecution', 'Can view push account execution'), ('add_pushaccountexecution', 'Can add push account execution'), ('view_backupaccountexecution', 'Can view backup account execution'), ('add_backupaccountexecution', 'Can add backup account execution')], 'verbose_name': 'Automation execution', 'verbose_name_plural': 'Automation executions'},
        ),
    ]
