# Generated by Django 5.2.15 on 2026-09-30 03:07

from django.db import migrations
from django.db.models import Count, F
from django.utils import timezone


def retire_duplicate_instance_ids(apps, schema_editor):
    """Keep historical rows while choosing one live instance per application identity."""
    Client = apps.get_model('accounts', 'CredentialClientInstance')
    Rotation = apps.get_model('accounts', 'CredentialRotationRecord')
    db = schema_editor.connection.alias
    retired_ids = set()
    duplicates = Client.objects.using(db).values(
        'application_id', 'type', 'instance_id',
    ).annotate(count=Count('id')).filter(count__gt=1)
    for identity in duplicates.iterator():
        clients = list(Client.objects.using(db).filter(
            application_id=identity['application_id'], type=identity['type'],
            instance_id=identity['instance_id'],
        ).order_by('-is_active', F('date_last_seen').desc(nulls_last=True), '-date_created', 'id'))
        for client in clients[1:]:
            suffix = f'-retired-{client.id.hex}'
            value = identity['instance_id'][:128 - len(suffix)] + suffix
            Client.objects.using(db).filter(pk=client.pk).update(
                instance_id=value, is_active=False,
            )
            retired_ids.add(str(client.id))
    if not retired_ids:
        return
    excluded_at = timezone.now().isoformat()
    for rotation in Rotation.objects.using(db).filter(
        status__in=('running', 'preparing'), date_finished__isnull=True,
    ).iterator():
        snapshot = rotation.participant_snapshot or {}
        changed = False
        for participant in snapshot.get('participants', []):
            if participant.get('client', {}).get('id') in retired_ids and not participant.get('excluded_at'):
                participant['excluded_at'] = excluded_at
                participant['exclusion_reason'] = 'Duplicate client identity retired during migration.'
                changed = True
        if changed:
            Rotation.objects.using(db).filter(pk=rotation.pk).update(participant_snapshot=snapshot)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_application_pull_scope_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationaudit',
            name='configuration',
        ),
        migrations.RemoveField(
            model_name='applicationaudit',
            name='configuration_id',
        ),
        migrations.RunPython(retire_duplicate_instance_ids, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='credentialclientinstance',
            unique_together={('application', 'type', 'instance_id')},
        ),
        migrations.RemoveField(
            model_name='credentialclientinstance',
            name='configuration',
        ),
        migrations.DeleteModel(
            name='ClientAccessConfiguration',
        ),
    ]
