# Generated by Django 4.1.13 on 2024-12-10 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_changesecretrecord_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changesecretrecord',
            options={'verbose_name': 'Change secret record'},
        ),
    ]
