# Generated by Django 4.1.13 on 2024-12-24 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('assets', '0011_auto_20241204_1516'),
        ('accounts', '0023_alter_changesecretrecord_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changesecretrecord',
            name='date_started',
        ),
        migrations.AlterField(
            model_name='changesecretrecord',
            name='account',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='change_secret_records', to='accounts.account'
            ),
        ),
        migrations.AlterField(
            model_name='changesecretrecord',
            name='asset',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='asset_change_secret_records', to='assets.asset'
            ),
        ),
        migrations.AlterField(
            model_name='changesecretrecord',
            name='execution',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='execution_change_secret_records', to='accounts.automationexecution'
            ),
        ),
    ]
