# Generated by Django 4.1.13 on 2025-01-13 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0025_alter_accountrisk_risk_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountrisk",
            name="account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="risks",
                to="accounts.account",
                verbose_name="Account",
            ),
        ),
    ]
