# Generated by Django 4.1.13 on 2025-01-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_accountrisk_gathered_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkaccountengine',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='checkaccountautomation',
            name='engines',
        ),
        migrations.AddField(
            model_name='checkaccountautomation',
            name='engines',
            field=models.JSONField(default=list, verbose_name='Engines'),
        ),
    ]
