# Generated by Django 2.0.7 on 2018-08-07 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftplog',
            name='org_id',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=36, null=True),
        ),
    ]
