# Generated by Django 4.1.13 on 2024-05-09 03:16

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ops', '0001_initial'),
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobLog',
            fields=[
            ],
            options={
                'verbose_name': 'Job audit log',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ops.jobexecution',),
        ),
    ]
