# Generated by Django 4.1.13 on 2024-09-06 08:40

import common.db.fields
from django.db import migrations, models
import uuid


def init_log_storage(apps, schema_editor):
    model = apps.get_model("audits", "LogStorage")
    model.objects.update_or_create(
        name="default", type="server", is_default=True,
        defaults={
            "name": "default",
            "type": "server",
            "comment": "Store locally",
            "meta": "{}",
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0003_auto_20180816_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogStorage',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
                ('meta', common.db.fields.EncryptJsonDictTextField(default={})),
                ('is_default', models.BooleanField(default=False, verbose_name='Default')),
                ('type', models.CharField(choices=[('server', 'Server'), ('es', 'Elasticsearch')], default='server', max_length=16, verbose_name='Type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(init_log_storage),
    ]
