# Generated by Django 4.1.13 on 2024-12-04 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0004_serviceaccesslog"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ServiceAccessLog",
            new_name="IntegrationApplicationLog",
        ),
    ]
