# Generated by Django 2.2.7 on 2019-12-02 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0006_auto_20190726_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ftplog',
            name='remote_addr',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Remote addr'),
        ),
        migrations.AlterField(
            model_name='operatelog',
            name='remote_addr',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Remote addr'),
        ),
        migrations.AlterField(
            model_name='passwordchangelog',
            name='remote_addr',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Remote addr'),
        ),
    ]
