# Generated by Django 4.1.13 on 2026-02-26 02:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0007_auto_20250610_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='FTPLogHmac',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('record_id', models.UUIDField(db_index=True, verbose_name='Record ID')),
                ('encrypt_fields', models.CharField(default='', max_length=1024, verbose_name='Encrypt fields')),
                ('encrypt_value', models.CharField(default='', max_length=1024, verbose_name='Encrypt value')),
            ],
            options={
                'verbose_name': 'FTP log HMAC',
                'db_table': 'audits_ftp_log_hmac',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OperateLogHmac',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('record_id', models.UUIDField(db_index=True, verbose_name='Record ID')),
                ('encrypt_fields', models.CharField(default='', max_length=1024, verbose_name='Encrypt fields')),
                ('encrypt_value', models.CharField(default='', max_length=1024, verbose_name='Encrypt value')),
            ],
            options={
                'verbose_name': 'Operate log HMAC',
                'db_table': 'audits_operate_log_hmac',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PasswordChangeLogHmac',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('record_id', models.UUIDField(db_index=True, verbose_name='Record ID')),
                ('encrypt_fields', models.CharField(default='', max_length=1024, verbose_name='Encrypt fields')),
                ('encrypt_value', models.CharField(default='', max_length=1024, verbose_name='Encrypt value')),
            ],
            options={
                'verbose_name': 'Password change log HMAC',
                'db_table': 'audits_password_change_log_hmac',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserLoginLogHmac',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('record_id', models.UUIDField(db_index=True, verbose_name='Record ID')),
                ('encrypt_fields', models.CharField(default='', max_length=1024, verbose_name='Encrypt fields')),
                ('encrypt_value', models.CharField(default='', max_length=1024, verbose_name='Encrypt value')),
            ],
            options={
                'verbose_name': 'User login log HMAC',
                'db_table': 'audits_user_login_log_hmac',
                'abstract': False,
            },
        ),
    ]
