# Generated by Django 5.2.13 on 2026-08-07 08:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0007_auto_20250610_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageReclamationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=36, verbose_name='Session ID')),
                ('target_type', models.CharField(default='session_replay', max_length=32, verbose_name='Target type')),
                ('file_path', models.CharField(max_length=1024, verbose_name='File path')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='File size (bytes)')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
            ],
            options={
                'verbose_name': 'Storage reclamation log',
                'ordering': ['-date_created'],
            },
        ),
    ]
