# Generated by Django 2.2.10 on 2020-05-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0007_auto_20191202_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ftplog',
            name='date_start',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date start'),
        ),
        migrations.AlterField(
            model_name='operatelog',
            name='datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Datetime'),
        ),
        migrations.AlterField(
            model_name='passwordchangelog',
            name='datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Datetime'),
        ),
    ]
