# Generated by Django 5.2.13 on 2026-07-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0007_auto_20250610_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloginlog',
            name='reason_code',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Reason code'),
        ),
        migrations.AddField(
            model_name='userloginlog',
            name='reason_params',
            field=models.JSONField(blank=True, default=dict, verbose_name='Reason params'),
        ),
    ]
