# Generated by Django 2.2.10 on 2020-06-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0008_auto_20200508_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ftplog',
            name='operate',
            field=models.CharField(choices=[('Delete', 'Delete'), ('Upload', 'Upload'), ('Download', 'Download'), ('Rmdir', 'Rmdir'), ('Rename', 'Rename'), ('Mkdir', 'Mkdir'), ('Symlink', 'Symlink')], max_length=16, verbose_name='Operate'),
        ),
    ]
