# Generated by Django 5.2.13 on 2026-08-07 08:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0008_storagereclamationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=36, verbose_name='Session ID')),
                ('file_path', models.CharField(max_length=1024, verbose_name='File path')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='File size (bytes)')),
                ('storage_path', models.CharField(default='', max_length=1024, verbose_name='Storage path')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
            ],
            options={
                'verbose_name': 'Archive log',
                'ordering': ['-date_created'],
            },
        ),
    ]
