# Generated by Django 5.2.13 on 2026-07-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0008_userloginlog_reason_code_userloginlog_reason_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordchangelog',
            name='datetime',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Datetime'),
        ),
    ]
