# Generated by Django 5.2.13 on 2026-08-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0009_archivelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storagereclamationlog',
            name='session_id',
        ),
        migrations.RemoveField(
            model_name='storagereclamationlog',
            name='target_type',
        ),
        migrations.RemoveField(
            model_name='storagereclamationlog',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='storagereclamationlog',
            name='file_size',
        ),
        migrations.AddField(
            model_name='storagereclamationlog',
            name='method',
            field=models.CharField(
                choices=[('delete', 'Delete'), ('archive', 'Archive')],
                default='delete', max_length=16, verbose_name='Reclamation method'
            ),
        ),
        migrations.AddField(
            model_name='storagereclamationlog',
            name='data_start',
            field=models.DateTimeField(null=True, verbose_name='Data start'),
        ),
        migrations.AddField(
            model_name='storagereclamationlog',
            name='data_end',
            field=models.DateTimeField(null=True, verbose_name='Data end'),
        ),
        migrations.AddField(
            model_name='storagereclamationlog',
            name='result',
            field=models.CharField(
                choices=[('success', 'Success'), ('fail', 'Fail')],
                default='success', max_length=16, verbose_name='Result'
            ),
        ),
        migrations.DeleteModel(
            name='ArchiveLog',
        ),
    ]
