# Generated by Django 2.2.13 on 2020-10-26 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0010_auto_20200811_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userloginlog',
            name='type',
            field=models.CharField(choices=[('W', 'Web'), ('T', 'Terminal'), ('S', 'SSO')], max_length=2, verbose_name='Login type'),
        ),
    ]
