# Generated by Django 5.2.13 on 2026-08-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0010_archive_into_reclamation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagereclamationlog',
            name='method',
            field=models.CharField(choices=[('delete_day', 'Delete the earliest day of audit'), ('archive_day', 'Archive the earliest day of audit'), ('delete_month', 'Delete the earliest month of audit'), ('archive_month', 'Archive the earliest month of audit'), ('delete', 'Delete'), ('archive', 'Archive')], default='delete_day', max_length=16, verbose_name='Reclamation method'),
        ),
    ]
