# Generated by Django 3.1 on 2020-12-09 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0010_auto_20200811_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloginlog',
            name='backend',
            field=models.CharField(default='', max_length=32, verbose_name='Authentication backend'),
        ),
    ]
