# Generated by Django 3.1.6 on 2021-04-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0011_userloginlog_backend'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftplog',
            name='has_file_record',
            field=models.BooleanField(default=False, verbose_name='File Recorded'),
        ),
    ]
