# Generated by Django 3.1 on 2021-04-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0011_userloginlog_backend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userloginlog',
            name='type',
            field=models.CharField(choices=[('W', 'Web'), ('T', 'Terminal'), ('U', 'Unknown')], max_length=2, verbose_name='Login type'),
        ),
    ]
