# Generated by Django 3.1.13 on 2021-11-30 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0012_auto_20210414_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ftplog',
            options={'verbose_name': 'File transfer log'},
        ),
        migrations.AlterModelOptions(
            name='operatelog',
            options={'verbose_name': 'Operate log'},
        ),
        migrations.AlterModelOptions(
            name='passwordchangelog',
            options={'verbose_name': 'Password change log'},
        ),
        migrations.AlterModelOptions(
            name='userloginlog',
            options={'ordering': ['-datetime', 'username'], 'verbose_name': 'User login log'},
        ),
    ]
