# Generated by Django 3.2.14 on 2022-10-11 09:45

import common.db.encoder
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0014_auto_20220505_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatelog',
            name='after',
            field=models.JSONField(default=dict, encoder=common.db.encoder.ModelJSONFieldEncoder, null=True),
        ),
        migrations.AddField(
            model_name='operatelog',
            name='before',
            field=models.JSONField(default=dict, encoder=common.db.encoder.ModelJSONFieldEncoder, null=True),
        ),
    ]
