# Generated by Django 3.1.14 on 2022-05-23 02:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0014_auto_20220505_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('email', 'Email')], default='email', max_length=16, verbose_name='Type')),
                ('event', models.TextField(blank=True, null=True, verbose_name='Event')),
                ('result', models.TextField(blank=True, null=True, verbose_name='Result')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='Datetime')),
                ('is_success', models.BooleanField(default=True, verbose_name='Success')),
            ],
            options={
                'verbose_name': 'Task log',
                'ordering': ['-datetime'],
            },
        ),
    ]
