# Generated by Django 3.2.14 on 2022-11-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('audits', '0015_auto_20221011_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ftplog',
            name='operate',
            field=models.CharField(
                choices=[('mkdir', 'Mkdir'), ('rmdir', 'Rmdir'), ('delete', 'Delete'), ('upload', 'Upload'),
                         ('rename', 'Rename'), ('symlink', 'Symlink'), ('download', 'Download')], max_length=16,
                verbose_name='Operate'),
        ),
        migrations.AlterField(
            model_name='operatelog',
            name='action',
            field=models.CharField(choices=[
                ('view', 'View'), ('update', 'Update'), ('delete', 'Delete'),
                ('create', 'Create'), ('connect', 'Connect'), ('login', 'Login'),
                ('change_password', 'Change password')
            ], max_length=16, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='userloginlog',
            name='status',
            field=models.BooleanField(choices=[(1, 'Success'), (0, 'Failed')], default=1, verbose_name='Status'),
        ),
    ]
