# Generated by Django 3.2.14 on 2022-12-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('audits', '0016_auto_20221111_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ftplog',
            old_name='system_user',
            new_name='account',
        ),
        migrations.AlterField(
            model_name='ftplog',
            name='account',
            field=models.CharField(default='', max_length=128, verbose_name='Account'),
            preserve_default=False,
        ),
    ]
