# Generated by Django 3.2.14 on 2023-01-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0017_auto_20221220_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatelog',
            name='resource_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Resource'),
        ),
        migrations.AlterModelOptions(
            name='operatelog',
            options={'ordering': ('-datetime',), 'verbose_name': 'Operate log'},
        ),
    ]
