# Generated by Django 3.2.16 on 2023-01-10 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0018_operatelog_resource_id'),
    ]

    operations = [
    ]
