# Generated by Django 3.2.14 on 2023-01-12 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0019_alter_operatelog_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatelog',
            name='is_activity',
            field=models.BooleanField(default=False, verbose_name='Is Activity'),
        ),
    ]
