# Generated by Django 3.2.16 on 2023-02-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0020_auto_20230117_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatelog',
            name='resource_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='Resource'),
        ),
    ]
