# Generated by Django 3.2.17 on 2023-05-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0021_auto_20230207_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftplog',
            name='has_file',
            field=models.BooleanField(default=False, verbose_name='File Record'),
        ),
    ]
