# Generated by Django 3.2.17 on 2023-06-05 07:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0021_auto_20230207_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftplog',
            name='has_file',
            field=models.BooleanField(default=False, verbose_name='File'),
        ),
        migrations.AddField(
            model_name='ftplog',
            name='session',
            field=models.CharField(default=uuid.uuid4, max_length=36, verbose_name='Session'),
        ),
        migrations.AlterField(
            model_name='ftplog',
            name='operate',
            field=models.CharField(choices=[('mkdir', 'Mkdir'), ('rmdir', 'Rmdir'), ('delete', 'Delete'), ('upload', 'Upload'), ('rename', 'Rename'), ('symlink', 'Symlink'), ('download', 'Download'), ('rename_dir', 'Rename dir')], max_length=16, verbose_name='Operate'),
        ),
    ]
