# Generated by Django 4.1.10 on 2023-10-18 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0024_usersession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='date_expired',
        ),
    ]
