# Generated by Django 5.2.13 on 2026-07-16 10:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def configure_mysql_utf8mb4(apps, schema_editor):
    if schema_editor.connection.vendor != 'mysql':
        return

    statements = (
        'ALTER TABLE chat_ai_conversation MODIFY COLUMN title '
        'VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL',
        'ALTER TABLE chat_ai_message MODIFY COLUMN content '
        'LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL',
        'ALTER TABLE chat_ai_message_file '
        'MODIFY COLUMN name VARCHAR(255) CHARACTER SET utf8mb4 '
        'COLLATE utf8mb4_bin NOT NULL, '
        'MODIFY COLUMN extracted_text LONGTEXT CHARACTER SET utf8mb4 '
        'COLLATE utf8mb4_bin NOT NULL',
    )
    for statement in statements:
        schema_editor.execute(statement)


class Migration(migrations.Migration):

    initial = True
    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('org_id', models.CharField(db_index=True, max_length=36, verbose_name='Organization')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('awaiting_approval', 'Awaiting approval'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=32, verbose_name='Status')),
                ('task_id', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Celery task ID')),
                ('step_count', models.PositiveIntegerField(default=0, verbose_name='Step count')),
                ('api_call_count', models.PositiveIntegerField(default=0, verbose_name='API call count')),
                ('search_summary', models.JSONField(blank=True, default=list, verbose_name='API search summary')),
                ('input_tokens', models.PositiveIntegerField(default=0, verbose_name='Input tokens')),
                ('output_tokens', models.PositiveIntegerField(default=0, verbose_name='Output tokens')),
                ('model_duration_ms', models.PositiveIntegerField(default=0, verbose_name='Model duration')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started at')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finished at')),
                ('error', models.CharField(blank=True, default='', max_length=1024, verbose_name='Error')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_ai_agent_runs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Chat AI agent run',
                'db_table': 'chat_ai_agent_run',
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('title', models.CharField(blank=True, default='', max_length=256, verbose_name='Title')),
                ('model', models.CharField(blank=True, default='', max_length=128, verbose_name='Model')),
                ('assistant', models.CharField(blank=True, default='general', max_length=32, verbose_name='Assistant')),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=16, verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_ai_conversations', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Chat AI conversation',
                'db_table': 'chat_ai_conversation',
                'ordering': ('-date_updated',),
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('org_id', models.CharField(db_index=True, max_length=36, verbose_name='Organization')),
                ('operation_id', models.CharField(max_length=256, verbose_name='Operation ID')),
                ('method', models.CharField(max_length=8, verbose_name='Method')),
                ('path', models.CharField(max_length=1024, verbose_name='Path')),
                ('request_payload', models.JSONField(default=dict, verbose_name='Request payload')),
                ('request_hash', models.CharField(max_length=64, verbose_name='Request hash')),
                ('nonce', models.CharField(max_length=64, unique=True, verbose_name='Nonce')),
                ('signing_key_id', models.CharField(default='v1', max_length=64, verbose_name='Signing key ID')),
                ('signature', models.CharField(max_length=64, verbose_name='Signature')),
                ('risk_level', models.CharField(default='write', max_length=32, verbose_name='Risk level')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('failed', 'Failed')], default='pending', max_length=32, verbose_name='Status')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmed at')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='Expires at')),
                ('result_summary', models.JSONField(blank=True, default=dict, verbose_name='Result summary')),
                ('error', models.CharField(blank=True, default='', max_length=1024, verbose_name='Error')),
                ('agent_run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to='chat_ai.agentrun', verbose_name='Agent run')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_chat_ai_approvals', to=settings.AUTH_USER_MODEL, verbose_name='Confirmed by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_ai_approvals', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('conversation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to='chat_ai.conversation', verbose_name='Conversation')),
            ],
            options={
                'verbose_name': 'Chat AI approval',
                'db_table': 'chat_ai_approval',
                'ordering': ('-date_created',),
            },
        ),
        migrations.AddField(
            model_name='agentrun',
            name='conversation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_runs', to='chat_ai.conversation', verbose_name='Conversation'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('system', 'System'), ('user', 'User'), ('assistant', 'Assistant'), ('tool', 'Tool')], max_length=16, verbose_name='Role')),
                ('content', models.TextField(blank=True, default='', verbose_name='Content')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('streaming', 'Streaming'), ('awaiting_approval', 'Awaiting approval'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=32, verbose_name='Status')),
                ('model', models.CharField(blank=True, default='', max_length=128, verbose_name='Model')),
                ('input_tokens', models.PositiveIntegerField(default=0, verbose_name='Input tokens')),
                ('output_tokens', models.PositiveIntegerField(default=0, verbose_name='Output tokens')),
                ('error', models.CharField(blank=True, default='', max_length=1024, verbose_name='Error')),
                ('result_cards', models.JSONField(blank=True, default=list, verbose_name='Result cards')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat_ai.conversation', verbose_name='Conversation')),
                ('regenerated_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regenerations', to='chat_ai.message', verbose_name='Regenerated from')),
            ],
            options={
                'verbose_name': 'Chat AI message',
                'db_table': 'chat_ai_message',
                'ordering': ('date_created',),
            },
        ),
        migrations.CreateModel(
            name='ApiCallAudit',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('org_id', models.CharField(db_index=True, max_length=36, verbose_name='Organization')),
                ('operation_id', models.CharField(db_index=True, max_length=256, verbose_name='Operation ID')),
                ('method', models.CharField(max_length=8, verbose_name='Method')),
                ('path', models.CharField(max_length=1024, verbose_name='Path')),
                ('request_summary', models.JSONField(blank=True, default=dict, verbose_name='Request summary')),
                ('response_summary', models.JSONField(blank=True, default=dict, verbose_name='Response summary')),
                ('status_code', models.PositiveIntegerField(default=0, verbose_name='Status code')),
                ('risk_level', models.CharField(default='read', max_length=32, verbose_name='Risk level')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='Duration')),
                ('error', models.CharField(blank=True, default='', max_length=1024, verbose_name='Error')),
                ('agent_run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_call_audits', to='chat_ai.agentrun', verbose_name='Agent run')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_ai_api_call_audits', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('approval', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_call_audits', to='chat_ai.approval', verbose_name='Approval')),
                ('conversation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_call_audits', to='chat_ai.conversation', verbose_name='Conversation')),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_call_audits', to='chat_ai.message', verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Chat AI API call audit',
                'db_table': 'chat_ai_api_call_audit',
                'ordering': ('-date_created',),
            },
        ),
        migrations.AddField(
            model_name='agentrun',
            name='assistant_message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_run', to='chat_ai.message', verbose_name='Assistant message'),
        ),
        migrations.CreateModel(
            name='MessageFile',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=512, upload_to='chat_ai/files/%Y/%m/%d/', verbose_name='File')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('content_type', models.CharField(max_length=128, verbose_name='Content type')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='Size')),
                ('extracted_text', models.TextField(blank=True, default='', verbose_name='Extracted text')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='chat_ai.message', verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Chat AI message file',
                'db_table': 'chat_ai_message_file',
                'ordering': ('date_created',),
            },
        ),
        migrations.CreateModel(
            name='MessageImage',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=512, upload_to='chat_ai/images/%Y/%m/%d/', verbose_name='File')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('content_type', models.CharField(max_length=64, verbose_name='Content type')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='Size')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='chat_ai.message', verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Chat AI message image',
                'db_table': 'chat_ai_message_image',
                'ordering': ('date_created',),
            },
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('interval', models.IntegerField(blank=True, default=24, null=True, verbose_name='Interval')),
                ('crontab', models.CharField(blank=True, default='', max_length=128, verbose_name='Crontab')),
                ('start_time', models.DateTimeField(blank=True, help_text='Datetime when the schedule should begin triggering the task to run', null=True, verbose_name='Start Datetime')),
                ('date_last_run', models.DateTimeField(blank=True, null=True, verbose_name='Date last run')),
                ('is_periodic', models.BooleanField(default=True, verbose_name='Periodic run')),
                ('prompt', models.TextField(verbose_name='Prompt')),
                ('assistant', models.CharField(default='ops', max_length=32, verbose_name='Assistant')),
                ('web_search', models.BooleanField(default=False, verbose_name='Web search')),
                ('notify', models.BooleanField(default=True, verbose_name='Notify')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('last_status', models.CharField(blank=True, default='', max_length=32, verbose_name='Last status')),
                ('last_error', models.CharField(blank=True, default='', max_length=1024, verbose_name='Last error')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_ai_scheduled_reports', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Chat AI scheduled report',
                'db_table': 'chat_ai_scheduled_report',
                'ordering': ('-date_updated',),
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='scheduled_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='chat_ai.scheduledreport', verbose_name='Scheduled report'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['user', 'org_id', 'status'], name='chat_ai_app_user_id_dc16f3_idx'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['date_updated'], name='chat_ai_appr_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'date_created'], name='chat_ai_mes_convers_6dd876_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['date_created'], name='chat_ai_msg_created_idx'),
        ),
        migrations.AddIndex(
            model_name='apicallaudit',
            index=models.Index(fields=['operation_id', '-date_created'], name='chat_ai_api_operati_302572_idx'),
        ),
        migrations.AddIndex(
            model_name='apicallaudit',
            index=models.Index(fields=['user', 'org_id', '-date_created'], name='chat_ai_api_user_id_569a32_idx'),
        ),
        migrations.AddIndex(
            model_name='apicallaudit',
            index=models.Index(fields=['date_created'], name='chat_ai_audit_created_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['user', 'org_id', '-started_at'], name='chat_ai_age_user_id_a3cd71_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['user', 'status', 'date_created'], name='chat_ai_age_user_id_queued_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['date_updated'], name='chat_ai_run_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='messagefile',
            index=models.Index(fields=['date_created'], name='chat_ai_file_created_idx'),
        ),
        migrations.AddIndex(
            model_name='messageimage',
            index=models.Index(fields=['date_created'], name='chat_ai_img_created_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledreport',
            index=models.Index(fields=['user', 'org_id', 'is_active'], name='chat_ai_sch_user_id_d1fb55_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scheduledreport',
            unique_together={('user', 'org_id', 'name')},
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', 'org_id', '-date_updated'], name='chat_ai_con_user_id_e18f36_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['date_updated'], name='chat_ai_con_updated_idx'),
        ),
        migrations.RunPython(
            configure_mysql_utf8mb4,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
