# Generated by Django 3.1 on 2021-03-02 02:33

from django.conf import settings
from django.db import migrations, models
import ipaddress
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetACLPolicy',
            fields=[
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
                ('policy_type', models.CharField(choices=[('policy_asset', 'policy_asset')], default='policy_asset', max_length=32, verbose_name='Policy Type')),
                ('action', models.CharField(choices=[('deny', 'Deny'), ('confirm', 'Confirm')], default='confirm', max_length=32, verbose_name='Action')),
                ('created_by', models.CharField(blank=True, max_length=128, verbose_name='Created by')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('user', models.CharField(max_length=128, verbose_name='User')),
                ('ip', models.CharField(max_length=128, validators=[ipaddress.ip_network], verbose_name='IP')),
                ('ip_start', models.GenericIPAddressField(verbose_name='IP Start')),
                ('ip_end', models.GenericIPAddressField(verbose_name='IP End')),
                ('port', models.IntegerField(default=22, verbose_name='Port')),
                ('system_user', models.CharField(max_length=128, verbose_name='System User')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('reviewers', models.ManyToManyField(related_name='assetaclpolicys', to=settings.AUTH_USER_MODEL, verbose_name='Reviewers')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
