# Generated by Django 3.1 on 2021-03-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginacl',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='loginassetacl',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
