# Generated by Django 3.1 on 2021-03-09 08:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acls', '0002_auto_20210308_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginacl',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='loginacl',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='loginacl',
            name='users',
            field=models.ManyToManyField(related_name='login_acls', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='loginassetacl',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='loginassetacl',
            name='reviewers',
            field=models.ManyToManyField(blank=True, related_name='review_login_asset_acls', to=settings.AUTH_USER_MODEL, verbose_name='Reviewers'),
        ),
        migrations.AlterUniqueTogether(
            name='loginassetacl',
            unique_together={('name', 'org_id')},
        ),
    ]
