# Generated by Django 3.1.13 on 2021-11-30 02:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('acls', '0002_auto_20210926_1047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginacl',
            options={'ordering': ('priority', '-is_active', 'name'), 'verbose_name': 'Login acl'},
        ),
        migrations.AlterModelOptions(
            name='loginassetacl',
            options={'ordering': ('priority', '-is_active', 'name'), 'verbose_name': 'Login asset acl'},
        ),
    ]
