# Generated by Django 5.2.13 on 2026-07-07 04:15

import common.db.fields
import django.core.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acls', '0003_datamaskingrule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClipboardACL',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('priority', models.IntegerField(default=50, help_text='1-100, the lower the value will be match first', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Priority')),
                ('action', models.CharField(default='reject', max_length=64, verbose_name='Action')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('users', common.db.fields.JSONManyToManyField(default=dict, to='users.User', verbose_name='Users')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('assets', common.db.fields.JSONManyToManyField(default=dict, to='assets.Asset', verbose_name='Assets')),
                ('accounts', models.JSONField(default=list, verbose_name='Accounts')),
                ('operations', models.IntegerField(default=24, verbose_name='Operations')),
                ('copy_text_limit', models.BigIntegerField(default=0, help_text='0 means unlimited, unit: characters', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Copy text character limit')),
                ('paste_text_limit', models.BigIntegerField(default=0, help_text='0 means unlimited, unit: characters', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Paste text character limit')),
                ('download_file_size_limit', models.BigIntegerField(default=0, help_text='0 means unlimited, unit: MB', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Download file size limit')),
                ('upload_file_size_limit', models.BigIntegerField(default=0, help_text='0 means unlimited, unit: MB', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Upload file size limit')),
                ('reviewers', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Reviewers')),
            ],
            options={
                'verbose_name': 'Clipboard acl',
                'ordering': ('priority', '-is_active', 'name'),
                'abstract': False,
                'unique_together': {('name', 'org_id')},
            },
        ),
    ]
