# Generated by Django 3.2.14 on 2022-12-02 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acls', '0004_connectacl'),
        ('acls', '0007_auto_20221202_1048'),
    ]

    operations = [
    ]
