# Generated by Django 3.2.14 on 2022-12-02 04:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('acls', '0007_auto_20221202_1048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commandgroup',
            options={'verbose_name': 'Command group'},
        ),
        migrations.RenameField(
            model_name='commandfilteracl',
            old_name='commands',
            new_name='command_groups',
        ),
        migrations.AlterModelOptions(
            name='commandfilteracl',
            options={'ordering': ('priority', '-is_active', 'name'), 'verbose_name': 'Command acl'},
        ),
        migrations.AlterModelOptions(
            name='loginacl',
            options={'ordering': ('priority', '-is_active', 'name'), 'verbose_name': 'Login acl'},
        ),
        migrations.AlterModelOptions(
            name='loginassetacl',
            options={'ordering': ('priority', '-is_active', 'name'), 'verbose_name': 'Login asset acl'},
        ),
    ]
