# Generated by Django 3.2.14 on 2022-12-03 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acls', '0008_commandgroup_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commandgroup',
            options={'verbose_name': 'Command group'},
        ),
        migrations.RenameField(
            model_name='commandfilteracl',
            old_name='commands',
            new_name='command_groups',
        ),
    ]
