# Generated by Django 3.2.14 on 2022-12-05 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acls', '0009_auto_20221204_0001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commandfilteracl',
            options={'ordering': ('priority', 'name'), 'verbose_name': 'Command acl'},
        ),
        migrations.AlterModelOptions(
            name='loginacl',
            options={'ordering': ('priority', 'name'), 'verbose_name': 'Login acl'},
        ),
        migrations.AlterModelOptions(
            name='loginassetacl',
            options={'ordering': ('priority', 'name'), 'verbose_name': 'Login asset acl'},
        ),
    ]
