# Generated by Django 3.2.16 on 2023-01-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acls', '0009_auto_20221220_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandfilteracl',
            name='command_groups',
            field=models.ManyToManyField(to='acls.CommandGroup', verbose_name='Command group'),
        ),
    ]
