# Generated by Django 3.2.17 on 2023-04-25 09:04

from django.db import migrations, models

import common.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ('acls', '0010_alter_commandfilteracl_command_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandfilteracl',
            name='new_accounts',
            field=models.JSONField(default=list, verbose_name='Accounts'),
        ),
        migrations.AddField(
            model_name='commandfilteracl',
            name='new_assets',
            field=common.db.fields.JSONManyToManyField(default=dict, to='assets.Asset', verbose_name='Assets'),
        ),
        migrations.AddField(
            model_name='commandfilteracl',
            name='new_users',
            field=common.db.fields.JSONManyToManyField(default=dict, to='users.User', verbose_name='Users'),
        ),
        migrations.AddField(
            model_name='loginassetacl',
            name='new_accounts',
            field=models.JSONField(default=list, verbose_name='Accounts')
        ),
        migrations.AddField(
            model_name='loginassetacl',
            name='new_assets',
            field=common.db.fields.JSONManyToManyField(default=dict, to='assets.Asset', verbose_name='Assets'),
        ),
        migrations.AddField(
            model_name='loginassetacl',
            name='new_users',
            field=common.db.fields.JSONManyToManyField(default=dict, to='users.User', verbose_name='Users'),
        ),
    ]
