# Generated by Django 3.2.17 on 2023-04-26 09:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('acls', '0012_auto_20230426_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandfilteracl',
            name='accounts',
        ),
        migrations.RemoveField(
            model_name='commandfilteracl',
            name='assets',
        ),
        migrations.RemoveField(
            model_name='commandfilteracl',
            name='users',
        ),
        migrations.RemoveField(
            model_name='loginassetacl',
            name='accounts',
        ),
        migrations.RemoveField(
            model_name='loginassetacl',
            name='assets',
        ),
        migrations.RemoveField(
            model_name='loginassetacl',
            name='users',
        ),
        migrations.RenameField(
            model_name='commandfilteracl',
            old_name='new_accounts',
            new_name='accounts',
        ),
        migrations.RenameField(
            model_name='commandfilteracl',
            old_name='new_assets',
            new_name='assets',
        ),
        migrations.RenameField(
            model_name='commandfilteracl',
            old_name='new_users',
            new_name='users',
        ),
        migrations.RenameField(
            model_name='loginassetacl',
            old_name='new_accounts',
            new_name='accounts',
        ),
        migrations.RenameField(
            model_name='loginassetacl',
            old_name='new_assets',
            new_name='assets',
        ),
        migrations.RenameField(
            model_name='loginassetacl',
            old_name='new_users',
            new_name='users',
        ),
    ]
