# Generated by Django 3.2.17 on 2023-05-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acls', '0013_auto_20230426_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginassetacl',
            name='rules',
            field=models.JSONField(default=dict, verbose_name='Rule'),
        ),
    ]
