# Generated by Django 3.1 on 2020-11-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.CharField(max_length=128)),
                ('ip', models.GenericIPAddressField()),
                ('component', models.CharField(choices=[('core', 'Core'), ('koko', 'KoKo'), ('guacamole', 'Guacamole'), ('omnidb', 'OmniDB')], max_length=16)),
                ('key', models.CharField(db_index=True, max_length=64, verbose_name='Item key')),
                ('value', models.FloatField()),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
