- hosts: windows
  gather_facts: no
  vars:
    ansible_timeout: 30
  tasks:
    - name: Refresh connection
      ansible.builtin.meta: reset_connection

    - name: Windows ping
      ansible.builtin.win_ping:
