# Generated by Django 2.1.7 on 2019-02-28 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('terminal', '0002_auto_20171228_0025'), ('terminal', '0003_auto_20171230_0308'), ('terminal', '0004_session_remote_addr'), ('terminal', '0005_auto_20180122_1154'), ('terminal', '0006_auto_20180123_1037'), ('terminal', '0007_session_date_last_active'), ('terminal', '0008_auto_20180307_1603'), ('terminal', '0009_auto_20180326_0957')]

    dependencies = [
        ('terminal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='terminal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='terminal.Terminal'),
        ),
        migrations.AddField(
            model_name='status',
            name='terminal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='terminal.Terminal'),
        ),
        migrations.AddField(
            model_name='task',
            name='terminal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='terminal.Terminal'),
        ),
        migrations.AddField(
            model_name='terminal',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terminal', to=settings.AUTH_USER_MODEL, verbose_name='Application User'),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='command',
            name='asset',
            field=models.CharField(db_index=True, max_length=128, verbose_name='Asset'),
        ),
        migrations.AlterField(
            model_name='command',
            name='system_user',
            field=models.CharField(db_index=True, max_length=64, verbose_name='System user'),
        ),
        migrations.AlterField(
            model_name='command',
            name='user',
            field=models.CharField(db_index=True, max_length=64, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='session',
            name='remote_addr',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Remote addr'),
        ),
        migrations.AddField(
            model_name='terminal',
            name='command_storage',
            field=models.CharField(default='default', max_length=128, verbose_name='Command storage'),
        ),
        migrations.AddField(
            model_name='terminal',
            name='replay_storage',
            field=models.CharField(default='default', max_length=128, verbose_name='Replay storage'),
        ),
        migrations.AddField(
            model_name='session',
            name='date_last_active',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date last active'),
        ),
        migrations.AlterField(
            model_name='session',
            name='date_start',
            field=models.DateTimeField(db_index=True, verbose_name='Date start'),
        ),
    ]
