# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-29 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0002_auto_20171228_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='asset',
            field=models.CharField(db_index=True, max_length=128, verbose_name='Asset'),
        ),
        migrations.AlterField(
            model_name='command',
            name='system_user',
            field=models.CharField(db_index=True, max_length=64, verbose_name='System user'),
        ),
        migrations.AlterField(
            model_name='command',
            name='user',
            field=models.CharField(db_index=True, max_length=64, verbose_name='User'),
        ),
    ]
