# Generated by Django 4.1.13 on 2025-04-01 07:44

import common.db.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0005_endpoint_vnc_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='oracle_port',
            field=common.db.fields.PortField(default=15210, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)], verbose_name='Oracle port'),
        ),
    ]
