# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0005_auto_20180122_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminal',
            name='command_storage',
            field=models.CharField(default='default', max_length=128, verbose_name='Command storage'),
        ),
    ]
