# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0006_auto_20180123_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='date_last_active',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date last active'),
        ),
    ]
