# Generated by Django 4.1.13 on 2025-04-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0006_endpoint_oracle_port'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='command',
            index=models.Index(fields=['timestamp', 'org_id'], name='idx_timestamp_org'),
        ),
    ]
