# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0007_session_date_last_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='date_start',
            field=models.DateTimeField(db_index=True, verbose_name='Date start'),
        ),
    ]
