# Generated by Django 4.1.13 on 2025-06-09 07:30

import common.db.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0007_command_idx_timestamp_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='mongodb_port',
            field=common.db.fields.PortField(default=27018, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)], verbose_name='MongoDB port'),
        ),
    ]
