# Generated by Django 4.1.13 on 2025-07-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0008_endpoint_mongodb_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='replay_size',
            field=models.BigIntegerField(default=0, verbose_name='Replay size'),
        ),
    ]
