# Generated by Django 4.1.13 on 2026-07-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0010_alter_command_risk_level_alter_session_login_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='replay_storage',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Replay storage'),
        ),
    ]
