# Generated by Django 4.1.13 on 2026-07-29

import common.db.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0010_alter_command_risk_level_alter_session_login_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='magnus_port',
            field=common.db.fields.PortField(
                default=5525,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(65535),
                ],
                verbose_name='Magnus port',
            ),
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='mariadb_port',
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='mongodb_port',
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='mysql_port',
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='oracle_port',
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='postgresql_port',
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='redis_port',
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='sqlserver_port',
        ),
    ]
