# Generated by Django 5.2.13 on 2026-08-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0010_alter_command_risk_level_alter_session_login_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Is archived'),
        ),
    ]
