# Generated by Django 4.1.13 on 2025-09-30 06:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0010_alter_command_risk_level_alter_session_login_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('chat', models.JSONField(default=dict, verbose_name='Chat')),
                ('meta', models.JSONField(default=dict, verbose_name='Meta')),
                ('pinned', models.BooleanField(default=False, verbose_name='Pinned')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('share_id', models.CharField(blank=True, default='', max_length=36)),
                ('folder_id', models.CharField(blank=True, default='', max_length=36)),
                ('socket_id', models.CharField(blank=True, default='', max_length=36)),
                ('user_id', models.CharField(blank=True, db_index=True, default='', max_length=36)),
                ('session_info', models.JSONField(default=dict, verbose_name='Session Info')),
            ],
            options={
                'verbose_name': 'Chat',
            },
        ),
    ]
