# Generated by Django 2.0.7 on 2018-08-07 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0010_auto_20180423_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='org_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='session',
            name='org_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization'),
        ),
    ]
