# Generated by Django 4.1.13 on 2026-02-26 02:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0010_alter_command_risk_level_alter_session_login_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandHmac',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('record_id', models.UUIDField(db_index=True, verbose_name='Record ID')),
                ('encrypt_fields', models.CharField(default='', max_length=1024, verbose_name='Encrypt fields')),
                ('encrypt_value', models.CharField(default='', max_length=1024, verbose_name='Encrypt value')),
            ],
            options={
                'verbose_name': 'Command HMAC',
                'db_table': 'terminal_command_hmac',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SessionHmac',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('record_id', models.UUIDField(db_index=True, verbose_name='Record ID')),
                ('encrypt_fields', models.CharField(default='', max_length=1024, verbose_name='Encrypt fields')),
                ('encrypt_value', models.CharField(default='', max_length=1024, verbose_name='Encrypt value')),
            ],
            options={
                'verbose_name': 'Session HMAC',
                'db_table': 'terminal_session_hmac',
                'abstract': False,
            },
        ),
    ]
