# Generated by Django 2.0.7 on 2018-08-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0011_auto_20180807_1116'),
    ]

    operations = [
    ]
