# Generated by Django 5.2.13 on 2026-08-06 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0023_platformpackage_platform_package'),
        ('terminal', '0011_endpoint_magnus_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='appprovider',
            name='connection_mode',
            field=models.CharField(choices=[('direct', 'Direct'), ('ssh', 'SSH')], default='direct', max_length=16, verbose_name='Connection mode'),
        ),
        migrations.AddField(
            model_name='appprovider',
            name='deploy_options',
            field=models.JSONField(blank=True, default=dict, verbose_name='Deploy options'),
        ),
        migrations.AddField(
            model_name='appprovider',
            name='host',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_provider', to='assets.host', verbose_name='Host'),
        ),
        migrations.AddField(
            model_name='appprovider',
            name='runtime_type',
            field=models.CharField(choices=[('docker', 'Docker'), ('podman', 'Podman')], default='docker', max_length=16, verbose_name='Runtime type'),
        ),
        migrations.AddField(
            model_name='appprovider',
            name='service_url',
            field=models.URLField(blank=True, default='', max_length=1024, verbose_name='Service URL'),
        ),
    ]
