# Generated by Django 5.2.15 on 2026-09-07 11:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0026_add_virtual_app_host_platform'),
        ('terminal', '0011_endpoint_magnus_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='appprovider',
            name='deploy_options',
            field=models.JSONField(blank=True, default=dict, verbose_name='Deploy options'),
        ),
        migrations.AddField(
            model_name='appprovider',
            name='host',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_provider', to='assets.host', verbose_name='Host'),
        ),
        migrations.AddField(
            model_name='appprovider',
            name='runtime_type',
            field=models.CharField(choices=[('docker', 'Docker'), ('podman', 'Podman')], default='docker', max_length=16, verbose_name='Runtime type'),
        ),
        migrations.AddField(
            model_name='appprovider',
            name='service_url',
            field=models.URLField(blank=True, default='', max_length=1024, verbose_name='Service URL'),
        ),
        migrations.AddField(
            model_name='virtualapppublication',
            name='app_version',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Published version'),
        ),
        migrations.AddField(
            model_name='virtualapppublication',
            name='image_digest',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Image digest'),
        ),
        migrations.AddField(
            model_name='virtualapppublication',
            name='date_synced',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date synced'),
        ),
        migrations.CreateModel(
            name='AppProviderDeployment',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.CharField(default='pending', max_length=16, verbose_name='Status')),
                ('date_start', models.DateTimeField(blank=True, null=True, verbose_name='Date start')),
                ('date_finished', models.DateTimeField(blank=True, null=True, verbose_name='Date finished')),
                ('task', models.UUIDField(blank=True, null=True, verbose_name='Task')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='terminal.appprovider', verbose_name='App Provider')),
                ('publication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='terminal.virtualapppublication', verbose_name='Virtual app publication')),
            ],
            options={
                'verbose_name': 'App Provider deployment',
                'ordering': ('-date_created',),
            },
        ),
    ]
