# Generated by Django 5.2.15 on 2026-09-07 11:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


def migrate_provider_addresses(apps, schema_editor):
    provider_model = apps.get_model('terminal', 'AppProvider')
    host_model = apps.get_model('assets', 'Host')
    asset_model = apps.get_model('assets', 'Asset')
    protocol_model = apps.get_model('assets', 'Protocol')
    platform_model = apps.get_model('assets', 'Platform')
    db = schema_editor.connection.alias
    platform = platform_model.objects.using(db).get(name='VirtualAppHost', internal=True)
    org_id = '00000000-0000-0000-0000-000000000004'
    providers = provider_model.objects.using(db).filter(host__isnull=True).exclude(hostname='')
    for provider in providers.iterator():
        name = provider.name
        if asset_model.objects.using(db).filter(org_id=org_id, name=name).exists():
            name = f'{name[:91]}-{provider.pk}'
        host = host_model.objects.using(db).create(
            name=name, address=provider.hostname, platform_id=platform.pk, org_id=org_id,
        )
        protocol_model.objects.using(db).create(asset_id=host.pk, name='ssh', port=22)
        provider_model.objects.using(db).filter(pk=provider.pk).update(host_id=host.pk)


def restore_provider_addresses(apps, schema_editor):
    provider_model = apps.get_model('terminal', 'AppProvider')
    db = schema_editor.connection.alias
    for provider in provider_model.objects.using(db).select_related('host').iterator():
        if provider.host_id:
            provider_model.objects.using(db).filter(pk=provider.pk).update(hostname=provider.host.address)


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0029_add_virtual_app_host_platform'),
        ('terminal', '0012_retire_builtin_chrome'),
    ]

    operations = [
        migrations.AddField(
            model_name='appprovider',
            name='deploy_options',
            field=models.JSONField(blank=True, default=dict, verbose_name='Deploy options'),
        ),
        migrations.AddField(
            model_name='appprovider',
            name='host',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_provider', to='assets.host', verbose_name='Host'),
        ),
        migrations.AlterField(
            model_name='appprovider',
            name='hostname',
            field=models.CharField(default='', max_length=128, verbose_name='Hostname'),
        ),
        migrations.RunPython(migrate_provider_addresses, restore_provider_addresses),
        migrations.RemoveField(model_name='appprovider', name='hostname'),
        migrations.AddField(
            model_name='virtualapppublication',
            name='app_version',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Published version'),
        ),
        migrations.AddField(
            model_name='virtualapppublication',
            name='date_synced',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date synced'),
        ),
        migrations.CreateModel(
            name='AppProviderDeployment',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.CharField(default='pending', max_length=16, verbose_name='Status')),
                ('date_start', models.DateTimeField(blank=True, null=True, verbose_name='Date start')),
                ('date_finished', models.DateTimeField(blank=True, null=True, verbose_name='Date finished')),
                ('task', models.UUIDField(blank=True, null=True, verbose_name='Task')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='terminal.appprovider', verbose_name='App Provider')),
                ('publication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='terminal.virtualapppublication', verbose_name='Virtual app publication')),
            ],
            options={
                'verbose_name': 'App Provider deployment',
                'ordering': ('-date_created',),
            },
        ),
    ]
