# Generated by Django 5.2.15 on 2026-09-09

import common.db.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0013_virtual_app_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='web_proxy_port',
            field=common.db.fields.PortField(
                default=5001,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(65535),
                ],
                verbose_name='Web proxy port',
            ),
        ),
    ]
