# Generated by Django 5.2.15 on 2026-09-20 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_identity_snapshots(apps, schema_editor):
    alias = schema_editor.connection.alias
    model = apps.get_model('terminal', 'SessionSharing')
    batch = []
    rows = model.objects.using(alias).filter(creator__isnull=False).select_related('creator')
    for row in rows.iterator(chunk_size=1000):
        user = row.creator
        row.creator_display = f'{user.name}({user.username})'
        row.creator_id_snapshot = user.pk
        batch.append(row)
        if len(batch) == 1000:
            model.objects.using(alias).bulk_update(batch, ['creator_display', 'creator_id_snapshot'])
            batch.clear()
    if batch:
        model.objects.using(alias).bulk_update(batch, ['creator_display', 'creator_id_snapshot'])
    model = apps.get_model('terminal', 'SessionJoinRecord')
    batch = []
    rows = model.objects.using(alias).filter(joiner__isnull=False).select_related('joiner')
    for row in rows.iterator(chunk_size=1000):
        user = row.joiner
        row.joiner_display = f'{user.name}({user.username})'
        row.joiner_id_snapshot = user.pk
        batch.append(row)
        if len(batch) == 1000:
            model.objects.using(alias).bulk_update(batch, ['joiner_display', 'joiner_id_snapshot'])
            batch.clear()
    if batch:
        model.objects.using(alias).bulk_update(batch, ['joiner_display', 'joiner_id_snapshot'])
    apps.get_model('terminal', 'SessionSharing').objects.using(alias).filter(creator__isnull=True).update(is_active=False)


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0014_endpoint_web_proxy_port'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionjoinrecord',
            name='joiner_display',
            field=models.CharField(blank=True, default='', editable=False, max_length=258),
        ),
        migrations.AddField(
            model_name='sessionjoinrecord',
            name='joiner_id_snapshot',
            field=models.UUIDField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='sessionsharing',
            name='creator_display',
            field=models.CharField(blank=True, default='', editable=False, max_length=258),
        ),
        migrations.AddField(
            model_name='sessionsharing',
            name='creator_id_snapshot',
            field=models.UUIDField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='sessionjoinrecord',
            name='joiner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Joiner'),
        ),
        migrations.AlterField(
            model_name='sessionjoinrecord',
            name='sharing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='terminal.sessionsharing', verbose_name='Session sharing'),
        ),
        migrations.AlterField(
            model_name='sessionsharing',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.RunPython(backfill_identity_snapshots, migrations.RunPython.noop),
    ]
