# Generated by Django 2.1.7 on 2019-09-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0014_auto_20181226_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='protocol',
            field=models.CharField(choices=[('ssh', 'ssh'), ('rdp', 'rdp'), ('vnc', 'vnc'), ('telnet', 'telnet')], default='ssh', max_length=8),
        ),
    ]
