# Generated by Django 2.2.5 on 2019-11-22 10:07

import uuid

from django.db import migrations, models

import common.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ('terminal', '0015_auto_20190923_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandStorage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Created by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Name')),
                ('type', models.CharField(choices=[('null', 'Null'), ('server', 'Server'), ('es', 'Elasticsearch')],
                                          default='server', max_length=16, verbose_name='Type')),
                ('meta', common.db.fields.EncryptJsonDictTextField(default={})),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReplayStorage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Created by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Name')),
                ('type', models.CharField(
                    choices=[('null', 'Null'), ('server', 'Server'), ('s3', 'S3'), ('ceph', 'Ceph'), ('swift', 'Swift'),
                             ('oss', 'OSS'), ('azure', 'Azure')], default='server', max_length=16,
                    verbose_name='Type')),
                ('meta', common.db.fields.EncryptJsonDictTextField(default={})),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
