# Generated by Django 2.2.7 on 2019-12-02 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0017_auto_20191125_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='remote_addr',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Remote addr'),
        ),
    ]
