# Generated by Django 2.2.7 on 2019-12-06 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0018_auto_20191202_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replaystorage',
            name='type',
            field=models.CharField(choices=[('null', 'Null'), ('server', 'Server'), ('s3', 'S3'), ('ceph', 'Ceph'), ('swift', 'Swift'), ('oss', 'OSS'), ('azure', 'Azure')], default='server', max_length=16, verbose_name='Type'),
        ),
    ]
