# Generated by Django 2.2.10 on 2020-02-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0020_auto_20191218_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='is_finished',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
