# Generated by Django 2.2.10 on 2020-02-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0021_auto_20200213_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_success',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
