# Generated by Django 2.2.10 on 2020-03-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0022_session_is_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='risk_level',
            field=models.SmallIntegerField(choices=[(0, 'Ordinary'), (5, 'Dangerous')], db_index=True, default=0, verbose_name='Risk level'),
        ),
    ]
