# Generated by Django 2.2.10 on 2020-07-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0023_command_risk_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='login_from',
            field=models.CharField(choices=[('ST', 'SSH Terminal'), ('WT', 'Web Terminal')], default='ST', max_length=2, verbose_name='Login from'),
        ),
    ]
