# Generated by Django 2.2.13 on 2020-11-02 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0026_auto_20201027_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='terminal',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='terminal.Terminal'),
        ),
    ]
