# Generated by Django 2.2.13 on 2020-11-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0028_auto_20201110_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandstorage',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='replaystorage',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Name'),
        ),
    ]
