# Generated by Django 3.1 on 2020-12-09 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0029_auto_20201116_1757'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
