# Generated by Django 3.1 on 2021-01-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0030_terminal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandstorage',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='replaystorage',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Comment'),
        ),
    ]
