# Generated by Django 3.1 on 2021-03-24 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0032_auto_20210302_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='login_from',
            field=models.CharField(choices=[('ST', 'SSH Terminal'), ('RT', 'RDP Terminal'), ('WT', 'Web Terminal')], default='ST', max_length=2, verbose_name='Login from'),
        ),
    ]
