# Generated by Django 3.1 on 2021-03-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0032_auto_20210302_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='cpu_used',
            new_name='cpu_load',
        ),
        migrations.AlterField(
            model_name='status',
            name='cpu_load',
            field=models.FloatField(default=0, verbose_name='CPU Load'),
        ),
        migrations.AddField(
            model_name='status',
            name='disk_used',
            field=models.FloatField(default=0, verbose_name='Disk Used'),
        ),
        migrations.AlterField(
            model_name='status',
            name='boot_time',
            field=models.FloatField(default=0, verbose_name='Boot Time'),
        ),
        migrations.AlterField(
            model_name='status',
            name='connections',
            field=models.IntegerField(default=0, verbose_name='Connections'),
        ),
        migrations.AlterField(
            model_name='status',
            name='threads',
            field=models.IntegerField(default=0, verbose_name='Threads'),
        ),
    ]
