# Generated by Django 3.1 on 2021-04-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0033_auto_20210324_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='cpu_used',
        ),
        migrations.AddField(
            model_name='status',
            name='cpu_load',
            field=models.FloatField(default=0, verbose_name='CPU Load'),
        ),
        migrations.AddField(
            model_name='status',
            name='disk_used',
            field=models.FloatField(default=0, verbose_name='Disk Used'),
        ),
        migrations.AlterField(
            model_name='status',
            name='boot_time',
            field=models.FloatField(default=0, verbose_name='Boot Time'),
        ),
        migrations.AlterField(
            model_name='status',
            name='connections',
            field=models.IntegerField(default=0, verbose_name='Connections'),
        ),
        migrations.AlterField(
            model_name='status',
            name='threads',
            field=models.IntegerField(default=0, verbose_name='Threads'),
        ),
    ]
