# Generated by Django 3.1.6 on 2021-05-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0034_auto_20210406_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminal',
            name='type',
            field=models.CharField(choices=[('koko', 'KoKo'), ('guacamole', 'Guacamole'), ('omnidb', 'OmniDB'), ('xrdp', 'Xrdp'), ('lion', 'Lion')], default='koko', max_length=64, verbose_name='type'),
        ),
    ]
