# Generated by Django 3.1.6 on 2021-07-29 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0037_auto_20210623_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='kwargs',
            field=models.JSONField(default=dict, verbose_name='Kwargs'),
        ),
    ]
