# Generated by Django 3.1.13 on 2021-11-30 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0040_sessionjoinrecord_sessionsharing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='command',
            options={'ordering': ('-timestamp',), 'verbose_name': 'Command record'},
        ),
        migrations.AlterModelOptions(
            name='commandstorage',
            options={'verbose_name': 'Command storage'},
        ),
        migrations.AlterModelOptions(
            name='replaystorage',
            options={'verbose_name': 'Replay storage'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-date_start'], 'verbose_name': 'Session record'},
        ),
        migrations.AlterModelOptions(
            name='sessionjoinrecord',
            options={'ordering': ('-date_joined',), 'verbose_name': 'Session join record'},
        ),
        migrations.AlterModelOptions(
            name='sessionsharing',
            options={'ordering': ('-date_created',), 'verbose_name': 'Session sharing'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'get_latest_by': 'date_created', 'verbose_name': 'Status'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Task'},
        ),
        migrations.AlterModelOptions(
            name='terminal',
            options={'ordering': ('is_accepted',), 'verbose_name': 'Terminal'},
        ),
    ]
