# Generated by Django 3.1.12 on 2021-09-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0040_sessionjoinrecord_sessionsharing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionsharing',
            name='verify_code',
            field=models.CharField(max_length=16, verbose_name='Verify code'),
        ),
    ]
