# Generated by Django 3.1.12 on 2022-02-11 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0041_auto_20211130_1037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terminal',
            options={'ordering': ('is_accepted',), 'permissions': (('view_terminalconfig', 'Can view terminal config'),), 'verbose_name': 'Terminal'},
        ),
    ]
