# Generated by Django 3.1.13 on 2022-02-17 13:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0042_auto_20211229_1619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='command',
            options={'ordering': ('-timestamp',), 'verbose_name': 'Command record'},
        ),
        migrations.AlterModelOptions(
            name='commandstorage',
            options={'verbose_name': 'Command storage'},
        ),
        migrations.AlterModelOptions(
            name='replaystorage',
            options={'verbose_name': 'Replay storage'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-date_start'], 'permissions': [('monitor_session', 'Can monitor session'), ('share_session', 'Can share session'), ('terminate_session', 'Can terminate session'), ('validate_sessionactionperm', 'Can validate session action perm')], 'verbose_name': 'Session record'},
        ),
        migrations.AlterModelOptions(
            name='sessionjoinrecord',
            options={'ordering': ('-date_joined',), 'verbose_name': 'Session join record'},
        ),
        migrations.AlterModelOptions(
            name='sessionsharing',
            options={'ordering': ('-date_created',), 'permissions': [('add_supersessionsharing', 'Can add super session sharing')], 'verbose_name': 'Session sharing'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'get_latest_by': 'date_created', 'verbose_name': 'Status'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Task'},
        ),
        migrations.AlterModelOptions(
            name='terminal',
            options={'ordering': ('is_accepted',), 'permissions': (('view_terminalconfig', 'Can view terminal config'),), 'verbose_name': 'Terminal'},
        ),
        migrations.CreateModel(
            name='SessionReplay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Created by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminal.session', verbose_name='Session')),
            ],
            options={
                'permissions': [('upload_sessionreplay', 'Can upload session replay'), ('download_sessionreplay', 'Can download session replay')],
            },
        ),
    ]
