# Generated by Django 3.1.12 on 2021-09-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0043_remove_sessionsharing_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionjoinrecord',
            name='verify_code',
            field=models.CharField(default='0000', max_length=16, verbose_name='Verify code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sessionjoinrecord',
            name='date_left',
            field=models.DateTimeField(db_index=True, null=True, verbose_name='Date end'),
        ),
        migrations.AlterField(
            model_name='sessionjoinrecord',
            name='remote_addr',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='Remote addr'),
        ),
        migrations.AlterField(
            model_name='sessionsharing',
            name='expired_time',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Expired time (min)'),
        ),
        migrations.AlterField(
            model_name='sessionsharing',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Active'),
        ),
    ]
