# Generated by Django 3.1.14 on 2022-03-02 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0046_auto_20220228_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionreplay',
            options={'permissions': [('upload_sessionreplay', 'Can upload session replay'), ('download_sessionreplay', 'Can download session replay')], 'verbose_name': 'Session replay'},
        ),
    ]
