# Generated by Django 3.1.14 on 2022-03-30 03:51
import time

from django.db import migrations, models

start_time = time.time()


def pre_alter(apps, schema_editor):
    global start_time
    start_time = time.time()


def post_alter(apps, schema_editor):
    end_time = time.time()
    msg = ' [Use time: %.3f s] ...' % (end_time - start_time)
    print(msg, end='')


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0047_auto_20220302_1951'),
    ]

    operations = [
        migrations.RunPython(pre_alter),
        migrations.AlterField(
            model_name='command',
            name='input',
            field=models.CharField(db_index=True, max_length=1024, verbose_name='Input'),
        ),
        migrations.RunPython(post_alter),
    ]
