# Generated by Django 3.1.14 on 2022-05-12 06:35

import common.db.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0048_endpoint_endpointrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='redis_port',
            field=common.db.fields.PortField(default=63790, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)], verbose_name='Redis port'),
        ),
    ]
