# Generated by Django 3.1.14 on 2022-05-12 07:22

import common.db.encoder
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0049_endpoint_redis_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionsharing',
            name='meta',
            field=models.JSONField(default=dict, encoder=common.db.encoder.ModelJSONFieldEncoder, verbose_name='Meta'),
        ),
    ]
