# Generated by Django 3.1.14 on 2022-05-17 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0050_auto_20220606_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionsharing',
            name='users',
            field=models.CharField(default=list, max_length=1024, verbose_name='User'),
        ),
    ]
