# Generated by Django 3.1.14 on 2022-06-30 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0050_auto_20220606_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionsharing',
            name='users',
            field=models.TextField(blank=True, verbose_name='User'),
        ),
    ]
