# Generated by Django 3.2.13 on 2022-08-30 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0052_auto_20220713_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='protocol',
            field=models.CharField(db_index=True, default='ssh', max_length=16),
        ),
        migrations.RenameField(
            model_name='session',
            old_name='system_user',
            new_name='account',
        ),
        migrations.RemoveField(
            model_name='session',
            name='system_user_id',
        ),
        migrations.AlterField(
            model_name='session',
            name='account',
            field=models.CharField(db_index=True, max_length=128, verbose_name='Account'),
        ),
    ]
