# Generated by Django 3.2.15 on 2022-10-09 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0052_auto_20220713_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endpoint',
            name='mariadb_port',
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='mysql_port',
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='oracle_11g_port',
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='oracle_12c_port',
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='postgresql_port',
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='redis_port',
        ),
    ]
