# Generated by Django 3.2.14 on 2022-10-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0054_auto_20221024_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applet',
            name='vcs_type',
        ),
        migrations.RemoveField(
            model_name='applet',
            name='vcs_url',
        ),
        migrations.AddField(
            model_name='applet',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
    ]
