# Generated by Django 3.2.14 on 2022-11-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0055_auto_20221031_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='applethost',
            name='deploy_options',
            field=models.JSONField(default=dict, verbose_name='Deploy options'),
        ),
        migrations.AddField(
            model_name='applethostdeployment',
            name='initial',
            field=models.BooleanField(default=False, verbose_name='Initial'),
        ),
    ]
