# Generated by Django 3.2.16 on 2022-12-30 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0056_auto_20221228_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appletpublication',
            name='applet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='terminal.applet', verbose_name='Applet'),
        ),
        migrations.AlterField(
            model_name='appletpublication',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='terminal.applethost', verbose_name='Host'),
        ),
    ]
