# Generated by Django 3.2.14 on 2023-01-09 06:47

import common.db.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0056_auto_20221228_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='mariadb_port',
            field=common.db.fields.PortField(default=33062, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)], verbose_name='MariaDB port'),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='mysql_port',
            field=common.db.fields.PortField(default=33061, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)], verbose_name='MySQL port'),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='oracle_port_range',
            field=common.db.fields.PortRangeField(default='1-65535', max_length=16, verbose_name='Oracle port range'),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='postgresql_port',
            field=common.db.fields.PortField(default=54320, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)], verbose_name='PostgreSQL port'),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='redis_port',
            field=common.db.fields.PortField(default=63790, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)], verbose_name='Redis port'),
        ),
    ]
