# Generated by Django 3.2.16 on 2023-01-10 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0057_auto_20230109_1447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applethost',
            options={'verbose_name': 'Hosting'},
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='oracle_port_range',
        ),
        migrations.AlterField(
            model_name='appletpublication',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='terminal.applethost', verbose_name='Hosting'),
        ),
    ]
