# Generated by Django 3.2.14 on 2023-02-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0058_auto_20230110_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='account_id',
            field=models.CharField(db_index=True, default='', max_length=128, verbose_name='Account id'),
            preserve_default=False,
        ),
    ]
