# Generated by Django 3.2.14 on 2022-11-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0058_auto_20221103_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='applethostdeployment',
            name='task',
            field=models.UUIDField(null=True, verbose_name='Task'),
        ),
    ]
