# Generated by Django 3.2.17 on 2023-04-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0059_session_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionsharing',
            name='action_permission',
            field=models.CharField(default='writable', max_length=16, verbose_name='Action permission'),
        ),
    ]
