# Generated by Django 3.2.14 on 2022-11-18 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0059_applethostdeployment_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applethostdeployment',
            options={'ordering': ('-date_start',)},
        ),
    ]
