# Generated by Django 3.2.14 on 2022-12-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0060_alter_applethostdeployment_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='command',
            old_name='system_user',
            new_name='account',
        ),
        migrations.AlterField(
            model_name='command',
            name='account',
            field=models.CharField(db_index=True, max_length=64, verbose_name='Account'),
        ),
    ]
