# Generated by Django 3.2.17 on 2023-05-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0060_sessionsharing_action_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='applet',
            name='can_concurrent',
            field=models.BooleanField(default=False, verbose_name='Can concurrent'),
        ),
    ]
