# Generated by Django 3.2.14 on 2022-12-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0061_rename_system_user_command_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='session',
            name='type',
            field=models.CharField(db_index=True, default='normal', max_length=16),
        ),
    ]
