# Generated by Django 3.2.17 on 2023-06-09 02:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('terminal', '0061_applet_can_concurrent'),
    ]

    operations = [
        migrations.AddField(
            model_name='applet',
            name='edition',
            field=models.CharField(choices=[('community', 'Community edition'), ('enterprise', 'Enterprise')],
                                   default='community', max_length=128, verbose_name='Edition'),
        ),
    ]
