# Generated by Django 3.2.19 on 2023-06-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0062_applet_edition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endpointrule',
            options={'ordering': ('priority', 'is_active', 'name'), 'verbose_name': 'Endpoint rule'},
        ),
        migrations.AddField(
            model_name='endpointrule',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
    ]
