# Generated by Django 3.2.14 on 2022-12-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0062_auto_20221216_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='applet',
            name='builtin',
            field=models.BooleanField(default=False, verbose_name='Builtin'),
        ),
    ]
