# Generated by Django 4.1.10 on 2023-07-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0063_auto_20230621_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionsharing',
            name='origin',
            field=models.URLField(blank=True, null=True, verbose_name='Origin'),
        ),
    ]
