# Generated by Django 4.1.10 on 2023-07-28 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0063_auto_20230621_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='applethost',
            name='accounts_create_amount',
            field=models.IntegerField(default=100, verbose_name='Accounts create amount'),
        ),
        migrations.AddField(
            model_name='applethost',
            name='auto_create_accounts',
            field=models.BooleanField(default=True, verbose_name='Auto create accounts'),
        ),
        migrations.AddField(
            model_name='sessionsharing',
            name='origin',
            field=models.URLField(blank=True, null=True, verbose_name='Origin'),
        ),
        migrations.AddField(
            model_name='session',
            name='cmd_amount',
            field=models.IntegerField(default=-1, verbose_name='Command amount'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(choices=[('kill_session', 'Kill session'), ('lock_session', 'Lock session'), ('unlock_session', 'Unlock session')], max_length=128, verbose_name='Name'),
        ),
    ]
