# Generated by Django 4.1.10 on 2023-10-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0064_auto_20230728_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='error_reason',
            field=models.CharField(blank=True, max_length=128, verbose_name='Error reason'),
        ),
    ]
