# Generated by Django 3.2.16 on 2022-12-23 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0064_auto_20221220_1956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applet',
            options={'verbose_name': 'Applet'},
        ),
        migrations.AlterModelOptions(
            name='applethost',
            options={'verbose_name': 'Applet host'},
        ),
    ]
