# Generated by Django 4.1.10 on 2023-10-30 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0065_session_error_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='applethost',
            name='using_same_account',
            field=models.BooleanField(default=False, verbose_name='Using same account'),
        ),
    ]
