# Generated by Django 4.1.10 on 2023-08-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0066_auto_20230810_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applet',
            name='enterprise',
        ),
        migrations.AddField(
            model_name='applet',
            name='edition',
            field=models.CharField(choices=[('community', 'Community'), ('enterprise', 'Enterprise')], default='community', max_length=128, verbose_name='Edition'),
        ),
    ]
