# Generated by Django 4.1.10 on 2023-11-09 10:16

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0067_alter_replaystorage_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualApp',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.SlugField(max_length=128, unique=True, verbose_name='Name')),
                ('image_name', models.CharField(max_length=128, verbose_name='Image name')),
                ('image_protocol', models.CharField(default='vnc', max_length=16, verbose_name='Image protocol')),
                ('image_port', models.IntegerField(default=5900, verbose_name='Image port')),
                ('protocols', models.JSONField(default=list, verbose_name='Protocol')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
            ],
            options={
                'verbose_name': 'Virtual app',
            },
        ),
    ]
