# Generated by Django 4.1.10 on 2023-12-08 09:41

import common.db.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0068_virtualapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='sqlserver_port',
            field=common.db.fields.PortField(default=14330, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)], verbose_name='SQLServer port'),
        ),
    ]
