# Generated by Django 4.1.10 on 2023-11-15 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('labels', '0002_auto_20231103_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labeledresource',
            options={'verbose_name': 'Labeled resource'},
        ),
        migrations.AlterField(
            model_name='labeledresource',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labeled_resources', to='labels.label', verbose_name='Label'),
        ),
        migrations.AlterUniqueTogether(
            name='labeledresource',
            unique_together={('label', 'res_type', 'res_id', 'org_id')},
        ),
    ]
