apiVersion: v1
kind: Namespace
metadata:
  name: jumpserver
  labels:
    name: jumpserver
    app.kubernetes.io/name: jumpserver
    app.kubernetes.io/instance: jumpserver
    app.kubernetes.io/version: "4.0"
    app.kubernetes.io/component: namespace
    app.kubernetes.io/part-of: jumpserver
    app.kubernetes.io/managed-by: kubectl
  annotations:
    description: "JumpServer PAM Platform Namespace"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: jumpserver-quota
  namespace: jumpserver
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    services: "10"
    secrets: "20"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: jumpserver-limits
  namespace: jumpserver
spec:
  limits:
  - default:
      cpu: "1"
      memory: "2Gi"
    defaultRequest:
      cpu: "100m"
      memory: "256Mi"
    type: Container
  - default:
      storage: "10Gi"
    type: PersistentVolumeClaim
