# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-11 06:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='Setting',
        ),
        migrations.AlterModelManagers(
            name='setting',
            managers=[
            ],
        ),
        migrations.AlterModelTable(
            name='setting',
            table='settings',
        ),
    ]
