# Generated by Django 2.1 on 2018-09-03 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_setting_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='encrypted',
            field=models.BooleanField(default=False),
        ),
    ]
