# Generated by Django 2.1.7 on 2019-02-21 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_setting_encrypted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': 'Setting'},
        ),
    ]
