# Generated by Django 2.1.7 on 2019-03-04 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20190221_1902'),
    ]

    database_operations = [
        migrations.AlterModelTable('setting', 'settings_setting')
    ]
    state_operations = [migrations.DeleteModel('setting')]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations
        )
    ]
