- hosts: mysql
  gather_facts: no
  vars:
    ansible_python_interpreter: /Users/xiaofeng/Desktop/jumpserver/venv/bin/python

  tasks:
    - name: Get info
      community.mysql.mysql_info:
        login_user: "{{ jms_account.username }}"
        login_password: "{{ jms_account.secret }}"
        login_host: "{{ jms_asset.address }}"
        login_port: 1234
        filter: users
      register: db_info

    - name: Define info by set_fact
      set_fact:
        info: "{{ db_info.users }}"

    - debug:
        var: info
