# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usergroup',
            table='user_group',
        ),
    ]
