# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-13 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='_public_key',
            field=models.CharField(blank=True, max_length=2000, verbose_name='ssh public key'),
        ),
    ]
