# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160814_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='guanghongwei', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=b'', verbose_name='\u5934\u50cf'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_by',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='\u624b\u673a\u53f7'),
        ),
        migrations.AlterField(
            model_name='user',
            name='private_key',
            field=models.CharField(blank=True, max_length=5000, verbose_name='ssh\u79c1\u94a5'),
        ),
        migrations.AlterField(
            model_name='user',
            name='public_key',
            field=models.CharField(blank=True, max_length=1000, verbose_name='\u516c\u94a5'),
        ),
        migrations.AlterField(
            model_name='user',
            name='secret_key_2FA',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='wechat',
            field=models.CharField(blank=True, max_length=30, verbose_name='\u5fae\u4fe1'),
        ),
    ]
