# Generated by Django 4.1.13 on 2025-05-15 02:38

import common.utils.django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_face_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_expired',
            field=models.DateTimeField(blank=True, db_index=True, default=common.utils.django.user_date_expired_default, null=True, verbose_name='Date expired'),
        ),
    ]
