# Generated by Django 4.1.13 on 2026-02-25 03:27

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import common.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_fix_user_wechat_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='UKey',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('u_key_serial', models.CharField(max_length=128, unique=True, verbose_name='USBKey Serial')),
                ('u_key_public_key', common.db.fields.EncryptTextField(verbose_name='USBKey Public Key')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_usb_key', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User UKey',
            },
        ),
    ]
