# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20160815_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='comment',
            field=models.TextField(blank=True, max_length=200, verbose_name='\u63cf\u8ff0'),
        ),
    ]
