# Generated by Django 4.1.13 on 2026-03-23 07:00

import common.db.fields
from django.db import migrations

user_email_mapper = {}

def get_user_email_mapper(apps, schema_editor):
    User = apps.get_model('users', 'User')
    for user in User.objects.all():
        user_email_mapper[str(user.id)] = user.email

    
def set_user_encrypted_email(apps, schema_editor):
    User = apps.get_model('users', 'User')
    for user in User.objects.all():
        if str(user.id) in user_email_mapper:
            user.email = user_email_mapper[str(user.id)]
            user.save(update_fields=['email'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_fix_user_wechat_phone'),
    ]

    operations = [
        migrations.RunPython(get_user_email_mapper),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=common.db.fields.EncryptCharField(max_length=128, unique=True, verbose_name='Email'),
        ),
        migrations.RunPython(set_user_encrypted_email),
    ]
