# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20160816_1358'),
        ('users', '0005_auto_20160816_2252'),
    ]

    operations = [
    ]
