# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180306_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='secret_key_otp',
            new_name='otp_secret_key',
        ),
        migrations.RemoveField(
            model_name='user',
            name='enable_otp',
        ),
        migrations.AddField(
            model_name='user',
            name='otp_level',
            field=models.SmallIntegerField(choices=[(0, 'Disable'), (1, 'Enable'), (2, 'Force enable')], default=0, verbose_name='Enable OTP'),
        ),
    ]
