# Generated by Django 5.2.13 on 2026-06-03 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ukey_sn',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='UKey SN'),
        ),
    ]
