# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-19 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180411_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp_secret_key',
        ),
        migrations.AddField(
            model_name='user',
            name='_otp_secret_key',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
