# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_merge_20160817_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatar', verbose_name='\u5934\u50cf'),
        ),
    ]
