# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 22:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20160818_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_expired',
            field=models.DateTimeField(default=datetime.datetime(2086, 8, 3, 22, 43, 39, 338972), verbose_name='\u6709\u6548\u671f'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True, verbose_name='\u7528\u6237\u540d'),
        ),
    ]
