# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20160820_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='enable_2FA',
            new_name='enable_otp',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='secret_key_2FA',
            new_name='secret_key_otp',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_expired',
            field=models.DateTimeField(verbose_name='\u6709\u6548\u671f'),
        ),
    ]
