# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 15:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20160820_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_expired',
            field=models.DateTimeField(default=datetime.datetime(2086, 8, 3, 15, 13, 28, 819421, tzinfo=utc), verbose_name='\u6709\u6548\u671f'),
        ),
    ]
