# Generated by Django 2.1.1 on 2018-11-05 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20180816_1652'),
    ]

    operations = [
    ]
