# Generated by Django 2.1.7 on 2019-06-25 03:04

import common.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20190612_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='_otp_secret_key',
            field=common.db.fields.EncryptCharField(blank=True, max_length=128, null=True, verbose_name='OTP secret key'),
        ),
        migrations.AlterField(
            model_name='user',
            name='_private_key',
            field=common.db.fields.EncryptTextField(blank=True, null=True, verbose_name='Private key'),
        ),
        migrations.AlterField(
            model_name='user',
            name='_public_key',
            field=common.db.fields.EncryptTextField(blank=True, null=True, verbose_name='Public key'),
        ),
        migrations.AlterField(
            model_name='user',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
    ]
