# Generated by Django 2.1.7 on 2019-07-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20190625_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_by',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Created by'),
        ),
    ]
