# Generated by Django 3.1 on 2021-04-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20201118_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wecom_id',
            field=models.CharField(default=None, max_length=128, null=True, unique=True),
        ),
    ]
