# Generated by Django 3.1 on 2021-04-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20201118_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='require_password_update',
            field=models.BooleanField(default=False),
        ),
    ]
