# Generated by Django 3.1 on 2021-04-21 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20201118_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOldPassword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Date updated')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_passwords', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
