# Generated by Django 3.1 on 2021-04-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_user_wecom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dingtalk_id',
            field=models.CharField(default=None, max_length=128, null=True, unique=True),
        ),
    ]
