# Generated by Django 3.1 on 2021-04-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_userpasswordhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='need_update_password',
            field=models.BooleanField(default=False),
        ),
    ]
