# Generated by Django 3.1.6 on 2021-08-06 02:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0035_auto_20210526_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='feishu_id',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='FeiShu'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('feishu_id',), ('wecom_id',), ('dingtalk_id',)},
        ),
    ]
