# Generated by Django 3.1.12 on 2021-09-29 06:03

from django.db import migrations, models


def migrate_app_users(apps, schema_editor):
    user_model = apps.get_model('users', 'User')
    app_users = user_model.objects.filter(role='App')
    app_users.update(is_app=True)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_user_feishu_id'),
        # ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_app',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(migrate_app_users),
    ]
