# Generated by Django 3.1.13 on 2021-12-07 08:23

import common.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_user_feishu_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secret_key',
            field=common.db.fields.EncryptCharField(blank=True, max_length=256, null=True, verbose_name='Secret key'),
        ),
    ]
