# Generated by Django 3.1.6 on 2021-07-01 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_auto_20210701_1353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'default_permissions': [], 'ordering': ['username'], 'permissions': [('create_user', 'Create user'), ('update_user', 'Update user'), ('delete_user', 'Delete user'), ('view_user', 'View user')], 'verbose_name': 'User'},
        ),
    ]
