# Generated by Django 3.1.6 on 2021-07-06 11:47

from django.db import migrations, models


def migrate_app_users(apps, schema_editor):
    user_model = apps.get_model('users', 'User')
    app_users = user_model.objects.filter(role='App')
    app_users.update(is_app=True)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_auto_20210701_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_app',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(migrate_app_users),
        migrations.RemoveField(
            model_name='user',
            name='role',
        )
    ]
