# Generated by Django 3.1.13 on 2021-11-30 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_auto_20210929_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpasswordhistory',
            options={'verbose_name': 'User password history'},
        ),
    ]
