# Generated by Django 3.1.13 on 2021-12-29 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_auto_20211208_1133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'permissions': [('invite', 'Can invite user'), ('remove', 'Can remove user')], 'verbose_name': 'User'},
        ),
    ]
