# Generated by Django 3.1.14 on 2022-06-14 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_auto_20211229_1852'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('feishu_id',), ('wecom_id',), ('dingtalk_id',)},
        ),
    ]
