# Generated by Django 3.1.12 on 2022-02-11 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_auto_20211229_1852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'permissions': [('invite_user', 'Can invite user'), ('remove_user', 'Can remove user'), ('match_user', 'Can match user')], 'verbose_name': 'User'},
        ),
    ]
