# Generated by Django 3.2.14 on 2022-10-11 09:45

import common.db.fields
import common.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_alter_user_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_secret_key',
            field=common.db.fields.EncryptCharField(blank=True, max_length=128, null=True, verbose_name='OTP secret key'),
        ),
        migrations.AlterField(
            model_name='userpasswordhistory',
            name='user',
            field=models.ForeignKey(on_delete=common.db.models.CASCADE_SIGNAL_SKIP, related_name='history_passwords', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
