# Generated by Django 4.1.10 on 2023-09-15 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_usersession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
