# Generated by Django 4.1.10 on 2023-11-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_wechat_phone_encrypt'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('feishu_id',), ('dingtalk_id',), ('wecom_id',)},
        ),
        migrations.AddField(
            model_name='user',
            name='slack_id',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='Slack'),
        ),
        migrations.AlterField(
            model_name='user',
            name='source',
            field=models.CharField(choices=[('local', 'Local'), ('ldap', 'LDAP/AD'), ('openid', 'OpenID'), ('radius', 'Radius'), ('cas', 'CAS'), ('saml2', 'SAML2'), ('oauth2', 'OAuth2'), ('wecom', 'WeCom'), ('dingtalk', 'DingTalk'), ('feishu', 'FeiShu'), ('slack', 'Slack'), ('custom', 'Custom')], default='local', max_length=30, verbose_name='Source'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('slack_id',), ('feishu_id',), ('dingtalk_id',), ('wecom_id',)},
        ),
    ]
