# Generated by Django 4.1.13 on 2024-03-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_alter_user_unique_together_user_slack_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lark_id',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='Lark'),
        ),
        migrations.AlterField(
            model_name='user',
            name='source',
            field=models.CharField(choices=[('local', 'Local'), ('ldap', 'LDAP/AD'), ('openid', 'OpenID'), ('radius', 'Radius'), ('cas', 'CAS'), ('saml2', 'SAML2'), ('oauth2', 'OAuth2'), ('wecom', 'WeCom'), ('dingtalk', 'DingTalk'), ('feishu', 'FeiShu'), ('lark', 'Lark'), ('slack', 'Slack'), ('custom', 'Custom')], default='local', max_length=30, verbose_name='Source'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('wecom_id',), ('slack_id',), ('dingtalk_id',), ('lark_id',), ('feishu_id',)},
        ),
    ]
