# Generated by Django 4.1.13 on 2024-05-17 07:56

import common.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_user_lark_id_alter_user_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usbkey_sn',
            field=common.db.fields.EncryptCharField(blank=True, max_length=128, null=True, verbose_name='USBKey serial number'),
        ),
    ]
