# Generated by Django 3.2.14 on 2022-12-06 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('applications', '0003_auto_20191210_1659'),
        ('tickets', '0001_initial'),
        ('assets', '0002_auto_20180105_1807'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('terminal', '0002_auto_20171228_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketassignee',
            name='assignee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_assignees',
                                    to=settings.AUTH_USER_MODEL, verbose_name='Assignee'),
        ),
        migrations.AddField(
            model_name='ticketassignee',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_assignees',
                                    to='tickets.ticketstep'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='applied_tickets', to=settings.AUTH_USER_MODEL,
                                    verbose_name='Applicant'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='flow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets',
                                    to='tickets.ticketflow', verbose_name='TicketFlow'),
        ),
        migrations.AddField(
            model_name='comment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments',
                                    to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments',
                                    to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='approvalrule',
            name='assignees',
            field=models.ManyToManyField(related_name='assigned_ticket_flow_approval_rule', to=settings.AUTH_USER_MODEL,
                                         verbose_name='Assignees'),
        ),
        migrations.CreateModel(
            name='SuperTicket',
            fields=[
            ],
            options={
                'verbose_name': 'Super ticket',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tickets.ticket',),
        ),
        migrations.AddField(
            model_name='applyloginassetticket',
            name='apply_login_asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.asset',
                                    verbose_name='Login asset'),
        ),
        migrations.AddField(
            model_name='applyloginassetticket',
            name='apply_login_system_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.systemuser',
                                    verbose_name='Login system user'),
        ),
        migrations.AddField(
            model_name='applyloginassetticket',
            name='apply_login_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to=settings.AUTH_USER_MODEL, verbose_name='Login user'),
        ),
        migrations.AddField(
            model_name='applycommandticket',
            name='apply_from_cmd_filter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.commandfilter',
                                    verbose_name='From cmd filter'),
        ),
        migrations.AddField(
            model_name='applycommandticket',
            name='apply_from_cmd_filter_rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='assets.commandfilterrule', verbose_name='From cmd filter rule'),
        ),
        migrations.AddField(
            model_name='applycommandticket',
            name='apply_from_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='terminal.session',
                                    verbose_name='Session'),
        ),
        migrations.AddField(
            model_name='applycommandticket',
            name='apply_run_system_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.systemuser',
                                    verbose_name='Run system user'),
        ),
        migrations.AddField(
            model_name='applycommandticket',
            name='apply_run_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to=settings.AUTH_USER_MODEL, verbose_name='Run user'),
        ),
        migrations.AddField(
            model_name='applyassetticket',
            name='apply_assets',
            field=models.ManyToManyField(to='assets.Asset', verbose_name='Apply assets'),
        ),
        migrations.AddField(
            model_name='applyassetticket',
            name='apply_nodes',
            field=models.ManyToManyField(to='assets.Node', verbose_name='Apply nodes'),
        ),
        migrations.AddField(
            model_name='applyassetticket',
            name='apply_system_users',
            field=models.ManyToManyField(to='assets.SystemUser', verbose_name='Apply system users'),
        ),
        migrations.AddField(
            model_name='applyapplicationticket',
            name='apply_applications',
            field=models.ManyToManyField(to='applications.Application', verbose_name='Apply applications'),
        ),
        migrations.AddField(
            model_name='applyapplicationticket',
            name='apply_system_users',
            field=models.ManyToManyField(to='assets.SystemUser', verbose_name='Apply system users'),
        ),
    ]
