# Generated by Django 2.2.10 on 2020-08-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20200728_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assignee_display',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Assignee display name'),
        ),
    ]
