# Generated by Django 2.2.13 on 2020-09-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20200804_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=128, verbose_name='Comment'),
        ),
    ]
