# Generated by Django 4.1.13 on 2026-03-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_replace_assignees_to_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='state',
            field=models.CharField(choices=[('all', 'All'), ('pending', 'Ticket open'), ('closed', 'Ticket closed'), ('approved', 'Ticket approved'), ('rejected', 'Ticket rejected')], default='pending', max_length=16, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Ticket open'), ('closed', 'Ticket finished')], default='open', max_length=16, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='ticketassignee',
            name='state',
            field=models.CharField(choices=[('all', 'All'), ('pending', 'Ticket open'), ('closed', 'Ticket closed'), ('approved', 'Ticket approved'), ('rejected', 'Ticket rejected')], default='pending', max_length=64),
        ),
        migrations.AlterField(
            model_name='ticketstep',
            name='state',
            field=models.CharField(choices=[('pending', 'Step pending'), ('closed', 'Step closed'), ('approved', 'Step approved'), ('rejected', 'Step rejected')], default='pending', max_length=64, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='ticketstep',
            name='status',
            field=models.CharField(choices=[('active', 'Step active'), ('closed', 'Step closed'), ('pending', 'Step pending')], default='pending', max_length=16),
        ),
    ]