# Generated by Django 2.2.13 on 2020-10-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_meta_confirmed_system_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Comment'),
        ),
    ]
