# Generated by Django 4.1.13 on 2026-08-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_ticket_state_alter_ticket_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='cc_users',
            field=models.ManyToManyField(
                blank=True, related_name='cc_tickets', to='users.user', verbose_name='CC users'
            ),
        ),
        migrations.AddField(
            model_name='ticketflow',
            name='cc_users',
            field=models.ManyToManyField(
                blank=True, related_name='cc_ticket_flows', to='users.user', verbose_name='CC users'
            ),
        ),
    ]
