# Generated by Django 3.1 on 2020-12-24 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def migrate_tickets_fields_name(apps, schema_editor):
    ticket_model = apps.get_model("tickets", "Ticket")
    tickets = ticket_model.origin_objects.all()

    for ticket in tickets:
        ticket.applicant = ticket.user
        ticket.applicant_display = ticket.user_display
        ticket.handler = ticket.assignee
        ticket.handler_display = ticket.assignee_display
        ticket.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0006_auto_20201023_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Applicant'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='applicant_display',
            field=models.CharField(default='', max_length=128, verbose_name='Applicant display'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='handler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Assignee'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='handler_display',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Assignee name'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assignees',
            field=models.ManyToManyField(related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Assignees'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assignees_display',
            field=models.CharField(blank=True, max_length=128, verbose_name='Assignees display'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='meta',
            field=models.JSONField(verbose_name='Meta'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('general', 'General'), ('login_confirm', 'Login confirm'), ('apply_asset', 'Apply for asset'), ('apply_application', 'Apply for application')], default='general', max_length=64, verbose_name='Type'),
        ),
        migrations.RunPython(migrate_tickets_fields_name)
    ]
