# Generated by Django 4.1.13 on 2026-08-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticket_cc_users_ticketflow_cc_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketflow',
            name='name',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='approvalrule',
            name='level',
            field=models.SmallIntegerField(
                choices=[
                    (1, 'One level'), (2, 'Two level'), (3, 'Three level'),
                    (4, 'Four level'), (5, 'Five level')
                ],
                default=1,
                verbose_name='Approve level',
            ),
        ),
        migrations.AlterField(
            model_name='ticketflow',
            name='approval_level',
            field=models.SmallIntegerField(
                choices=[
                    (1, 'One level'), (2, 'Two level'), (3, 'Three level'),
                    (4, 'Four level'), (5, 'Five level')
                ],
                default=1,
                verbose_name='Approve level',
            ),
        ),
        migrations.AlterField(
            model_name='ticketstep',
            name='level',
            field=models.SmallIntegerField(
                choices=[
                    (1, 'One level'), (2, 'Two level'), (3, 'Three level'),
                    (4, 'Four level'), (5, 'Five level')
                ],
                default=1,
                verbose_name='Approve level',
            ),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='approval_step',
            field=models.SmallIntegerField(
                choices=[
                    (1, 'One level'), (2, 'Two level'), (3, 'Three level'),
                    (4, 'Four level'), (5, 'Five level')
                ],
                default=1,
                verbose_name='Approval step',
            ),
        ),
    ]
