# Generated by Django 5.2.15 on 2026-09-20 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_identity_snapshots(apps, schema_editor):
    alias = schema_editor.connection.alias
    model = apps.get_model('tickets', 'TicketAssignee')
    batch = []
    rows = model.objects.using(alias).filter(assignee__isnull=False).select_related('assignee')
    for row in rows.iterator(chunk_size=1000):
        user = row.assignee
        row.assignee_display = f'{user.name}({user.username})'
        row.assignee_id_snapshot = user.pk
        batch.append(row)
        if len(batch) == 1000:
            model.objects.using(alias).bulk_update(batch, ['assignee_display', 'assignee_id_snapshot'])
            batch.clear()
    if batch:
        model.objects.using(alias).bulk_update(batch, ['assignee_display', 'assignee_id_snapshot'])


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_applyassetticket_expire_soon_notice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketassignee',
            name='assignee_display',
            field=models.CharField(blank=True, default='', editable=False, max_length=258),
        ),
        migrations.AddField(
            model_name='ticketassignee',
            name='assignee_id_snapshot',
            field=models.UUIDField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='ticketassignee',
            name='assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_assignees', to=settings.AUTH_USER_MODEL, verbose_name='Assignee'),
        ),
        migrations.RunPython(backfill_identity_snapshots, migrations.RunPython.noop),
    ]
