# Generated by Django 5.2.15 on 2026-09-22 12:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_ticketassignee_assignee_display_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('type', models.CharField(choices=[('general', 'General'), ('apply_asset', 'Apply for asset'), ('login_confirm', 'Login confirm'), ('command_confirm', 'Command confirm'), ('login_asset_confirm', 'Login asset confirm')], max_length=64, verbose_name='Type')),
                ('enabled', models.BooleanField(default=False, verbose_name='Enabled')),
                ('legacy_flow_id', models.UUIDField(editable=False, null=True, unique=True)),
                ('migration_notes', models.JSONField(default=dict, editable=False)),
            ],
            options={
                'verbose_name': 'Approval workflow',
                'default_permissions': ('add', 'change', 'view'),
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowNode',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=64)),
                ('type', models.CharField(choices=[('start', 'Start'), ('approval', 'Approval'), ('condition', 'Condition'), ('end', 'End')], max_length=16)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('config', models.JSONField(default=dict)),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Workflow node',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ApprovalTask',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('assignee_snapshot', models.JSONField(default=dict, editable=False)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('transferred', 'Transferred'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('is_added', models.BooleanField(default=False)),
                ('date_finished', models.DateTimeField(null=True)),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_tasks', to=settings.AUTH_USER_MODEL)),
                ('predecessor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successors', to='tickets.approvaltask')),
            ],
            options={
                'verbose_name': 'Approval task',
                'ordering': ['date_created', 'id'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('context', models.JSONField(default=dict, editable=False)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('error', 'Error')], default='pending', max_length=16)),
                ('date_started', models.DateTimeField(null=True)),
                ('date_finished', models.DateTimeField(null=True)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_instance', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Workflow instance',
                'ordering': ['-date_created', 'id'],
                'default_permissions': ('view',),
            },
        ),
        migrations.CreateModel(
            name='WorkflowNodeInstance',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('running', 'Running'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], default='running', max_length=16)),
                ('required', models.PositiveIntegerField(default=0)),
                ('deadline', models.DateTimeField(db_index=True, null=True)),
                ('date_finished', models.DateTimeField(null=True)),
                ('result', models.JSONField(default=dict)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='node_instances', to='tickets.workflowinstance')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='tickets.workflownode')),
            ],
            options={
                'verbose_name': 'Workflow node instance',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='WorkflowEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=64)),
                ('actor_snapshot', models.JSONField(default=dict, editable=False)),
                ('data', models.JSONField(default=dict)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tickets.approvaltask')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='tickets.workflowinstance')),
                ('node_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tickets.workflownodeinstance')),
            ],
            options={
                'verbose_name': 'Workflow event',
                'ordering': ['id'],
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='approvaltask',
            name='node_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='tickets.workflownodeinstance'),
        ),
        migrations.CreateModel(
            name='WorkflowVersion',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('published_at', models.DateTimeField(editable=False, null=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='tickets.workflow')),
            ],
            options={
                'verbose_name': 'Workflow version',
                'default_permissions': (),
                'ordering': ['-number'],
            },
        ),
        migrations.AddField(
            model_name='workflownode',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='tickets.workflowversion'),
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='tickets.workflowversion'),
        ),
        migrations.CreateModel(
            name='WorkflowEdge',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('condition', models.BooleanField(null=True)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing', to='tickets.workflownode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming', to='tickets.workflownode')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='tickets.workflowversion')),
            ],
            options={
                'verbose_name': 'Workflow edge',
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='workflow',
            name='active_version',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tickets.workflowversion'),
        ),
        migrations.AddConstraint(
            model_name='workflownodeinstance',
            constraint=models.UniqueConstraint(fields=('instance', 'node'), name='tickets_workflow_node_run_uniq'),
        ),
        migrations.AddIndex(
            model_name='approvaltask',
            index=models.Index(fields=['assignee', 'state'], name='tickets_task_assignee_state'),
        ),
        migrations.AddConstraint(
            model_name='approvaltask',
            constraint=models.UniqueConstraint(fields=('node_instance', 'assignee'), name='tickets_approval_task_user_uniq'),
        ),
        migrations.AddConstraint(
            model_name='workflowversion',
            constraint=models.UniqueConstraint(fields=('workflow', 'number'), name='tickets_workflow_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='workflownode',
            constraint=models.UniqueConstraint(fields=('version', 'key'), name='tickets_workflow_node_key_uniq'),
        ),
        migrations.AddConstraint(
            model_name='workflowedge',
            constraint=models.UniqueConstraint(fields=('version', 'source', 'target'), name='tickets_workflow_edge_uniq'),
        ),
        migrations.AddConstraint(
            model_name='workflow',
            constraint=models.UniqueConstraint(fields=('org_id', 'type', 'name'), name='tickets_workflow_org_name_uniq'),
        ),
    ]
