# Generated by Django 3.1.6 on 2021-08-11 03:53

from django.conf import settings
from django.db import migrations, models, transaction
import django.db.models.deletion
import tickets.models.ticket
import uuid
import json

ticket_assignee_m2m = list()


def get_ticket_assignee_m2m_info(apps, schema_editor):
    ticket_model = apps.get_model("tickets", "Ticket")
    for i in ticket_model.objects.only('id', 'assignees', 'action', 'created_by'):
        ticket_assignee_m2m.append((i.id, list(i.assignees.values_list('id', flat=True)), i.action, i.created_by))


def update_ticket_process(apps, schema_editor):
    ticket_model = apps.get_model("tickets", "Ticket")
    updates = list()
    with transaction.atomic():
        for instance in ticket_model.objects.all():
            instance.process = [{
                'action': instance.action,
                'processor': instance.processor.id if instance.processor else '',
                'processor_display': instance.processor_display if instance.processor_display else '',
                'assignees': list(instance.assignees.values_list('id', flat=True)) if instance.assignees else [],
                'assignees_display': instance.assignees_display if instance.assignees_display else []
            }, ]
            updates.append(instance)
        ticket_model.objects.bulk_update(updates, ['process', ])


def create_ticket_assignee_m2m_info(apps, schema_editor):
    ticket_assignee_model = apps.get_model("tickets", "TicketAssignee")
    creates = list()
    with transaction.atomic():
        for id, assignees, action, created_by in ticket_assignee_m2m:
            for assignee_id in assignees:
                creates.append(
                    ticket_assignee_model(
                        ticket_id=id, user_id=assignee_id, is_processor=True, action=action, created_by=created_by
                    )
                )
        ticket_assignee_model.objects.bulk_create(creates)


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0009_auto_20210426_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketFlow',
            fields=[
                ('org_id',
                 models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Created by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('type', models.CharField(choices=[('general', 'General'), ('login_confirm', 'Login confirm'),
                                                   ('apply_asset', 'Apply for asset'),
                                                   ('apply_application', 'Apply for application'),
                                                   ('login_asset_confirm', 'Login asset confirm'),
                                                   ('command_confirm', 'Command confirm')], default='general',
                                          max_length=64, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Ticket flow',
            },
        ),
        migrations.RunPython(get_ticket_assignee_m2m_info),
        migrations.AddField(
            model_name='ticket',
            name='process',
            field=models.JSONField(default=list, encoder=tickets.models.ticket.ModelJSONFieldEncoder,
                                   verbose_name='Process'),
        ),
        migrations.RunPython(update_ticket_process),
        migrations.RemoveField(
            model_name='ticket',
            name='assignees',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='assignees_display',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='processor_display',
        ),
        migrations.AddField(
            model_name='ticket',
            name='approve_level',
            field=models.SmallIntegerField(default=1, verbose_name='Approve level'),
        ),
        migrations.CreateModel(
            name='ApprovalRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Created by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('approve_level', models.SmallIntegerField(choices=[(1, 'One level'), (2, 'Two level')], default=1,
                                                           verbose_name='Approve level')),
                ('approve_strategy', models.CharField(
                    choices=[('super', 'Super user'), ('super_admin', 'Super admin user'), ('all_user', 'All user')],
                    default='super_admin', max_length=64, verbose_name='Approve strategy')),
                ('assignees_display',
                 models.JSONField(default=list, encoder=tickets.models.ticket.ModelJSONFieldEncoder,
                                  verbose_name='Assignees display')),
                ('assignees',
                 models.ManyToManyField(related_name='assigned_ticket_flow_approve', to=settings.AUTH_USER_MODEL,
                                        verbose_name='Assignees')),
                ('ticket_flow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                                  related_name='ticket_flow_approves', to='tickets.ticketflow',
                                                  verbose_name='Ticket Flow')),
            ],
            options={
                'verbose_name': 'Ticket flow approve',
            },
        ),
        migrations.CreateModel(
            name='TicketAssignee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Created by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('approve_level', models.SmallIntegerField(choices=[(1, 'One level'), (2, 'Two level')], default=1,
                                                           verbose_name='Approve level')),
                ('is_processor', models.BooleanField(default=False)),
                ('action', models.CharField(
                    choices=[('open', 'Open'), ('approve', 'Approve'), ('reject', 'Reject'), ('close', 'Close')],
                    default='open', max_length=16, verbose_name='Action')),
                ('ticket',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m2m_ticket_users',
                                   to='tickets.ticket', verbose_name='Ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m2m_user_tickets',
                                           to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Ticket assignee',
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='flow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='ticket_flow_tickets', to='tickets.ticketflow',
                                    verbose_name='TicketFlow'),
        ),
        migrations.RunPython(create_ticket_assignee_m2m_info),
        migrations.AddField(
            model_name='ticket',
            name='assignees',
            field=models.ManyToManyField(related_name='assigned_tickets', through='tickets.TicketAssignee',
                                         to=settings.AUTH_USER_MODEL, verbose_name='Assignees'),
        ),
    ]
