# Generated by Django 3.1.6 on 2021-08-12 03:10

import common.db.encoder
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0009_auto_20210426_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Created by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('level', models.SmallIntegerField(choices=[(1, 'One level'), (2, 'Two level')], default=1, verbose_name='Approve level')),
                ('strategy', models.CharField(choices=[('super', 'Super user'), ('super_admin', 'Super admin user'), ('all_user', 'All user')], default='super_admin', max_length=64, verbose_name='Approve strategy')),
                ('assignees_display', models.JSONField(default=list, encoder=common.db.encoder.ModelJSONFieldEncoder, verbose_name='Assignees display')),
                ('assignees', models.ManyToManyField(related_name='assigned_ticket_flow_approval_rule', to=settings.AUTH_USER_MODEL, verbose_name='Assignees')),
            ],
            options={
                'verbose_name': 'Ticket flow approval rule',
            },
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='action',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='assignees',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='assignees_display',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='processor_display',
        ),
        migrations.AddField(
            model_name='ticket',
            name='approval_step',
            field=models.SmallIntegerField(choices=[(1, 'One level'), (2, 'Two level')], default=1, verbose_name='Approval step'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='process_map',
            field=models.JSONField(default=list, encoder=common.db.encoder.ModelJSONFieldEncoder, verbose_name='Process'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='state',
            field=models.CharField(choices=[('open', 'Open'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='open', max_length=16, verbose_name='State'),
        ),
        migrations.CreateModel(
            name='TicketProcess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Created by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('step', models.SmallIntegerField(choices=[(1, 'One level'), (2, 'Two level')], default=1, verbose_name='Approve level')),
                ('action', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=16, verbose_name='Action')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m2m_user_tickets', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m2m_ticket_users', to='tickets.ticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Ticket assignee',
            },
        ),
        migrations.CreateModel(
            name='TicketFlow',
            fields=[
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Created by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('type', models.CharField(choices=[('general', 'General'), ('login_confirm', 'Login confirm'), ('apply_asset', 'Apply for asset'), ('apply_application', 'Apply for application'), ('login_asset_confirm', 'Login asset confirm'), ('command_confirm', 'Command confirm')], default='general', max_length=64, verbose_name='Type')),
                ('approval_level', models.SmallIntegerField(choices=[(1, 'One level'), (2, 'Two level')], default=1, verbose_name='Approval level')),
                ('rules', models.ManyToManyField(related_name='ticket_flows', to='tickets.ApprovalRule')),
            ],
            options={
                'verbose_name': 'Ticket flow',
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='flow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.ticketflow', verbose_name='TicketFlow'),
        ),
    ]
