# Generated by Django 3.1.13 on 2021-12-15 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_auto_20210812_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalrule',
            name='assignees_display',
        ),
    ]
