# Generated by Django 3.1.6 on 2021-08-12 03:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0010_auto_20210812_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assignees',
            field=models.ManyToManyField(related_name='assigned_tickets', through='tickets.TicketProcess', to=settings.AUTH_USER_MODEL, verbose_name='Assignees'),
        ),
    ]
