# Generated by Django 5.2.15 on 2026-09-22 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_workflow_foundation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.workflow', verbose_name='Workflow'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='state',
            field=models.CharField(choices=[('all', 'All'), ('pending', 'Ticket open'), ('closed', 'Ticket closed'), ('approved', 'Ticket approved'), ('rejected', 'Ticket rejected'), ('expired', 'Expired'), ('error', 'Error')], default='pending', max_length=16, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='ticketassignee',
            name='state',
            field=models.CharField(choices=[('all', 'All'), ('pending', 'Ticket open'), ('closed', 'Ticket closed'), ('approved', 'Ticket approved'), ('rejected', 'Ticket rejected'), ('expired', 'Expired'), ('error', 'Error')], default='pending', max_length=64),
        ),
    ]
