# Generated by Django 3.1.13 on 2021-12-29 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0042_auto_20211229_1619'),
        ('tickets', '0011_remove_approvalrule_assignees_display'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_relation', to='terminal.session')),
                ('ticket', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='session_relation', to='tickets.ticket')),
            ],
            options={'verbose_name': 'Ticket session relation'},
        ),
    ]
