# Generated by Django 5.2.15 on 2026-09-22 13:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_ticket_workflow_integration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow', name='is_system',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterModelOptions(
            name='workflownodeinstance',
            options={'default_permissions': (), 'ordering': ['date_created', 'id'], 'verbose_name': 'Workflow node instance'},
        ),
        migrations.AddField(
            model_name='workflow',
            name='cc_users',
            field=models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='CC users'),
        ),
    ]
