# Generated by Django 5.2.15 on 2026-09-23 08:25

import tickets.plugins.registry
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_workflow_cc_and_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='request_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Request parameters'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=tickets.plugins.registry.ticket_type_choices, default='general', max_length=64, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='type',
            field=models.CharField(choices=tickets.plugins.registry.ticket_type_choices, max_length=64, verbose_name='Type'),
        ),
    ]
