# Generated by Django 3.1.14 on 2022-02-28 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_auto_20220217_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperTicket',
            fields=[
            ],
            options={
                'verbose_name': 'Super ticket',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tickets.ticket',),
        ),
    ]
