# Generated by Django 3.1.14 on 2022-06-14 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_superticket'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('serial_num',)},
        ),
    ]
