# Generated by Django 3.1.14 on 2022-05-23 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0049_endpoint_redis_port'),
        ('assets', '0090_auto_20220412_1145'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0015_superticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='rel_snapshot',
            field=models.JSONField(default=dict, verbose_name='Relation snapshot'),
        ),
        migrations.CreateModel(
            name='ApplyCommandTicket',
            fields=[
                ('ticket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tickets.ticket')),
                ('apply_run_command', models.CharField(max_length=4096, verbose_name='Run command')),
                ('apply_from_cmd_filter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.commandfilter', verbose_name='From cmd filter')),
                ('apply_from_cmd_filter_rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.commandfilterrule', verbose_name='From cmd filter rule')),
                ('apply_from_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='terminal.session', verbose_name='Session')),
                ('apply_run_asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.asset', verbose_name='Run asset')),
                ('apply_run_system_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.systemuser', verbose_name='Run system user')),
                ('apply_run_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Run user')),
            ],
            options={
                'abstract': False,
            },
            bases=('tickets.ticket',),
        ),
    ]
