# Generated by Django 3.1.14 on 2022-06-06 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_auto_20220602_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='process_map',
        ),
    ]
