# Generated by Django 3.2.14 on 2022-08-16 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_applyapplicationticket_apply_actions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplyApplicationTicket',
        ),
    ]
