# Generated by Django 3.1.14 on 2022-05-31 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_auto_20220525_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='process_map',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='ticketassignee',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=64),
        ),
        migrations.AlterField(
            model_name='ticketstep',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=64, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='ticketstep',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending')], default='pending', max_length=16, verbose_name='Status'),
        ),
    ]
