# Generated by Django 3.1.14 on 2022-05-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_auto_20220531_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='applicant_display',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='ticketstep',
            name='status',
        ),
        migrations.AlterField(
            model_name='ticketstep',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='pending', max_length=64, verbose_name='State'),
        ),
    ]
