# Generated by Django 3.2.13 on 2022-09-21 10:14

from django.db import migrations, models


def migrate_remove_application_flow(apps, schema_editor):
    flow_model = apps.get_model('tickets', 'TicketFlow')
    flow_model.objects.filter(type='apply_application').delete()


class Migration(migrations.Migration):
    dependencies = [
        ('tickets', '0020_auto_20220817_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(
                choices=[('general', 'General'), ('login_confirm', 'Login confirm'), ('apply_asset', 'Apply for asset'),
                         ('login_asset_confirm', 'Login asset confirm'), ('command_confirm', 'Command confirm')],
                default='general', max_length=64, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='ticketflow',
            name='type',
            field=models.CharField(
                choices=[('general', 'General'), ('login_confirm', 'Login confirm'), ('apply_asset', 'Apply for asset'),
                         ('login_asset_confirm', 'Login asset confirm'), ('command_confirm', 'Command confirm')],
                default='general', max_length=64, verbose_name='Type'),
        ),
        migrations.RunPython(migrate_remove_application_flow),
    ]
