# Generated by Django 3.2.14 on 2022-12-06 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('acls', '0008_commandgroup_comment'),
        ('tickets', '0024_auto_20221121_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applycommandticket',
            name='apply_from_cmd_filter',
        ),
        migrations.RemoveField(
            model_name='applycommandticket',
            name='apply_from_cmd_filter_rule',
        ),
        migrations.AddField(
            model_name='applycommandticket',
            name='apply_from_cmd_filter_acl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='acls.commandfilteracl',
                                    verbose_name='Command filter acl'),
        ),
    ]
