# Generated by Django 3.2.16 on 2022-12-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0026_auto_20221220_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applycommandticket',
            name='apply_run_account',
            field=models.CharField(default='', max_length=128, verbose_name='Account'),
        ),
    ]
