# Generated by Django 3.2.16 on 2023-01-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0107_automation'),
        ('tickets', '0028_remove_app_tickets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applyassetticket',
            options={'verbose_name': 'Apply Asset Ticket'},
        ),
        migrations.AlterField(
            model_name='applyassetticket',
            name='apply_assets',
            field=models.ManyToManyField(to='assets.Asset', verbose_name='Asset'),
        ),
        migrations.AlterField(
            model_name='applyassetticket',
            name='apply_nodes',
            field=models.ManyToManyField(to='assets.Node', verbose_name='Node'),
        ),
    ]
