# Generated by Django 4.1.13 on 2025-05-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeakPasswords',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=1024, verbose_name='Password')),
            ],
            options={
                'db_table': 'passwords',
                'managed': False,
            },
        ),
    ]
