# Generated by Django 3.1.12 on 2021-09-01 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20210729_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='value',
            field=models.TextField(blank=True, null=True, verbose_name='Value'),
        ),
    ]
