# Generated by Django 3.1.12 on 2022-02-11 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_auto_20210901_1035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': 'System setting'},
        ),
    ]
