# Generated by Django 3.1.14 on 2022-06-06 09:45

from django.db import migrations


def migrate_terminal_razor_enabled(apps, schema_editor):
    setting_model = apps.get_model("settings", "Setting")
    s = setting_model.objects.filter(name='XRDP_ENABLED').first()
    if not s:
        return
    s.name = 'TERMINAL_RAZOR_ENABLED'
    s.save()


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_auto_20220310_0616'),
    ]

    operations = [
        migrations.RunPython(migrate_terminal_razor_enabled),
    ]
