# Generated by Django 3.2.14 on 2022-10-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_remove_setting_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='category',
            field=models.CharField(default='default', max_length=128, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='encrypted',
            field=models.BooleanField(default=False, verbose_name='Encrypted'),
        ),
    ]
