# Generated by Django 3.1.14 on 2022-03-11 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_auto_20220310_2006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setting',
            options={'permissions': [('change_basic', 'Can change basic setting'), ('change_email', 'Can change email setting'), ('change_auth', 'Can change auth setting'), ('change_systemmsgsubscription', 'Can sys msg sub setting'), ('change_sms', 'Can change sms setting'), ('change_security', 'Can change security setting'), ('change_clean', 'Can change clean setting'), ('change_interface', 'Can change interface setting'), ('change_license', 'Can change license setting'), ('change_terminal', 'Can change terminal setting'), ('change_other', 'Can change other setting')], 'verbose_name': 'System setting'},
        ),
    ]
