# Generated by Django 4.1.10 on 2023-10-19 07:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('settings', '0009_alter_cas_username_attribute'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setting',
            options={'permissions': [
                ('change_email', 'Can change email setting'),
                ('change_auth', 'Can change auth setting'),
                ('change_ops', 'Can change auth ops'),
                ('change_ticket', 'Can change auth ticket'),
                ('change_announcement', 'Can change auth announcement'),
                ('change_vault', 'Can change vault setting'),
                ('change_chatai', 'Can change chat ai setting'),
                ('change_systemmsgsubscription', 'Can change system msg sub setting'),
                ('change_sms', 'Can change sms setting'),
                ('change_security', 'Can change security setting'),
                ('change_clean', 'Can change clean setting'),
                ('change_interface', 'Can change interface setting'),
                ('change_license', 'Can change license setting'),
                ('change_terminal', 'Can change terminal setting'),
                ('change_other', 'Can change other setting')
            ], 'verbose_name': 'System setting'},
        ),
    ]
