# Generated by Django 2.2.10 on 2020-07-01 08:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscontrol',
            name='date_from',
            field=models.DateTimeField(verbose_name='Date from'),
        ),
        migrations.AlterField(
            model_name='accesscontrol',
            name='date_to',
            field=models.DateTimeField(verbose_name='Date to'),
        ),
        migrations.AlterField(
            model_name='accesscontrol',
            name='ips',
            field=models.CharField(max_length=512, verbose_name='IPs'),
        ),
        migrations.AlterField(
            model_name='accesscontrol',
            name='name',
            field=models.CharField(max_length=512, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='accesscontrol',
            name='users',
            field=models.ManyToManyField(related_name='login_policies', to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
    ]
