# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-19 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idc',
            name='network',
        ),
        migrations.AddField(
            model_name='idc',
            name='extranet',
            field=models.TextField(blank=True, verbose_name='Extranet'),
        ),
        migrations.AddField(
            model_name='idc',
            name='intranet',
            field=models.TextField(blank=True, verbose_name='Intranet'),
        ),
        migrations.AlterField(
            model_name='assetgroup',
            name='system_users',
            field=models.ManyToManyField(blank=True, related_name='system_users', to='assets.SystemUser'),
        ),
    ]
