# Generated by Django 1.11 on 2018-01-09 15:31
from __future__ import unicode_literals

from django.db import migrations


def create_internal_platform(apps, schema_editor):
    model = apps.get_model("assets", "Platform")
    db_alias = schema_editor.connection.alias
    type_platforms = (
        ('Linux', 'Linux', None),
        ('Unix', 'Unix', None),
        ('MacOS', 'MacOS', None),
        ('BSD', 'BSD', None),
        ('Windows', 'Windows', None),
        ('Windows-RDP', 'Windows', {'security': 'rdp'}),
        ('Windows-TLS', 'Windows', {'security': 'tls'}),
        ('AIX', 'Unix', None),
        ('Other', 'Other', None),
    )
    for name, base, meta in type_platforms:
        model.objects.using(db_alias).update_or_create(
            name=name, defaults=dict(
                base=base, internal=True, meta=meta
            )
        )


class Migration(migrations.Migration):
    dependencies = [
        ('assets', '0002_auto_20180105_1807'),
    ]

    operations = [
        migrations.RunPython(create_internal_platform),
    ]
