# Generated by Django 4.1.13 on 2024-11-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0007_baseautomation_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseautomation",
            name="date_last_run",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date last run"
            ),
        ),
        migrations.AlterField(
            model_name="baseautomation",
            name="crontab",
            field=models.CharField(
                blank=True, default="", max_length=128, verbose_name="Crontab"
            ),
        ),
    ]
