# Generated by Django 4.1.13 on 2024-12-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0010_alter_automationexecution_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="automationexecution",
            name="status",
            field=models.CharField(
                choices=[
                    ("ready", "Ready"),
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                    ("error", "Error"),
                    ("canceled", "Canceled"),
                ],
                default="pending",
                max_length=16,
                verbose_name="Status",
            ),
        ),
    ]
