# Generated by Django 4.1.13 on 2025-03-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_auto_20241204_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseautomation',
            name='last_execution_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last execution date'),
        ),
    ]
