# Generated by Django 4.1.13 on 2025-03-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_baseautomation_last_execution_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationexecution',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Duration'),
        ),
    ]
