# Generated by Django 4.1.13 on 2025-03-13 09:14

from django.db import migrations, models


def migrate_execution_type(apps, schema_editor):
    execution_model = apps.get_model('assets', 'AutomationExecution')
    execution_objs = []
    for execution in execution_model.objects.all():
        snapshot = execution.snapshot
        execution.type = snapshot.get('type', '')
        execution_objs.append(execution)
    execution_model.objects.bulk_update(execution_objs, ['type'])


class Migration(migrations.Migration):
    dependencies = [
        ('assets', '0014_alter_automationexecution_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationexecution',
            name='type',
            field=models.CharField(default='', max_length=16, verbose_name='Type'),
        ),
        migrations.RunPython(migrate_execution_type)
    ]
