# Generated by Django 4.1.13 on 2025-04-18 08:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0017_auto_20250407_1124"),
    ]

    operations = [
        migrations.RenameField(
            model_name="platform",
            old_name="domain_enabled",
            new_name="gateway_enabled",
        ),
        migrations.RenameModel(
            old_name="Domain",
            new_name="Zone",
        ),
        migrations.RenameField(
            model_name="asset",
            old_name="zone",
            new_name="zone",
        ),
    ]
