# Generated by Django 4.1.13 on 2025-04-03 09:59

from django.db import migrations

from assets.const.gpt import create_or_update_chatx_resources


def migrate_chat_platform_asset_account(apps, schema_editor):
    create_or_update_chatx_resources()


class Migration(migrations.Migration):
    dependencies = [
        ('assets', '0018_rename_domain_zone'),
    ]

    operations = [
        migrations.RunPython(migrate_chat_platform_asset_account)
    ]