# Generated by Django 4.1.13 on 2025-11-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0019_alter_asset_connectivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloud',
            name='namespace',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Namespace'),
        ),
    ]
