# Generated by Django 4.1.13 on 2025-12-16 09:14

from django.db import migrations, models, transaction
import django.db.models.deletion


def log(msg=''):
    print(f'    -> {msg}')


def ensure_asset_single_node(apps, schema_editor):
    print('')
    log('Checking that all assets are linked to only one node...')
    Asset = apps.get_model('assets', 'Asset')
    Through = Asset.nodes.through

    assets_count_multi_nodes = Through.objects.values('asset_id').annotate(
        node_count=models.Count('node_id')
    ).filter(node_count__gt=1).count()

    if assets_count_multi_nodes > 0:
        raise Exception(
            f'There are {assets_count_multi_nodes} assets associated with more than one node. '
            'Please ensure each asset is linked to only one node before applying this migration.'
        )
    else:
        log('All assets are linked to only one node. Proceeding with the migration.')


def ensure_asset_has_node(apps, schema_editor):
    log('Checking that all assets are linked to at least one node...')
    Asset = apps.get_model('assets', 'Asset')
    Through = Asset.nodes.through

    asset_count = Asset.objects.count()
    through_asset_count = Through.objects.values('asset_id').count()

    assets_count_without_node = asset_count - through_asset_count
    
    if assets_count_without_node > 0:
        raise Exception(
            f'Some assets ({assets_count_without_node}) are not associated with any node. '
            'Please ensure all assets are linked to a node before applying this migration.'
        )
    else:
        log('All assets are linked to a node. Proceeding with the migration.')


def migrate_asset_node_id_field(apps, schema_editor):
    log('Migrating node_id field for all assets...')

    Asset = apps.get_model('assets', 'Asset')
    Through = Asset.nodes.through

    assets = Asset.objects.filter(node_id__isnull=True)
    log (f'Found {assets.count()} assets to migrate.')

    asset_node_mapper = {
        str(asset_id): str(node_id)
        for asset_id, node_id in Through.objects.values_list('asset_id', 'node_id')
    }
    # 测试
    asset_node_mapper.pop(None, None)  # Remove any entries with None keys

    for asset in assets:
        node_id = asset_node_mapper.get(str(asset.id))
        if not node_id:
            raise Exception(
                f'Asset (ID: {asset.id}) is not associated with any node. '
                'Cannot migrate node_id field.'
            )
        asset.node_id = node_id

    with transaction.atomic():
        total = len(assets)
        batch_size = 5000
        
        for i in range(0, total, batch_size):
            batch = assets[i:i+batch_size]
            start = i + 1
            end = min(i + batch_size, total)
            
            for asset in batch:
                asset.save(update_fields=['node_id'])
            
            log(f"Migrated {start}-{end}/{total} assets")

        count = Asset.objects.filter(node_id__isnull=True).count()
        if count > 0:
            log('Warning: Some assets still have null node_id after migration.')
            raise Exception('Migration failed: Some assets have null node_id.')

    count = Asset.objects.filter(node_id__isnull=False).count()
    log(f'Successfully migrated node_id for {count} assets.')


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0019_alter_asset_connectivity'),
    ]

    operations = [
        migrations.RunPython(
            ensure_asset_single_node,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.RunPython(
            ensure_asset_has_node,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.AddField(
            model_name='asset',
            name='node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='direct_assets', to='assets.node', verbose_name='Node'),
        ),
        migrations.RunPython(
            migrate_asset_node_id_field,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='asset',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='direct_assets', to='assets.node', verbose_name='Node'),
        ),
    ]
