# Generated by Django 2.1.4 on 2018-12-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0023_auto_20181016_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='protocol',
            field=models.CharField(choices=[('ssh', 'ssh'), ('rdp', 'rdp'), ('telnet', 'telnet (beta)'), ('vnc', 'vnc')], default='ssh', max_length=128, verbose_name='Protocol'),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='protocol',
            field=models.CharField(choices=[('ssh', 'ssh'), ('rdp', 'rdp'), ('telnet', 'telnet (beta)'), ('vnc', 'vnc')], default='ssh', max_length=16, verbose_name='Protocol'),
        ),
    ]
