# Generated by Django 2.1.7 on 2019-02-21 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0024_auto_20181219_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commandfilter',
            options={'verbose_name': 'Command filter'},
        ),
        migrations.AlterModelOptions(
            name='commandfilterrule',
            options={'ordering': ('-priority', 'action'), 'verbose_name': 'Command filter rule'},
        ),
    ]
