# Generated by Django 2.1.7 on 2019-05-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0026_auto_20190325_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='ip',
            field=models.CharField(db_index=True, max_length=128, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='public_ip',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Public IP'),
        ),
    ]
