# Generated by Django 2.1.7 on 2019-05-22 02:58

import uuid

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('assets', '0027_auto_20190521_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name',
                 models.CharField(choices=[('ssh', 'ssh'), ('rdp', 'rdp'), ('telnet', 'telnet (beta)'), ('vnc', 'vnc')],
                                  default='ssh', max_length=16, verbose_name='Name')),
                ('port', models.IntegerField(default=22, validators=[django.core.validators.MaxValueValidator(65535),
                                                                     django.core.validators.MinValueValidator(0)],
                                             verbose_name='Port')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='protocols',
            field=models.ManyToManyField(to='assets.Protocol',
                                         verbose_name='Protocol'),
        ),
    ]
