# Generated by Django 2.1.7 on 2019-06-24 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0032_auto_20190624_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminuser',
            old_name='_private_key',
            new_name='private_key',
        ),
        migrations.RenameField(
            model_name='adminuser',
            old_name='_public_key',
            new_name='public_key',
        ),
        migrations.RenameField(
            model_name='authbook',
            old_name='_private_key',
            new_name='private_key',
        ),
        migrations.RenameField(
            model_name='authbook',
            old_name='_public_key',
            new_name='public_key',
        ),
        migrations.RenameField(
            model_name='gateway',
            old_name='_private_key',
            new_name='private_key',
        ),
        migrations.RenameField(
            model_name='gateway',
            old_name='_public_key',
            new_name='public_key',
        ),
        migrations.RenameField(
            model_name='systemuser',
            old_name='_private_key',
            new_name='private_key',
        ),
        migrations.RenameField(
            model_name='systemuser',
            old_name='_public_key',
            new_name='public_key',
        ),
        migrations.RenameField(
            model_name='adminuser',
            old_name='_password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='authbook',
            old_name='_password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='gateway',
            old_name='_password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='systemuser',
            old_name='_password',
            new_name='password',
        ),
    ]
