# Generated by Django 2.1.7 on 2019-07-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0036_auto_20190716_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='_become_pass',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
