# Generated by Django 2.1.7 on 2019-09-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0037_auto_20190724_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='protocol',
            field=models.CharField(choices=[('ssh', 'ssh'), ('rdp', 'rdp'), ('telnet', 'telnet'), ('vnc', 'vnc')], default='ssh', max_length=128, verbose_name='Protocol'),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='protocol',
            field=models.CharField(choices=[('ssh', 'ssh'), ('rdp', 'rdp'), ('telnet', 'telnet'), ('vnc', 'vnc')], default='ssh', max_length=16, verbose_name='Protocol'),
        ),
    ]
