# Generated by Django 2.2.5 on 2019-11-14 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0042_favoriteasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='gathereduser',
            name='date_last_login',
            field=models.DateTimeField(null=True, verbose_name='Date last login'),
        ),
        migrations.AddField(
            model_name='gathereduser',
            name='ip_last_login',
            field=models.CharField(default='', max_length=39, verbose_name='IP last login'),
        ),
    ]
