# Generated by Django 2.1.11 on 2019-12-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0045_auto_20191206_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='protocol',
            field=models.CharField(choices=[('ssh', 'ssh'), ('rdp', 'rdp'), ('telnet', 'telnet'), ('vnc', 'vnc'), ('mysql', 'mysql')], default='ssh', max_length=16, verbose_name='Protocol'),
        ),
    ]
