# Generated by Django 2.2.7 on 2020-01-06 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0046_auto_20191218_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('assets.authbook',),
        ),
    ]
