# Generated by Django 2.2.7 on 2019-12-30 07:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0047_assetuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authbook',
            name='is_active',
        ),
        migrations.AddField(
            model_name='systemuser',
            name='username_same_with_user',
            field=models.BooleanField(default=False, verbose_name='Username same with user'),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='groups',
            field=models.ManyToManyField(blank=True, to='users.UserGroup',
                                         verbose_name='User groups'),
        ),
    ]
