# Generated by Django 2.2.7 on 2020-01-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0048_auto_20191230_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='sftp_root',
            field=models.CharField(default='tmp', max_length=128, verbose_name='SFTP Root'),
        ),
    ]
