# Generated by Django 2.2.13 on 2020-08-07 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0053_auto_20200723_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='token',
            field=models.TextField(default='', verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='protocol',
            field=models.CharField(choices=[('ssh', 'ssh'), ('rdp', 'rdp'), ('telnet', 'telnet'), ('vnc', 'vnc'), ('mysql', 'mysql'), ('k8s', 'k8s')], default='ssh', max_length=16, verbose_name='Protocol'),
        ),
    ]
