# Generated by Django 2.2.13 on 2020-08-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0054_auto_20200807_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='home',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='Home'),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='system_groups',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='System groups'),
        ),
    ]
