# Generated by Django 2.2.13 on 2020-08-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0055_auto_20200811_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='key',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Key'),
        ),
    ]
