# Generated by Django 2.2.13 on 2020-10-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0057_fill_node_value_assets_amount_and_parent_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['-date_created'], 'verbose_name': 'Asset'},
        ),
        migrations.AlterField(
            model_name='asset',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='commandfilterrule',
            name='content',
            field=models.TextField(help_text='One line one command', verbose_name='Content'),
        ),
    ]
