# Generated by Django 2.2.13 on 2020-10-23 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0057_fill_node_value_assets_amount_and_parent_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='left',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='node',
            name='parent',
            field=models.ForeignKey(db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='assets.Node'),
        ),
        migrations.AddField(
            model_name='node',
            name='right',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='asset',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='commandfilterrule',
            name='content',
            field=models.TextField(help_text='One line one command', verbose_name='Content'),
        ),
    ]
