# Generated by Django 2.2.13 on 2020-10-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0058_auto_20201023_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='ad_domain',
            field=models.CharField(default='', max_length=256),
        ),
    ]
