# Generated by Django 2.2.13 on 2020-11-16 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0060_node_full_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='node',
            options={'ordering': ['value'], 'verbose_name': 'Node'},
        ),
    ]
