# Generated by Django 3.1 on 2020-12-03 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0063_migrate_default_node_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='node',
            options={'ordering': ['parent_key', 'value'], 'verbose_name': 'Node'},
        ),
    ]
