# Generated by Django 3.1 on 2021-01-20 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0064_auto_20201203_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain',
            options={'ordering': ('name',), 'verbose_name': 'Domain'},
        ),
        migrations.CreateModel(
            name='NodeAssetRelatedRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_count', models.IntegerField(default=0)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes_related_records', to='assets.asset')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets_related_records', to='assets.node')),
            ],
        ),
    ]
