# Generated by Django 3.1 on 2021-01-21 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0064_auto_20201203_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain',
            options={'ordering': ('name',), 'verbose_name': 'Domain'},
        ),
    ]
