# Generated by Django 3.1 on 2021-01-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0065_auto_20210120_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeAssetRelatedRecordProxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=64)),
                ('node_id', models.CharField(max_length=64)),
                ('related_count', models.IntegerField(db_index=True, default=0)),
            ],
            options={
                'db_table': 'assets_nodeassetrelatedrecord',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='node',
            name='all_assets',
            field=models.ManyToManyField(related_name='all_nodes', through='assets.NodeAssetRelatedRecord', to='assets.Asset'),
        ),
        migrations.AlterField(
            model_name='nodeassetrelatedrecord',
            name='related_count',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
