# Generated by Django 3.1 on 2021-02-04 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0065_auto_20210121_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='assets_amount',
        ),
    ]
