# Generated by Django 3.1 on 2021-02-08 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0065_auto_20210121_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['hostname'], 'verbose_name': 'Asset'},
        ),
    ]
