# Generated by Django 3.1 on 2021-02-02 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0066_auto_20210130_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodeassetrelatedrecord',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='nodeassetrelatedrecord',
            name='node',
        ),
        migrations.DeleteModel(
            name='NodeAssetRelatedRecordProxy',
        ),
        migrations.RemoveField(
            model_name='node',
            name='all_assets',
        ),
        migrations.RemoveField(
            model_name='node',
            name='assets_amount',
        ),
        migrations.DeleteModel(
            name='NodeAssetRelatedRecord',
        ),
    ]
