# Generated by Django 3.1 on 2021-03-12 06:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0067_auto_20210311_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='priority',
            field=models.IntegerField(default=81, help_text='1-100, the lower the value will be match first', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Priority'),
        ),
    ]
