# Generated by Django 3.1 on 2021-04-26 07:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0069_change_node_key0_to_key1'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandfilterrule',
            name='reviewers',
            field=models.ManyToManyField(blank=True, related_name='review_cmd_filter_rules', to=settings.AUTH_USER_MODEL, verbose_name='Reviewers'),
        ),
        migrations.AlterField(
            model_name='commandfilterrule',
            name='action',
            field=models.IntegerField(choices=[(0, 'Deny'), (1, 'Allow'), (2, 'Reconfirm')], default=0, verbose_name='Action'),
        ),
    ]
