# Generated by Django 3.1 on 2021-04-26 11:32

from django.db import migrations, models
import django.db.models.deletion


def expire_node_assets_mapping(apps, schema_editor):
    from assets.signals_handler.node_assets_mapping import expire_node_assets_mapping_for_memory

    Organization = apps.get_model('orgs', 'Organization')
    org_ids = Organization.objects.all().values_list('id', flat=True)
    org_ids = [*org_ids, '00000000-0000-0000-0000-000000000000']

    print()
    for org_id in org_ids:
        print(f'--> Expire node assets mapping: org_id={org_id}')
        expire_node_assets_mapping_for_memory(org_id)


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0010_auto_20210219_1241'),
        ('assets', '0069_change_node_key0_to_key1'),
    ]

    operations = [
        migrations.RunPython(expire_node_assets_mapping)
    ]
