# Generated by Django 3.1.6 on 2021-06-04 16:46

from django.db import migrations, models, transaction


def migrate_admin_user_to_system_user(apps, schema_editor):
    admin_user_model = apps.get_model("assets", "AdminUser")
    system_user_model = apps.get_model("assets", "SystemUser")
    db_alias = schema_editor.connection.alias

    admin_users = admin_user_model.objects.using(db_alias).all()
    print()
    for admin_user in admin_users:
        kwargs = {}
        for attr in [
            'id', 'org_id', 'username', 'password', 'private_key', 'public_key',
            'comment', 'date_created', 'date_updated', 'created_by',
        ]:
            value = getattr(admin_user, attr)
            kwargs[attr] = value

        name = admin_user.name
        exist = system_user_model.objects.using(db_alias).filter(
            name=admin_user.name, org_id=admin_user.org_id
        ).exists()
        if exist:
            name = admin_user.name + '_' + str(admin_user.id)[:5]
        kwargs.update({
            'name': name,
            'type': 'admin',
            'protocol': 'ssh',
            'auto_push': False,
        })

        with transaction.atomic():
            s = system_user_model(**kwargs)
            s.save()
            print("  Migrate admin user to system user: {} => {}".format(admin_user.name, s.name))
            assets = admin_user.assets.all()
            s.assets.set(assets)


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0070_auto_20210426_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='type',
            field=models.CharField(choices=[('common', 'Common user'), ('admin', 'Admin user')], default='common', max_length=16, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='login_mode',
            field=models.CharField(choices=[('auto', 'Automatic managed'), ('manual', 'Manually input')], default='auto', max_length=10, verbose_name='Login mode'),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='protocol',
            field=models.CharField(choices=[('ssh', 'SSH'), ('rdp', 'RDP'), ('telnet', 'Telnet'), ('vnc', 'VNC'), ('mysql', 'MySQL'), ('oracle', 'Oracle'), ('mariadb', 'MariaDB'), ('postgresql', 'PostgreSQL'), ('k8s', 'K8S')], default='ssh', max_length=16, verbose_name='Protocol'),
        ),
        migrations.RunPython(migrate_admin_user_to_system_user)
    ]
