# Generated by Django 3.1.6 on 2021-06-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0070_auto_20210426_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='type',
            field=models.CharField(choices=[('admin', 'Admin user'), ('devops', 'Devops user'), ('common', 'Common user')], default='common', max_length=16, verbose_name='Type'),
        ),
    ]
