# Generated by Django 3.1.6 on 2021-06-04 17:03

import assets.models.base
import common.fields.model
import django.core.validators
from django.db import migrations, models, transaction
import django.db.models.deletion
import uuid


def migrate_old_authbook(apps, schema_editor):
    authbook_model = apps.get_model("assets", "AuthBook")
    history_model = apps.get_model("assets", "AuthBookHistory")
    db_alias = schema_editor.connection.alias

    old_authbook = authbook_model.objects.using(db_alias).all().filter(is_latest=False)
    for old in old_authbook:
        history = history_model()
        for attr in [
            'org_id', 'name', 'username', 'password', 'private_key', 'public_key',
            'comment', 'date_created', 'date_update', 'created_by', 'version', 'asset'
        ]:
            setattr(history, attr, getattr(old, attr))
        history.authbook = old

        with transaction.atomic():
            history.save()
            old.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0071_systemuser_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthBookHistory',
            fields=[
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('username', models.CharField(blank=True, db_index=True, max_length=128, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_@\\-\\.]*$', 'Special char not allowed')], verbose_name='Username')),
                ('password', common.fields.model.EncryptCharField(blank=True, max_length=256, null=True, verbose_name='Password')),
                ('private_key', common.fields.model.EncryptTextField(blank=True, null=True, verbose_name='SSH private key')),
                ('public_key', common.fields.model.EncryptTextField(blank=True, null=True, verbose_name='SSH public key')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('created_by', models.CharField(max_length=128, null=True, verbose_name='Created by')),
                ('version', models.IntegerField(default=1, verbose_name='Version')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset', verbose_name='Asset')),
                ('authbook', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='assets.authbook')),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date joined')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, assets.models.base.AuthMixin, assets.models.base.ConnectivityMixin),
        ),
    ]
