# Generated by Django 3.1.6 on 2021-06-05 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0072_migrate_admin_user_to_system_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='admin_user',
            new_name='_admin_user',
        ),
    ]
