# Generated by Django 3.1.6 on 2021-06-04 17:03

from django.db import migrations,  transaction


def migrate_old_authbook(apps, schema_editor):
    authbook_model = apps.get_model("assets", "AuthBook")
    history_model = apps.get_model("assets", "AuthBookHistory")
    db_alias = schema_editor.connection.alias

    old_authbook = authbook_model.objects.using(db_alias).all().filter(is_latest=False)
    print()
    for old in old_authbook:
        history = history_model()
        for attr in [
            'org_id', 'name', 'username', 'password', 'private_key', 'public_key',
            'comment', 'date_created', 'date_updated', 'created_by', 'version', 'asset'
        ]:
            setattr(history, attr, getattr(old, attr))
        history.authbook = old

        with transaction.atomic():
            print("Migrate old auth book to history table: {}@{}".format(history.username, history.asset.ip))
            history.save()
            old.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0072_authbookhistory'),
    ]

    operations = [
        migrations.RunPython(migrate_old_authbook)
    ]
