# Generated by Django 3.1.6 on 2021-06-06 03:42

from django.db import migrations, models, transaction
import django.db.models.deletion


def migrate_system_assets_to_authbook(apps, schema_editor):
    system_user_model = apps.get_model("assets", "SystemUser")
    system_user_asset_model = system_user_model.assets.through
    authbook_model = apps.get_model('assets', 'AuthBook')

    while True:
        systemuser_asset_relations = system_user_asset_model.objects.all()[:20]
        if not systemuser_asset_relations:
            break
        authbooks = []
        relations_ids = []
        for i in systemuser_asset_relations:
            authbooks.append(authbook_model(asset=i.asset, systemuser=i.systemuser))
            relations_ids.append(i.id)
        with transaction.atomic():
            print("  Migrate system user assets relations: ", len(relations_ids))
            authbook_model.objects.bulk_create(authbooks, ignore_conflicts=True)
            system_user_asset_model.objects.filter(id__in=relations_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0072_historicalauthbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='authbook',
            name='systemuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.systemuser', verbose_name='System user'),
        ),
        migrations.AddField(
            model_name='historicalauthbook',
            name='systemuser',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='assets.systemuser', verbose_name='System user'),
        ),
        migrations.AlterUniqueTogether(
            name='authbook',
            unique_together={('username', 'asset', 'systemuser')},
        ),
        migrations.RunPython(migrate_system_assets_to_authbook)
    ]
