# Generated by Django 3.1.6 on 2021-06-04 18:31

from django.db import migrations
from django.db import transaction


def migrate_admin_user_to_system_user(apps, schema_editor):
    admin_user_model = apps.get_model("assets", "AdminUser")
    system_user_model = apps.get_model("assets", "SystemUser")
    db_alias = schema_editor.connection.alias

    admin_users = admin_user_model.objects.using(db_alias).all()
    print()
    for admin_user in admin_users:
        kwargs = {}
        for attr in [
            'id', 'org_id', 'username', 'password', 'private_key', 'public_key',
            'comment', 'date_created', 'date_updated', 'created_by',
        ]:
            value = getattr(admin_user, attr)
            kwargs[attr] = value

        protocol = 'ssh'
        if admin_user.username.lower() == 'administrator':
            protocol = 'rdp'
        kwargs.update({
            'name': admin_user.name + '(admin_user_' + str(admin_user.id)[:7] + ')',
            'type': 'admin',
            'protocol': protocol,
            'auto_push': False,
        })

        with transaction.atomic():
            s = system_user_model(**kwargs)
            s.save()
            print("Migrate admin user to system user: {} => {}".format(admin_user.name, s.name))
            assets = admin_user.assets.all()
            s.assets.set(assets)


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0073_auto_20210605_0116'),
    ]

    operations = [
        migrations.RunPython(migrate_admin_user_to_system_user)
    ]
