# Generated by Django 3.1 on 2021-07-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0074_remove_systemuser_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='connectivity',
            field=models.CharField(choices=[('-', 'Unknown'), ('ok', 'Ok'), ('err', 'Error')], default='-', max_length=16, verbose_name='Connectivity'),
        ),
        migrations.AddField(
            model_name='asset',
            name='date_verified',
            field=models.DateTimeField(null=True, verbose_name='Date verified'),
        ),
        migrations.AddField(
            model_name='authbook',
            name='connectivity',
            field=models.CharField(choices=[('-', 'Unknown'), ('ok', 'Ok'), ('err', 'Error')], default='-', max_length=16, verbose_name='Connectivity'),
        ),
        migrations.AddField(
            model_name='authbook',
            name='date_verified',
            field=models.DateTimeField(null=True, verbose_name='Date verified'),
        ),
        migrations.AddField(
            model_name='historicalauthbook',
            name='connectivity',
            field=models.CharField(choices=[('-', 'Unknown'), ('ok', 'Ok'), ('err', 'Error')], default='-', max_length=16, verbose_name='Connectivity'),
        ),
        migrations.AddField(
            model_name='historicalauthbook',
            name='date_verified',
            field=models.DateTimeField(null=True, verbose_name='Date verified'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='protocol',
            field=models.CharField(choices=[('ssh', 'SSH'), ('rdp', 'RDP'), ('telnet', 'Telnet'), ('vnc', 'VNC')], default='ssh', max_length=128, verbose_name='Protocol'),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='protocol',
            field=models.CharField(choices=[('ssh', 'SSH')], default='ssh', max_length=16, verbose_name='Protocol'),
        ),
    ]
