# Generated by Django 3.1.6 on 2021-06-04 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0074_auto_20210605_0231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='admin_user',
        ),
    ]
