# Generated by Django 3.1.6 on 2021-07-12 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0075_auto_20210705_1759'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssetUser',
        ),
    ]
