# Generated by Django 3.1.6 on 2021-06-06 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0075_auto_20210605_2350'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='authbook',
        #     name='system_user',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.systemuser', verbose_name='System user'),
        # ),
        # migrations.AddField(
        #     model_name='historicalauthbook',
        #     name='system_user',
        #     field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='assets.systemuser', verbose_name='System user'),
        # ),
    ]
