# Generated by Django 3.1.6 on 2021-06-04 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0075_remove_asset_admin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='authbook',
            name='system_user',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='assets.systemuser'),
        ),
        migrations.AddField(
            model_name='authbookhistory',
            name='system_user',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='assets.systemuser'),
        ),
    ]
