# Generated by Django 3.1.6 on 2021-06-06 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0076_auto_20210606_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemuser',
            name='assets',
        ),
    ]
