# Generated by Django 3.1.6 on 2021-08-18 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_applicationuser'),
        ('assets', '0076_delete_assetuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='authbook',
            name='database',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.application', verbose_name='Database'),
        ),
        migrations.AddField(
            model_name='historicalauthbook',
            name='database',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='applications.application', verbose_name='Database'),
        ),
        migrations.AlterField(
            model_name='authbook',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.asset', verbose_name='Asset'),
        ),
    ]
