# Generated by Django 3.1.6 on 2021-06-04 19:16

from django.db import migrations


def migrate_system_user_relation(apps, schema_editor):
    system_user_model = apps.get_model("assets", "SystemUser")
    db_alias = schema_editor.connection.alias

    authbook = apps.get_model('assets', 'AuthBook')
    system_users = system_user_model.objects.using(db_alias).all()
    for s in system_users:
        assets = s.assets.all()

    print()


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0076_auto_20210605_0314'),
    ]

    operations = [
    ]
