# Generated by Django 3.1.6 on 2021-06-06 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0075_auto_20210605_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemuser',
            name='assets',
        ),
    ]
