# Generated by Django 3.1.13 on 2021-10-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0077_auto_20211012_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='username',
            field=models.CharField(blank=True, db_index=True, max_length=128, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='authbook',
            name='username',
            field=models.CharField(blank=True, db_index=True, max_length=128, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='username',
            field=models.CharField(blank=True, db_index=True, max_length=128, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='historicalauthbook',
            name='username',
            field=models.CharField(blank=True, db_index=True, max_length=128, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='username',
            field=models.CharField(blank=True, db_index=True, max_length=128, verbose_name='Username'),
        ),
    ]
