# Generated by Django 3.1.12 on 2022-02-11 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0077_auto_20211130_1037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['hostname'], 'permissions': [('test_assetconnectivity', 'Can test asset connectivity'), ('push_assetsystemuser', 'Can push system user to asset')], 'verbose_name': 'Asset'},
        ),
        migrations.AlterModelOptions(
            name='authbook',
            options={'permissions': [('view_assetaccountsecret', 'Can view asset account secret'), ('change_assetaccountsecret', 'Can change asset account secret')], 'verbose_name': 'AuthBook'},
        ),
    ]
