# Generated by Django 3.1.6 on 2021-06-06 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0078_auto_20210606_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='assets',
            field=models.ManyToManyField(blank=True, through='assets.AuthBook', to='assets.Asset', verbose_name='Assets'),
        ),
    ]
