# Generated by Django 3.1.13 on 2021-11-04 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0079_auto_20211102_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='su_enabled',
            field=models.BooleanField(default=False, verbose_name='Enable switch user'),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='su_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_users', to='assets.systemuser', verbose_name='Switch from'),
        ),
    ]
