# Generated by Django 3.1.6 on 2021-06-06 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0079_auto_20210606_1153'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='authbook',
            unique_together={('asset', 'system_user')},
        ),
    ]
