# Generated by Django 3.1.6 on 2021-06-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0079_auto_20210606_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='type',
            field=models.CharField(choices=[('common', 'Common user'), ('dynamic', 'Dynamic user'), ('admin', 'Admin user')], default='common', max_length=16, verbose_name='Type'),
        ),
        migrations.AlterUniqueTogether(
            name='authbook',
            unique_together={('username', 'asset', 'systemuser')},
        ),
    ]
