# Generated by Django 3.1.13 on 2021-11-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0080_auto_20211104_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='storage_type',
            field=models.CharField(choices=[('db', 'DB storage'), ('vault', 'Vault storage'), ('pam', 'Pam storage')], default='db', max_length=64, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='authbook',
            name='storage_type',
            field=models.CharField(choices=[('db', 'DB storage'), ('vault', 'Vault storage'), ('pam', 'Pam storage')], default='db', max_length=64, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='gateway',
            name='storage_type',
            field=models.CharField(choices=[('db', 'DB storage'), ('vault', 'Vault storage'), ('pam', 'Pam storage')], default='db', max_length=64, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='historicalauthbook',
            name='storage_type',
            field=models.CharField(choices=[('db', 'DB storage'), ('vault', 'Vault storage'), ('pam', 'Pam storage')], default='db', max_length=64, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='storage_type',
            field=models.CharField(choices=[('db', 'DB storage'), ('vault', 'Vault storage'), ('pam', 'Pam storage')], default='db', max_length=64, verbose_name='Type'),
        ),
    ]
