# Generated by Django 3.1.13 on 2021-12-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0083_auto_20211215_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='su_extra',
            field=models.CharField(max_length=128, null=True, verbose_name='Switch Extra'),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='su_type',
            field=models.CharField(choices=[('su', 'su'), ('enable', 'enable'), ('other', 'other')], default='su', max_length=16, verbose_name='Switch Type'),
        ),
    ]
