# Generated by Django 3.1.13 on 2022-02-08 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0084_auto_20220112_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandfilterrule',
            name='ignore_case',
            field=models.BooleanField(default=True, verbose_name='Ignore case'),
        ),
    ]
