# Generated by Django 3.1.13 on 2022-02-17 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0085_commandfilterrule_ignore_case'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['hostname'], 'permissions': [('test_assetconnectivity', 'Can test asset connectivity'), ('push_assetsystemuser', 'Can push system user to asset')], 'verbose_name': 'Asset'},
        ),
        migrations.AlterModelOptions(
            name='authbook',
            options={'permissions': [('view_assetaccountsecret', 'Can view asset account secret'), ('change_assetaccountsecret', 'Can change asset account secret')], 'verbose_name': 'AuthBook'},
        ),
        migrations.AlterModelOptions(
            name='label',
            options={'verbose_name': 'Label'},
        ),
    ]
