# Generated by Django 3.1.14 on 2022-04-12 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0089_auto_20220310_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='number',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Asset number'),
        ),
    ]
