# Generated by Django 3.1.14 on 2022-04-01 07:58

from django.db import migrations, models
import django.db.models.deletion


def migrate_to_host(apps, schema_editor):
    asset_model = apps.get_model("assets", "Asset")
    host_model = apps.get_model("assets", 'Host')
    db_alias = schema_editor.connection.alias

    created = 0
    batch_size = 1000

    while True:
        start = created
        end = created + batch_size
        assets = asset_model.objects.using(db_alias).all()[start:end]
        if not assets:
            break

        hosts = [host_model(asset_ptr=asset) for asset in assets]
        host_model.objects.using(db_alias).bulk_create(hosts, ignore_conflicts=True)
        created += len(hosts)


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0090_add_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='asset_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.asset'),
        ),
        migrations.RunPython(migrate_to_host)
    ]
