# Generated by Django 3.1.14 on 2022-06-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0090_auto_20220412_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authbook',
            options={'permissions': [('test_authbook', 'Can test asset account connectivity'), ('view_assetaccountsecret', 'Can view asset account secret'), ('change_assetaccountsecret', 'Can change asset account secret'), ('view_assethistoryaccount', 'Can view asset history account'), ('view_assethistoryaccountsecret', 'Can view asset history account secret')], 'verbose_name': 'AuthBook'},
        ),
        migrations.AlterModelOptions(
            name='historicalauthbook',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical AuthBook', 'verbose_name_plural': 'historical AuthBooks'},
        ),
        migrations.AlterField(
            model_name='historicalauthbook',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
