# Generated by Django 3.2.12 on 2022-07-11 06:13

from django.db import migrations


def migrate_accounts(apps, schema_editor):
    auth_book_model = apps.get_model('assets', 'AuthBook')
    account_model = apps.get_model('assets', 'Account')


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0092_auto_20220711_1409'),
    ]

    operations = [
    ]
