# Generated by Django 3.1.14 on 2022-04-02 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0093_auto_20220403_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='cpu_cores',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='cpu_count',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='cpu_model',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='cpu_vcpus',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='disk_info',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='disk_total',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='hostname_raw',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='memory',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='model',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='os',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='os_arch',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='os_version',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='sn',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='vendor',
        ),
    ]
