# Generated by Django 3.2.14 on 2022-08-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0093_auto_20220711_1413'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cluster',
        ),
    ]
