# Generated by Django 3.2.14 on 2022-07-28 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0093_auto_20220711_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='admin_user',
        ),
        migrations.RemoveField(
            model_name='systemuser',
            name='ad_domain',
        ),
        migrations.RemoveField(
            model_name='systemuser',
            name='assets',
        ),
        migrations.RemoveField(
            model_name='systemuser',
            name='auto_push',
        ),
        migrations.RemoveField(
            model_name='systemuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='systemuser',
            name='home',
        ),
        migrations.RemoveField(
            model_name='systemuser',
            name='nodes',
        ),
        migrations.RemoveField(
            model_name='systemuser',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='systemuser',
            name='sftp_root',
        ),
        migrations.RemoveField(
            model_name='systemuser',
            name='shell',
        ),
        migrations.RemoveField(
            model_name='systemuser',
            name='sudo',
        ),
        migrations.RemoveField(
            model_name='systemuser',
            name='system_groups',
        ),
        migrations.RemoveField(
            model_name='systemuser',
            name='token',
        ),
        migrations.RemoveField(
            model_name='systemuser',
            name='type',
        ),
        migrations.RemoveField(
            model_name='systemuser',
            name='users',
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='version',
            field=models.IntegerField(default=0, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='login_mode',
            field=models.CharField(choices=[('auto', '使用账号'), ('manual', 'Manually input')], default='auto', max_length=10, verbose_name='Login mode'),
        ),
        migrations.DeleteModel(
            name='AdminUser',
        ),
        migrations.DeleteModel(
            name='Cluster',
        ),
    ]
