# Generated by Django 3.1.14 on 2022-04-06 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0094_auto_20220402_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.CharField(choices=[('host', 'Host'), ('network', 'Networking'), ('database', 'Database'), ('remote_app', 'Remote app'), ('cloud', 'Clouding')], default='host', max_length=16, verbose_name='Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='type',
            field=models.CharField(default='linux', max_length=128, verbose_name='Type'),
            preserve_default=False,
        ),
    ]
