# Generated by Django 3.1.14 on 2022-04-06 07:46
from itertools import groupby

from django.db import migrations
from django.db.models import F


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0095_auto_20220406_1541'),
    ]

    operations = [
    ]
