# Generated by Django 3.2.12 on 2022-07-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0095_auto_20220713_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemuser',
            old_name='auto_push',
            new_name='auto_push_account',
        ),
        migrations.AddField(
            model_name='systemuser',
            name='account_template_enabled',
            field=models.BooleanField(default=False, verbose_name='Auto account if not exist'),
        ),
    ]
