# Generated by Django 3.1.14 on 2022-04-12 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0097_auto_20220407_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceinfo',
            name='host',
        ),
        migrations.AddField(
            model_name='host',
            name='device_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.deviceinfo', verbose_name='Device info'),
        ),
    ]
