# Generated by Django 3.1.14 on 2022-04-30 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0099_auto_20220426_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='admin_user_default',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.systemuser', verbose_name='Admin user default'),
        ),
        migrations.AddField(
            model_name='platform',
            name='admin_user_enabled',
            field=models.BooleanField(default=True, verbose_name='Admin user enabled'),
        ),
        migrations.AddField(
            model_name='platform',
            name='domain_default',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.domain', verbose_name='Domain default'),
        ),
        migrations.AddField(
            model_name='platform',
            name='domain_enabled',
            field=models.BooleanField(default=True, verbose_name='Domain enabled'),
        ),
        migrations.AddField(
            model_name='platform',
            name='protocols_default',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Protocols default'),
        ),
        migrations.AddField(
            model_name='platform',
            name='protocols_enabled',
            field=models.BooleanField(default=True, verbose_name='Protocols enabled'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.CharField(choices=[('host', 'Host'), ('network', 'NetworkDevice'), ('database', 'Database'), ('remote_app', 'Remote app'), ('cloud', 'Clouding')], max_length=16, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='category',
            field=models.CharField(choices=[('host', 'Host'), ('network', 'NetworkDevice'), ('database', 'Database'), ('remote_app', 'Remote app'), ('cloud', 'Clouding')], max_length=16, verbose_name='Category'),
        ),
    ]
