# Generated by Django 3.2.14 on 2022-08-11 07:11
import django.db.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('assets', '0100_auto_20220711_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets',
                                    to='assets.platform', verbose_name='Platform'),
        ),
        migrations.RemoveField(
            model_name='asset',
            name='admin_user',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='port',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='protocol',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='_protocols',
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='protocol',
            field=models.CharField(default='ssh', max_length=16, verbose_name='Protocol'),
        ),
        migrations.RemoveField(
            model_name='asset',
            name='number',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='public_ip',
        ),
    ]
