# Generated by Django 3.2.14 on 2022-08-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0100_auto_20220711_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='protocols',
            new_name='_protocols',
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('port', models.IntegerField(verbose_name='Port')),
                ('asset', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='protocols', to='assets.asset', verbose_name='Asset')),
            ],
        ),
        migrations.DeleteModel(
            name='Cluster',
        ),
    ]
