# Generated by Django 3.2.14 on 2022-08-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0100_auto_20220711_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('port', models.IntegerField(verbose_name='Port')),
            ],
        ),
        migrations.RemoveField(
            model_name='asset',
            name='port',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='protocol',
        ),
        migrations.AddField(
            model_name='asset',
            name='_protocols',
            field=models.CharField(blank=True, default='ssh/22', max_length=128, verbose_name='Protocols'),
        ),
        migrations.RemoveField(
            model_name='asset',
            name='protocols',
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='protocol',
            field=models.CharField(default='ssh', max_length=16, verbose_name='Protocol'),
        ),
        migrations.AddField(
            model_name='asset',
            name='protocols',
            field=models.ManyToManyField(blank=True, to='assets.Protocol', verbose_name='Protocols'),
        ),
        migrations.DeleteModel(
            name='Cluster',
        ),
    ]
