# Generated by Django 3.2.13 on 2022-08-19 07:23

import assets.models.base
import common.db.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0105_auto_20220817_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTemplate',
            fields=[
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('username', models.CharField(blank=True, db_index=True, max_length=128, verbose_name='Username')),
                ('password', common.db.fields.EncryptCharField(blank=True, max_length=256, null=True, verbose_name='Password')),
                ('private_key', common.db.fields.EncryptTextField(blank=True, null=True, verbose_name='SSH private key')),
                ('public_key', common.db.fields.EncryptTextField(blank=True, null=True, verbose_name='SSH public key')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('created_by', models.CharField(max_length=128, null=True, verbose_name='Created by')),
                ('token', common.db.fields.EncryptTextField(blank=True, null=True, verbose_name='Token')),
                ('privileged', models.BooleanField(default=False, verbose_name='Privileged account')),
            ],
            options={
                'verbose_name': 'Account template',
                'unique_together': {('name', 'org_id')},
            },
        ),
    ]
