# Generated by Django 3.2.14 on 2022-08-11 05:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0105_auto_20220810_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='protocol',
        ),
        migrations.RemoveField(
            model_name='historicalaccount',
            name='protocol',
        ),
    ]
