# Generated by Django 3.2.14 on 2022-08-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0105_auto_20220810_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='_protocols',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='admin_user',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='category',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='number',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='public_ip',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='type',
        ),
    ]
