# Generated by Django 3.2.16 on 2022-12-29 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0106_auto_20221228_1838'),
        ('tickets', '0025_auto_20221206_1820'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accountbackupplan',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='accountbackupplan',
            name='recipients',
        ),
        migrations.DeleteModel(
            name='AccountBackupPlanExecution',
        ),
        migrations.DeleteModel(
            name='CommandFilter',
        ),
        migrations.DeleteModel(
            name='CommandFilterRule',
        ),
        migrations.DeleteModel(
            name='GatheredUser',
        ),
        migrations.DeleteModel(
            name='AccountBackupPlan',
        ),
    ]
