# Generated by Django 3.2.14 on 2022-09-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0106_auto_20220819_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbackupplan',
            name='types',
            field=models.BigIntegerField(),
        ),
    ]
