# Generated by Django 3.2.13 on 2022-08-11 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0106_auto_20220811_1358'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountTemplate',
        ),
    ]
