# Generated by Django 3.2.14 on 2022-10-19 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0107_auto_20221019_1115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automationexecution',
            options={'verbose_name': 'Automation task execution'},
        ),
        migrations.AlterModelOptions(
            name='baseautomation',
            options={'verbose_name': 'Automation task'},
        ),
        migrations.AlterModelOptions(
            name='changesecretrecord',
            options={'verbose_name': 'Change secret record'},
        ),
        migrations.AlterModelOptions(
            name='verifyaccountautomation',
            options={'verbose_name': 'Verify account automation'},
        ),
        migrations.RenameField(
            model_name='changesecretautomation',
            old_name='password',
            new_name='secret',
        ),
        migrations.RemoveField(
            model_name='baseautomation',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='changesecretautomation',
            name='password_strategy',
        ),
        migrations.RemoveField(
            model_name='changesecretautomation',
            name='secret_types',
        ),
        migrations.RemoveField(
            model_name='changesecretautomation',
            name='ssh_key',
        ),
        migrations.RemoveField(
            model_name='changesecretautomation',
            name='ssh_key_strategy',
        ),
        migrations.AddField(
            model_name='changesecretautomation',
            name='secret_strategy',
            field=models.CharField(choices=[('specific', 'Specific'), ('random_one', 'All assets use the same random password'), ('random_all', 'All assets use different random password')], default='specific', max_length=16, verbose_name='Secret strategy'),
        ),
        migrations.AddField(
            model_name='changesecretautomation',
            name='secret_type',
            field=models.CharField(choices=[('password', 'Password'), ('ssh_key', 'SSH key'), ('access_key', 'Access key'), ('token', 'Token')], default='password', max_length=16, verbose_name='Secret type'),
        ),
        migrations.AlterField(
            model_name='automationexecution',
            name='automation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='assets.baseautomation', verbose_name='Automation task'),
        ),
        migrations.AlterField(
            model_name='changesecretautomation',
            name='ssh_key_change_strategy',
            field=models.CharField(choices=[('add', 'Append SSH KEY'), ('set', 'Empty and append SSH KEY'), ('set_jms', 'Replace (The key generated by JumpServer) ')], default='add', max_length=16, verbose_name='SSH key change strategy'),
        ),
    ]
