# Generated by Django 3.2.16 on 2023-01-05 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0107_automation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationexecution',
            name='automation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='assets.baseautomation', verbose_name='Automation task'),
        ),
    ]
