# Generated by Django 3.2.14 on 2022-10-27 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0107_auto_20221019_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatherAccountsAutomation',
            fields=[
                ('baseautomation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.baseautomation')),
            ],
            options={
                'verbose_name': 'Gather asset accounts',
            },
            bases=('assets.baseautomation',),
        ),
        migrations.AlterField(
            model_name='baseautomation',
            name='type',
            field=models.CharField(choices=[('ping', 'Ping'), ('gather_facts', 'Gather facts'), ('push_account', 'Create account'), ('change_secret', 'Change secret'), ('verify_account', 'Verify account'), ('gather_accounts', 'Gather accounts')], max_length=16, verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='PingAutomation',
            fields=[
                ('baseautomation_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='assets.baseautomation')),
            ],
            options={
                'verbose_name': 'Ping asset',
            },
            bases=('assets.baseautomation',),
        ),
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['name'],
                     'permissions': [('refresh_assethardwareinfo', 'Can refresh asset hardware info'),
                                     ('test_assetconnectivity', 'Can test asset connectivity'),
                                     ('push_assetaccount', 'Can push account to asset'),
                                     ('match_asset', 'Can match asset'), ('add_assettonode', 'Add asset to node'),
                                     ('move_assettonode', 'Move asset to node')], 'verbose_name': 'Asset'},
        ),
    ]
