# Generated by Django 3.2.16 on 2023-02-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0107_automation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='charset',
            field=models.CharField(choices=[('utf-8', 'UTF-8'), ('gbk', 'GBK')], default='utf-8', max_length=8, verbose_name='Charset'),
        ),
    ]
