# Generated by Django 3.2.16 on 2022-12-29 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0107_auto_20221229_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automationexecution',
            options={'ordering': ('-date_start',), 'verbose_name': 'Automation task execution'},
        ),
    ]
