# Generated by Django 3.2.14 on 2022-09-01 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0107_alter_accountbackupplan_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='create_account_enabled',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='create_account_method',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='domain_default',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='domain_enabled',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='ping_enabled',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='ping_method',
        ),
    ]
