# Generated by Django 3.2.16 on 2023-01-06 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0108_alter_automationexecution_automation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='baseautomation',
            unique_together={('org_id', 'name', 'type')},
        ),
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['name'],
                     'permissions': [('refresh_assethardwareinfo', 'Can refresh asset hardware info'),
                                     ('test_assetconnectivity', 'Can test asset connectivity'),
                                     ('push_assetaccount', 'Can push account to asset'),
                                     ('test_account', 'Can verify account'), ('match_asset', 'Can match asset'),
                                     ('add_assettonode', 'Add asset to node'),
                                     ('move_assettonode', 'Move asset to node')], 'verbose_name': 'Asset'},
        ),
    ]
