# Generated by Django 3.2.14 on 2022-09-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0108_auto_20220901_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='device_info',
        ),
        migrations.AddField(
            model_name='asset',
            name='info',
            field=models.JSONField(blank=True, default=dict, verbose_name='Info'),
        ),
        migrations.AddField(
            model_name='database',
            name='version',
            field=models.CharField(blank=True, max_length=16, verbose_name='Version'),
        ),
        migrations.DeleteModel(
            name='DeviceInfo',
        ),
    ]
