# Generated by Django 3.2.14 on 2022-11-03 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0108_auto_20221027_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountbackupplan',
            old_name='categories',
            new_name='types',
        ),
    ]
