# Generated by Django 3.2.16 on 2023-02-14 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0108_alter_platform_charset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': [], 'permissions': [('refresh_assethardwareinfo', 'Can refresh asset hardware info'), ('test_assetconnectivity', 'Can test asset connectivity'), ('match_asset', 'Can match asset'), ('change_assetnodes', 'Can change asset nodes')], 'verbose_name': 'Asset'},
        ),
    ]
