# Generated by Django 3.2.14 on 2022-08-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0108_auto_20220811_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='type',
        ),
        migrations.RemoveField(
            model_name='historicalaccount',
            name='type',
        ),
        migrations.AddField(
            model_name='account',
            name='privileged',
            field=models.BooleanField(default=False, verbose_name='Privileged account'),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='privileged',
            field=models.BooleanField(default=False, verbose_name='Privileged account'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='su_enabled',
            field=models.BooleanField(default=False, verbose_name='Su enabled'),
        ),
    ]
