# Generated by Django 3.2.14 on 2022-08-17 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0109_auto_20220817_1544'),
        ('applications', '0022_auto_20220817_1346'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='authbook',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='authbook',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='authbook',
            name='systemuser',
        ),
        migrations.DeleteModel(
            name='HistoricalAuthBook',
        ),
        migrations.DeleteModel(
            name='AuthBook',
        ),
    ]
