# Generated by Django 3.2.14 on 2022-11-03 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0109_auto_20221102_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountbackupplan',
            old_name='categories',
            new_name='types',
        ),
        migrations.AddField(
            model_name='changesecretrecord',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.asset'),
        ),
    ]
