# Generated by Django 3.2.14 on 2022-11-03 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0109_rename_categories_to_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='changesecretrecord',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.asset'),
        ),
    ]
