# Generated by Django 3.2.14 on 2022-10-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0109_auto_20221019_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='connectivity',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('ok', 'Ok'), ('failed', 'Failed')], default='unknown', max_length=16, verbose_name='Connectivity'),
        ),
        migrations.AddField(
            model_name='account',
            name='date_verified',
            field=models.DateTimeField(null=True, verbose_name='Date verified'),
        ),
    ]
