# Generated by Django 3.2.16 on 2023-01-10 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0109_alter_baseautomation_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteasset',
            options={'verbose_name': 'Favorite Asset'},
        ),
    ]
