# Generated by Django 3.2.16 on 2023-01-11 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0110_alter_favoriteasset_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformautomation',
            name='push_account_enabled',
            field=models.BooleanField(default=False, verbose_name='Push account enabled'),
        ),
    ]
