# Generated by Django 3.2.17 on 2023-03-21 08:33

from django.db import migrations, models


def migrate_platform_charset(apps, schema_editor):
    platform_model = apps.get_model('assets', 'Platform')
    platform_model.objects.filter(charset='utf8').update(charset='utf-8')


def migrate_platform_protocol_primary(apps, schema_editor):
    platform_model = apps.get_model('assets', 'Platform')
    platforms = platform_model.objects.all()

    for platform in platforms:
        p = platform.protocols.first()
        p.primary = True
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0110_auto_20230315_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformprotocol',
            name='primary',
            field=models.BooleanField(default=False, verbose_name='Primary'),
        ),
        migrations.RunPython(migrate_platform_charset),
        migrations.RunPython(migrate_platform_protocol_primary),
    ]
