# Generated by Django 3.2.14 on 2022-10-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0110_gatherfactsautomation'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformprotocol',
            name='default',
            field=models.BooleanField(default=True, verbose_name='Default'),
        ),
        migrations.AddField(
            model_name='platformprotocol',
            name='required',
            field=models.BooleanField(default=False, verbose_name='Required'),
        ),
    ]
