# Generated by Django 3.2.14 on 2022-09-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0111_auto_20220908_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='web',
            name='autofill',
            field=models.CharField(default='basic', max_length=16),
        ),
        migrations.AddField(
            model_name='web',
            name='password_selector',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='web',
            name='submit_selector',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='web',
            name='username_selector',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='platform',
            name='domain_enabled',
            field=models.BooleanField(default=True, verbose_name='Domain enabled'),
        ),
    ]
