# Generated by Django 3.2.16 on 2023-01-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0111_platformautomation_push_account_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformautomation',
            name='push_account_method',
            field=models.TextField(blank=True, max_length=32, null=True, verbose_name='Push account method'),
        ),
        migrations.AlterField(
            model_name='platformautomation',
            name='change_secret_enabled',
            field=models.BooleanField(default=False, verbose_name='Change secret enabled'),
        ),
        migrations.AlterField(
            model_name='platformautomation',
            name='change_secret_method',
            field=models.TextField(blank=True, max_length=32, null=True, verbose_name='Change secret method'),
        ),
    ]
