# Generated by Django 3.2.13 on 2022-08-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0111_auto_20220819_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='protocols_default',
        ),
        migrations.AddField(
            model_name='platform',
            name='protocols_enabled',
            field=models.BooleanField(default=True, verbose_name='Protocols enabled'),
        ),
    ]
