# Generated by Django 3.2.17 on 2023-03-24 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0111_auto_20230321_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformprotocol',
            name='public',
            field=models.BooleanField(default=True, verbose_name='Public'),
        ),
    ]
