# Generated by Django 3.2.16 on 2023-03-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0111_auto_20230321_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformautomation',
            name='params',
            field=models.JSONField(default=dict, verbose_name='Params'),
        ),
    ]
