# Generated by Django 3.2.16 on 2023-04-07 02:55

from django.db import migrations

from assets.const import AllTypes


def migrate_automation_push_account_params(apps, schema_editor):
    platform_automation_model = apps.get_model('assets', 'PlatformAutomation')
    platform_automation_methods = AllTypes.get_automation_methods()
    methods_id_data_map = {
        i['id']: '' if i['serializer'] is None else i['serializer']({}).data
        for i in platform_automation_methods
        if i['method'] == 'push_account'
    }
    automation_objs = []
    for automation in platform_automation_model.objects.all():
        push_account_method = automation.push_account_method
        if not push_account_method:
            continue
        automation.params = {
            push_account_method: methods_id_data_map.get(push_account_method, {})
        }
        automation_objs.append(automation)
    platform_automation_model.objects.bulk_update(automation_objs, ['params'])


class Migration(migrations.Migration):
    dependencies = [
        ('assets', '0112_platformautomation_params'),
    ]

    operations = [
        migrations.RunPython(migrate_automation_push_account_params),
    ]
