# Generated by Django 3.2.17 on 2023-04-04 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0112_platformprotocol_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.asset')),
            ],
            options={
                'verbose_name': 'Custom asset',
            },
            bases=('assets.asset',),
        ),
        migrations.AddField(
            model_name='platform',
            name='custom_fields',
            field=models.JSONField(default=list, null=True, verbose_name='Custom fields'),
        ),
    ]
