# Generated by Django 3.2.14 on 2022-11-29 05:14

from django.db import migrations, models
import django.db.models.deletion


# TODO 最后去掉这个迁移
class Migration(migrations.Migration):
    dependencies = [
        ('assets', '0113_alter_accounttemplate_options'),
    ]

    operations = [
    ]
