# Generated by Django 3.2.14 on 2022-11-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('assets', '0113_alter_accounttemplate_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='allow_invalid_cert',
            field=models.BooleanField(default=False, verbose_name='Allow invalid cert'),
        ),
        migrations.AddField(
            model_name='database',
            name='ca_cert',
            field=models.TextField(blank=True, verbose_name='CA cert'),
        ),
        migrations.AddField(
            model_name='database',
            name='client_cert',
            field=models.TextField(blank=True, verbose_name='Client cert'),
        ),
        migrations.AddField(
            model_name='database',
            name='client_key',
            field=models.TextField(blank=True, verbose_name='Client key'),
        ),
        migrations.AddField(
            model_name='database',
            name='use_ssl',
            field=models.BooleanField(default=False, verbose_name='Use SSL'),
        ),
    ]
