# Generated by Django 3.2.14 on 2022-12-01 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0115_auto_20221130_1118'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gateway',
        ),
    ]
