# Generated by Django 3.2.16 on 2022-12-23 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0116_alter_automationexecution_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gateway',
            options={'verbose_name': 'Gateway'},
        ),
    ]
