# Generated by Django 3.2.17 on 2023-04-20 07:27

from django.db import migrations, models


def update_asset_protocol(apps, schema_editor):
    asset_protocol_cls = apps.get_model('assets', 'Protocol')
    asset_protocols = asset_protocol_cls.objects.all()

    for protocol in asset_protocols:
        platform_protocol = protocol.asset.platform.protocols.filter(name=protocol.name).first()
        if platform_protocol:
            protocol.setting = platform_protocol.setting
            protocol.public = platform_protocol.public
            protocol.save()


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0116_auto_20230418_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='public',
            field=models.BooleanField(default=True, verbose_name='Public'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='setting',
            field=models.JSONField(default=dict, verbose_name='Setting'),
        ),
        migrations.AlterField(
            model_name='baseautomation',
            name='params',
            field=models.JSONField(default=dict, verbose_name='Parameters'),
        ),
        migrations.RunPython(update_asset_protocol)
    ]
