# Generated by Django 3.2.14 on 2022-12-01 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0116_delete_gateway'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gateway',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('assets.host',),
        ),
    ]
