# Generated by Django 3.2.14 on 2022-12-27 07:04

import common.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0117_alter_gateway_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushaccountautomation',
            name='password_rules',
            field=models.JSONField(default=dict, verbose_name='Password rules'),
        ),
        migrations.AddField(
            model_name='pushaccountautomation',
            name='secret',
            field=common.db.fields.EncryptTextField(blank=True, null=True, verbose_name='Secret'),
        ),
        migrations.AddField(
            model_name='pushaccountautomation',
            name='secret_strategy',
            field=models.CharField(choices=[('specific', 'Specific'), ('random_one', 'All assets use the same random password'), ('random_all', 'All assets use different random password')], default='specific', max_length=16, verbose_name='Secret strategy'),
        ),
        migrations.AddField(
            model_name='pushaccountautomation',
            name='secret_type',
            field=models.CharField(choices=[('password', 'Password'), ('ssh_key', 'SSH key'), ('access_key', 'Access key'), ('token', 'Token')], default='password', max_length=16, verbose_name='Secret type'),
        ),
        migrations.AddField(
            model_name='pushaccountautomation',
            name='ssh_key_change_strategy',
            field=models.CharField(choices=[('add', 'Append SSH KEY'), ('set', 'Empty and append SSH KEY'), ('set_jms', 'Replace (The key generated by JumpServer) ')], default='add', max_length=16, verbose_name='SSH key change strategy'),
        ),
        migrations.AddField(
            model_name='pushaccountautomation',
            name='username',
            field=models.CharField(default='', max_length=128, verbose_name='Username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baseautomation',
            name='type',
            field=models.CharField(choices=[('ping', 'Ping'), ('gather_facts', 'Gather facts'), ('push_account', 'Push account'), ('change_secret', 'Change secret'), ('verify_account', 'Verify account'), ('gather_accounts', 'Gather accounts')], max_length=16, verbose_name='Type'),
        ),
    ]
