# Generated by Django 3.2.16 on 2022-12-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0118_auto_20221227_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='source',
            field=models.CharField(default='local', max_length=30, verbose_name='Source'),
        ),
        migrations.DeleteModel(
            name='GatheredUser',
        ),
    ]
