# Generated by Django 3.2.14 on 2022-12-28 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0119_auto_20221227_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandfilterrule',
            name='filter',
        ),
        migrations.RemoveField(
            model_name='commandfilterrule',
            name='reviewers',
        ),
        migrations.DeleteModel(
            name='CommandFilter',
        ),
        migrations.DeleteModel(
            name='CommandFilterRule',
        ),
    ]
