# Generated by Django 4.1.10 on 2023-11-22 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0125_auto_20231011_1053'),
        ('labels', '0002_auto_20231103_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='labels',
        ),
    ]
