target-version = "py39"
line-length = 88

[lint]
select = ["E4", "E7", "E9", "F", "I", "N"]

[lint.per-file-ignores]
"jms_pam/credential/v1/credential_client.py" = ["N802"]

[lint.isort]
known-first-party = ["jms_pam", "jms_pam_config", "file_apps"]
