# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-01 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Name')),
                ('remote_addr', models.GenericIPAddressField(blank=True, null=True, verbose_name='Remote address')),
                ('type', models.CharField(blank=True, choices=[('SSH', 'SSH Terminal'), ('Web', 'Web Terminal')], max_length=3, verbose_name='Terminal type')),
                ('url', models.CharField(blank=True, max_length=100, verbose_name='URL to login')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='Is Accepted')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
            ],
            options={
                'ordering': ('is_accepted',),
            },
        ),
        migrations.CreateModel(
            name='TerminalHeatbeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.Terminal')),
            ],
            options={
                'db_table': 'terminal_heatbeat',
            },
        ),
    ]
