# Generated by Django 2.1.7 on 2019-05-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remoteapp',
            name='type',
            field=models.CharField(choices=[('浏览器', (('chrome', 'Chrome'),)), ('数据库工具', (('mysql_workbench', 'MySQL Workbench'),)), ('虚拟化工具', (('vmware_client', 'VMware Client'),)), ('custom', '自定义')], default='chrome', max_length=128, verbose_name='App type'),
        ),
    ]
