# Generated by Django 2.1.7 on 2019-09-09 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('perms', '0009_remoteapppermission_system_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remoteapp',
            name='system_user',
        ),
    ]
