# Generated by Django 3.2.14 on 2022-12-06 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationUser',
            fields=[
            ],
            options={
                'verbose_name': 'Application user',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('assets.systemuser',),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='app',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                    to='applications.application', verbose_name='Application'),
        ),
    ]
