# Generated by Django 2.1.11 on 2019-12-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_remove_remoteapp_system_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remoteapp',
            name='type',
            field=models.CharField(choices=[('chrome', 'Chrome'), ('mysql_workbench', 'MySQL Workbench'), ('vmware_client', 'vSphere Client'), ('custom', 'Custom')], default='chrome', max_length=128, verbose_name='App type'),
        ),
    ]
