# Generated by Django 3.2.14 on 2022-12-06 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('applications', '0002_remove_remoteapp_system_user'),
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalaccount',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='systemuser',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                    to='assets.systemuser', verbose_name='System user'),
        ),
        migrations.AddField(
            model_name='application',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='applications', to='assets.domain', verbose_name='Domain'),
        ),
        migrations.AddField(
            model_name='account',
            name='app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='applications.application', verbose_name='Application'),
        ),
        migrations.AddField(
            model_name='account',
            name='systemuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.systemuser',
                                    verbose_name='System user'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('org_id', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('username', 'app', 'systemuser')},
        ),
    ]
