# Generated by Django 2.1.11 on 2019-12-10 09:13

import common.fields.model
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_auto_20191210_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseApp',
            fields=[
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('created_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Created by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('type', models.CharField(choices=[('mysql', 'MySQL')], default='mysql', max_length=128, verbose_name='Database type')),
                ('host', models.CharField(db_index=True, max_length=128, verbose_name='Host')),
                ('port', models.IntegerField(default=3306, verbose_name='Port')),
                ('database', models.CharField(db_index=True, max_length=128, verbose_name='Database')),
                ('login_mode', models.CharField(choices=[('auto', 'Automatic login'), ('manual', 'Manually login')], default='auto', max_length=10, verbose_name='Login mode')),
                ('user', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='Username')),
                ('password', common.fields.model.EncryptCharField(blank=True, max_length=128, null=True, verbose_name='Password')),
                ('comment', models.TextField(blank=True, default='', max_length=128, verbose_name='Comment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
