# Generated by Django 3.1 on 2021-01-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perms', '0017_auto_20210104_0435'),
        ('applications', '0007_auto_20201119_1110'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DatabaseApp',
        ),
        migrations.DeleteModel(
            name='K8sApp',
        ),
        migrations.AlterField(
            model_name='application',
            name='attrs',
            field=models.JSONField(default=dict, verbose_name='Attrs'),
        ),
        migrations.DeleteModel(
            name='RemoteApp',
        ),
    ]
