# Generated by Django 3.1.13 on 2021-11-30 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_auto_20210826_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Application account'},
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ('name',), 'verbose_name': 'Application'},
        ),
        migrations.AlterModelOptions(
            name='applicationuser',
            options={'verbose_name': 'Application user'},
        ),
        migrations.AlterModelOptions(
            name='historicalaccount',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Application account'},
        ),
    ]
