# Generated by Django 3.1.12 on 2022-02-11 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_auto_20211130_1037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': [('view_applicationaccountsecret', 'Can view application account secret'), ('change_appplicationaccountsecret', 'Can view application account secret')], 'verbose_name': 'Application account'},
        ),
    ]
