# Generated by Django 3.1.13 on 2022-01-18 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_auto_20220112_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.application', verbose_name='Application'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='app',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='applications.application', verbose_name='Application'),
        ),
    ]
