# Generated by Django 3.1.13 on 2022-02-17 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0016_auto_20220118_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': [('view_applicationaccountsecret', 'Can view application account secret'), ('change_appplicationaccountsecret', 'Can change application account secret')], 'verbose_name': 'Application account'},
        ),
        migrations.AlterModelOptions(
            name='applicationuser',
            options={'verbose_name': 'Application user'},
        ),
        migrations.AlterModelOptions(
            name='historicalaccount',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Application account'},
        ),
    ]
