# Generated by Django 3.1.14 on 2022-03-09 22:16

from django.db import migrations


def drop_old_permissions(apps, schema_editor):
    content_type_model = apps.get_model("rbac", "ContentType")
    db_alias = schema_editor.connection.alias
    content_type_model.objects.using(db_alias).filter(platform__startswith='Win').update(protocol='rdp')


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0018_auto_20220223_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseApp',
            fields=[
            ],
            options={
                'verbose_name': 'Database application',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('applications.application',),
        ),
        migrations.CreateModel(
            name='KubernetesApp',
            fields=[
            ],
            options={
                'verbose_name': 'Kubernetes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('applications.application',),
        ),
        migrations.CreateModel(
            name='RemoteApp',
            fields=[
            ],
            options={
                'verbose_name': 'Remote application',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('applications.application',),
        ),
    ]
