# Generated by Django 3.1.14 on 2022-03-09 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0018_auto_20220223_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseApp',
            fields=[
            ],
            options={
                'verbose_name': 'Database application',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('applications.application',),
        ),
        migrations.CreateModel(
            name='KubernetesApp',
            fields=[
            ],
            options={
                'verbose_name': 'Kubernetes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('applications.application',),
        ),
        migrations.CreateModel(
            name='RemoteApp',
            fields=[
            ],
            options={
                'verbose_name': 'Remote application',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('applications.application',),
        ),
    ]
