# Generated by Django 3.1.14 on 2022-03-10 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0018_auto_20220223_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ('name',), 'permissions': [('match_application', 'Can match application')], 'verbose_name': 'Application'},
        ),
    ]
