# Generated by Django 3.2.14 on 2022-08-16 02:15

import common.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0021_auto_20220629_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='token',
            field=common.db.fields.EncryptTextField(blank=True, null=True, verbose_name='Token'),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='token',
            field=common.db.fields.EncryptTextField(blank=True, null=True, verbose_name='Token'),
        ),
    ]
