# Generated by Django 3.2.14 on 2022-08-17 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0022_auto_20220817_1346'),
        ('perms', '0031_auto_20220816_1600'),
        ('ops', '0022_auto_20220817_1346'),
        ('assets', '0105_auto_20220817_1544'),
        ('tickets', '0020_auto_20220817_1346'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='HistoricalAccount',
        ),
        migrations.DeleteModel(
            name='ApplicationUser',
        ),
    ]
