# Generated by Django 3.2.14 on 2022-08-16 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0022_auto_20220816_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='token',
        ),
        migrations.RemoveField(
            model_name='historicalaccount',
            name='token',
        ),
    ]
