# Generated by Django 3.2.14 on 2022-08-18 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0023_auto_20220817_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='category',
            field=models.CharField(max_length=16, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='application',
            name='type',
            field=models.CharField(max_length=16, verbose_name='Type'),
        ),
    ]
