# Generated by Django 3.1 on 2021-03-26 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Created by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('display_name', models.CharField(max_length=256, verbose_name='Display name')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
                ('type', models.CharField(max_length=128, verbose_name='Type')),
                ('is_builtin', models.BooleanField(default=False, verbose_name='Built-in')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('permissions', models.ManyToManyField(to='auth.Permission', verbose_name='Permission')),
            ],
        ),
        migrations.CreateModel(
            name='SafeRoleBinding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rbac.role', verbose_name='Role')),
                ('safe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.safe', verbose_name='Safe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'unique_together': {('user', 'role', 'safe')},
            },
        ),
    ]
