# Generated by Django 2.2.13 on 2020-10-12 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0008_auto_20200819_2041'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
        ('namespaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name='Role name')),
                ('type', models.CharField(choices=[('system', 'System'), ('org', 'Organization'), ('namespace', 'Namespace'), ('common', 'Common')], default='common', max_length=64, verbose_name='Role type')),
                ('is_build_in', models.BooleanField(default=False, verbose_name='Is build in')),
                ('permissions', models.ManyToManyField(to='auth.Permission', verbose_name='Permissions')),
            ],
            options={
                'verbose_name': 'Role',
            },
        ),
        migrations.CreateModel(
            name='RoleBinding',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_expired', models.DateTimeField(verbose_name='Date expired')),
                ('namespaces', models.ManyToManyField(to='namespaces.Namespace', verbose_name='Namespaces')),
                ('orgs', models.ManyToManyField(to='orgs.Organization', verbose_name='Organizations')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rbac.Role', verbose_name='Role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Role Binding',
                'unique_together': {('user', 'role')},
            },
        ),
    ]
