# Generated by Django 2.2.13 on 2020-10-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='type',
            field=models.CharField(choices=[('system', 'System role'), ('org', 'Organization role'), ('namespace', 'Namespace role')], default='namespace', max_length=64, verbose_name='Role type'),
        ),
        migrations.AlterUniqueTogether(
            name='rolebinding',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='rolebinding',
            name='date_expired',
        ),
    ]
