# Generated by Django 3.1.6 on 2021-07-01 07:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0010_auto_20210219_1241'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolebinding',
            options={'verbose_name': 'Role binding'},
        ),
        migrations.AlterUniqueTogether(
            name='rolebinding',
            unique_together={('user', 'role', 'org')},
        ),
    ]
