# Generated by Django 3.2.14 on 2022-12-06 04:52

import common.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbac', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rolebinding',
            name='user',
            field=models.ForeignKey(on_delete=common.db.models.CASCADE_SIGNAL_SKIP, related_name='role_bindings', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', to='rbac.Permission', verbose_name='Permissions'),
        ),
        migrations.CreateModel(
            name='OrgRole',
            fields=[
            ],
            options={
                'verbose_name': 'Organization role',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('rbac.role',),
        ),
        migrations.CreateModel(
            name='OrgRoleBinding',
            fields=[
            ],
            options={
                'verbose_name': 'Organization role binding',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('rbac.rolebinding',),
        ),
        migrations.CreateModel(
            name='SystemRole',
            fields=[
            ],
            options={
                'verbose_name': 'System role',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('rbac.role',),
        ),
        migrations.CreateModel(
            name='SystemRoleBinding',
            fields=[
            ],
            options={
                'verbose_name': 'System role binding',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('rbac.rolebinding',),
        ),
        migrations.AlterUniqueTogether(
            name='rolebinding',
            unique_together={('user', 'role', 'org')},
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('name', 'scope')},
        ),
    ]
