# Generated by Django 3.1.6 on 2021-07-02 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rolebinding',
            old_name='role_scope',
            new_name='scope',
        ),
    ]
