# Generated by Django 3.1.13 on 2021-11-19 08:31

from django.db import migrations
from rbac import const


def add_default_role(apps, schema_editor):
    role_model = apps.get_model('rbac', "Role")
    roles_data = [
        {
            'name': 'SystemAdmin',
            'scope': 'system',
            'builtin': True
        },
        {
            'name': 'OrgAdmin',
            'scope': 'org',
            'builtin': True
        },
        {
            'name': 'SystemAuditor',
            'scope': 'system',
            'builtin': True
        },
        {
            'name': 'OrgAuditor',
            'scope': 'org',
            'builtin': True
        },
        {
            'name': 'SystemUser',
            'scope': 'org',
            'builtin': True
        },
        {
            'name': 'OrgUser',
            'scope': 'org',
            'builtin': True
        },
        {
            'name': 'App',
            'scope': 'system',
            'builtin': True,
        }
    ]
    roles = [role_model(**data) for data in roles_data]
    role_model.objects.bulk_create(roles)


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_default_role)
    ]
