# Generated by Django 3.1.13 on 2021-12-01 11:01

from django.db import migrations
from rbac.builtin import BuiltinRole


def create_builtin_roles(apps, schema_editor):
    BuiltinRole.sync_to_db(show_msg=True)


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20210929_1409'),
    ]

    operations = [
        migrations.RunPython(create_builtin_roles)
    ]
