# Generated by Django 3.1.13 on 2021-12-01 11:01

from django.db import migrations
from rbac.const import BuiltinRole


def create_builtin_roles(apps, schema_editor):
    BuiltinRole.sync_to_db()


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_auto_20211130_1037'),
    ]

    operations = [
        migrations.RunPython(create_builtin_roles)
    ]
