# Generated by Django 2.2.13 on 2020-10-21 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('namespaces', '0001_initial'),
        ('orgs', '0008_auto_20200819_2041'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rbac', '0002_auto_20201020_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleNamespaceBinding',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('namespace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='namespaces.Namespace', verbose_name='Namespaces')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rbac.Role', verbose_name='Role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Role Namespace Binding',
            },
        ),
        migrations.CreateModel(
            name='RoleOrgBinding',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.Organization', verbose_name='Organizations')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rbac.Role', verbose_name='Role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Role Org Binding',
            },
        ),
        migrations.DeleteModel(
            name='RoleBinding',
        ),
    ]
