# Generated by Django 3.1.6 on 2021-07-02 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0010_auto_20210219_1241'),
        ('rbac', '0002_auto_20210702_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolebinding',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_bindings', to='orgs.organization', verbose_name='Organization'),
        ),
    ]
