# Generated by Django 3.1 on 2021-03-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_auto_20210326_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='type',
            field=models.CharField(choices=[('safe', 'Safe')], default='safe', max_length=128, verbose_name='Type'),
        ),
    ]
