# Generated by Django 3.1.13 on 2021-12-01 11:01

from django.db import migrations

from rbac.const import BuiltinRole


def migrate_system_role_binding(apps, schema_editor):
    pass


def migrate_org_role_binding(apps, schema_editor):
    org_member_model = apps.get_model('orgs', 'OrganizationMember')
    role_binding_model = apps.get_model('rbac', 'RoleBinding')
    role_model = apps.get_model('rbac', 'Role')
    members = org_member_model.objects.all()

    role_name_mapper = {role.name: role for role in role_model.objects.all()}
    role_bindings = []
    for member in members:
        role = BuiltinRole.get_org_role_by_old_name(member.role)
        role_binding = role_binding_model(
            scope='org',
            user=member.user,
        )
        role_binding.append(role_binding)
    role_binding_model.objects.bulk_create(role_bindings)

    # for role_name in ['Admin', 'Auditor', 'User']:
    #     role_members = members.filter(_role=role_name)
    #     print("Migrate org role members: {} {}".format(role_name, role_members.count()))
    #     role_members.update(role=role.ids)


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_auto_20211130_1037'),
    ]

    operations = [
    ]
