# Generated by Django 2.2.13 on 2020-10-21 06:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('namespaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rbac', '0003_auto_20201021_1408'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rolenamespacebinding',
            unique_together={('user', 'role', 'namespace')},
        ),
    ]
