# Generated by Django 3.1.13 on 2021-11-30 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_auto_20211130_1037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extrapermission',
            options={'default_permissions': [], 'permissions': [('view_adminview', 'Can view admin view'), ('view_auditview', 'Can view audit view'), ('view_userview', 'Can view user view')], 'verbose_name': 'Extra permission'},
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'verbose_name': 'Permission'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'permissions': (('view_rolepermissions', 'Can view role permissions'), ('change_rolepermissions', 'Can change role permissions')), 'verbose_name': 'Role'},
        ),
    ]
