# Generated by Django 3.1.14 on 2022-03-07 07:58

from django.db import migrations


def delete_unused_permissions(apps, schema_editor):
    permission_model = apps.get_model('rbac', 'Permission')
    content_type_model = apps.get_model('rbac', 'ContentType')
    content_type_delete_required = [
        ('common', 'permission'),
    ]
    for app, model in content_type_delete_required:
        content_type_model.objects.filter(app_label=app, model=model).delete()

    permissions_delete_required = [
        ('perms', 'assetpermission', 'connect_myassets'),
        ('perms', 'assetpermission', 'view_myassets'),
        ('perms', 'assetpermission', 'view_userassets'),
        ('perms', 'assetpermission', 'view_usergroupassets'),
        ('perms', 'applicationpermission', 'view_myapps'),
        ('perms', 'applicationpermission', 'connect_myapps'),
        ('perms', 'applicationpermission', 'view_userapps'),
        ('perms', 'applicationpermission', 'view_usergroupapps'),
    ]
    for app, model, codename in permissions_delete_required:
        permission_model.objects.filter(
            codename=codename, content_type__model=model, content_type__app_label=app
        ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0005_auto_20220307_1524'),
    ]

    operations = [
        migrations.RunPython(delete_unused_permissions)
    ]
