# Generated by Django 3.1.14 on 2022-03-07 07:58

from django.db import migrations


def delete_unused_permissions(apps, schema_editor):
    permission_model = apps.get_model('rbac', 'Permission')
    content_type_model = apps.get_model('rbac', 'ContentType')
    content_type_delete_required = [
        ('common', 'permission'),
    ]
    for app, model in content_type_delete_required:
        content_type_model.objects.filter(app_label=app, model=model).delete()

    permissions_delete_required = [
        ('perms', 'permeddatabaseapp', 'connect_mydatabaseapp'),
        ('perms', 'permeddatabaseapp', 'view_mydatabaseapp'),
        ('perms', 'permedkubernetesapp', 'connect_mykubernetesapp'),
        ('perms', 'permedkubernetesapp', 'view_mykubernetesapp'),
        ('perms', 'permedremoteapp', 'connect_myremoteapp'),
        ('perms', 'permedremoteapp', 'view_myremoteapp'),

        ('applications', 'databaseapp', 'add_databaseapp'),
        ('applications', 'databaseapp', 'change_databaseapp'),
        ('applications', 'databaseapp', 'delete_databaseapp'),
        ('applications', 'databaseapp', 'view_databaseapp'),
        ('applications', 'kubernetesapp', 'add_kubernetesapp'),
        ('applications', 'kubernetesapp', 'delete_kubernetesapp'),
        ('applications', 'kubernetesapp', 'change_kubernetesapp'),
        ('applications', 'kubernetesapp', 'view_kubernetesapp'),
        ('applications', 'remoteapp', 'add_remoteapp'),
        ('applications', 'remoteapp', 'change_remoteapp'),
        ('applications', 'remoteapp', 'delete_remoteapp'),
        ('applications', 'remoteapp', 'view_remoteapp'),


    ]
    for app, model, codename in permissions_delete_required:
        permission_model.objects.filter(
            codename=codename, content_type__model=model, content_type__app_label=app
        ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0007_auto_20220310_0616'),
    ]

    operations = [
        migrations.RunPython(delete_unused_permissions)
    ]
