# Generated by Django 3.1.14 on 2022-04-11 09:09

from django.db import migrations


def migrate_workspace_to_workbench(apps, *args):
    model = apps.get_model('auth', 'Permission')
    model.objects.filter(codename='view_workspace').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0007_auto_20220314_1525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menupermission',
            options={'default_permissions': [], 'permissions': [('view_console', 'Can view console view'), ('view_audit', 'Can view audit view'), ('view_workbench', 'Can view workbench view'), ('view_webterminal', 'Can view web terminal'), ('view_filemanager', 'Can view file manager')], 'verbose_name': 'Menu permission'},
        ),
    ]
