# Generated by Django 3.1.14 on 2022-04-11 09:24

from django.db import migrations


def migrate_workspace_to_workbench(apps, *args):
    model = apps.get_model('auth', 'Permission')
    model.objects.filter(codename='view_workspace').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0008_auto_20220411_1709'),
    ]

    operations = [
        migrations.RunPython(migrate_workspace_to_workbench)
    ]
