# Generated by Django 3.2.16 on 2023-02-02 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0011_remove_redundant_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ('scope', 'name'), 'verbose_name': 'Role'},
        ),
    ]
