# Generated by Django 4.1.10 on 2023-10-20 07:01

from django.db import migrations


def migrate_remove_add_changesecretexection_permission(apps, *args):
    perm_model = apps.get_model('auth', 'Permission')
    perm_model.objects.filter(codename='add_changesecretexection').delete()


class Migration(migrations.Migration):
    dependencies = [
        ('rbac', '0011_remove_redundant_permission'),
    ]

    operations = [
        migrations.RunPython(migrate_remove_add_changesecretexection_permission)
    ]
