- hosts: sqlserver
  gather_facts: no
  vars:
    ansible_python_interpreter: "{{ local_python_interpreter }}"
    target_db: "{{ jms_asset.spec_info.db_name | default('master', true) }}"

  tasks:
    - name: Test SQLServer connection
      mssql_script:
        login_user: "{{ jms_account.username }}"
        login_password: "{{ jms_account.secret }}"
        login_host: "{{ jms_asset.address }}"
        login_port: "{{ jms_asset.port }}"
        name: "{{ target_db }}"
        encryption: "{{ jms_asset.encryption | default(None) }}"
        tds_version: "{{ jms_asset.tds_version | default(None) }}"
        login_timeout: 15
        query_timeout: 30
        script: |
          SELECT 
              l.name,
              l.modify_date,
              l.is_disabled,
              l.create_date,
              l.default_database_name,
              CAST(LOGINPROPERTY(name, 'DaysUntilExpiration') AS INT) AS days_until_expiration,
              CAST(NULL AS datetime) AS last_login_time
          FROM sys.sql_logins l
          ORDER BY l.name;
        output: dict
        changed: false
      register: db_info

    - name: Define info by set_fact
      set_fact:
        info: "{{ db_info.query_results_dict }}"
