#!/usr/bin/env node

var program = require('commander');
  nodetail = require('../src/node-tail.js');

var options = {};

program
  .usage('[options] file...')
  .option('-p, --port <port>', 'custom port');

program.parse(process.argv);

nodetail.run({
  port: program.port,
  file: program.args[0]
});
