- hosts: oracle
  gather_facts: no
  vars:
    ansible_python_interpreter: /opt/py3/bin/python

  tasks:
    - name: Get info
      oracle_ping:
        login_user: "{{ jms_account.username }}"
        login_password: "{{ jms_account.secret }}"
        login_host: "{{ jms_asset.address }}"
        login_port: "{{ jms_asset.port }}"
        login_database: "{{ jms_asset.spec_info.db_name }}"
        mode: "{{ jms_account.mode }}"
      register: db_info

    - name: Define info by set_fact
      set_fact:
        info:
          version: "{{ db_info.server_version }}"

    - debug:
        var: info
