# Generated by Django 4.1.13 on 2026-03-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportexecution',
            name='status',
            field=models.CharField(choices=[('ready', 'Ready'), ('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('error', 'Error'), ('canceled', 'Canceled')], default='pending', max_length=16),
        ),
    ]