# Generated by Django 2.1.7 on 2019-07-29 06:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesskey',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 7, 29, 6, 23, 54, 115123, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accesskey',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
