# Generated by Django 4.1.13 on 2024-12-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_sshkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passkey',
            name='token',
            field=models.CharField(max_length=1024, verbose_name='Token'),
        ),
    ]
