# Generated by Django 3.1.13 on 2021-11-30 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20210929_1106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesskey',
            options={'verbose_name': 'Access key'},
        ),
        migrations.AlterModelOptions(
            name='ssotoken',
            options={'verbose_name': 'SSO token'},
        ),
    ]
