# Generated by Django 4.1.13 on 2025-08-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_connectiontoken_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectiontoken",
            name="remote_addr",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Remote addr"
            ),
        ),
    ]
