# Generated by Django 4.1.13 on 2025-07-03 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_connectiontoken_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ssotoken',
            options={'permissions': [('add_ssologinurl', 'Can add SSO login URL')], 'verbose_name': 'SSO token'},
        ),
    ]
