# Generated by Django 3.1.14 on 2022-03-02 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_connectiontoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperConnectionToken',
            fields=[
            ],
            options={
                'verbose_name': 'Super connection token',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentication.connectiontoken',),
        ),
    ]
