# Generated by Django 3.1.13 on 2022-02-17 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_connectiontoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesskey',
            options={'verbose_name': 'Access key'},
        ),
        migrations.AlterModelOptions(
            name='ssotoken',
            options={'verbose_name': 'SSO token'},
        ),
    ]
