# Generated by Django 4.1.13 on 2025-08-14 06:39

import authentication.models.access_key
import common.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_connectiontoken_remote_addr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesskey",
            name="secret",
            field=common.db.fields.EncryptTextField(
                default=authentication.models.access_key.default_secret,
                verbose_name="AccessKeySecret",
            ),
        ),
        migrations.AlterField(
            model_name="temptoken",
            name="secret",
            field=common.db.fields.EncryptTextField(
                verbose_name="Secret"
            ),
        ),
    ]
