# Generated by Django 3.1.14 on 2022-03-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_superconnectiontoken'),
    ]

    operations = [
        # 删除 jms_oidc_rp 中的Model
        migrations.RunSQL(
            sql='DROP TABLE `jms_oidc_rp_oidcuser` CASCADE;',
        ),
    ]
