# Generated by Django 5.2.13 on 2026-06-03 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_accesskey_secret_alter_temptoken_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectiontoken',
            name='input_secret_type',
            field=models.CharField(blank=True, default='password', max_length=16, verbose_name='Input secret type'),
        ),
    ]
