# Generated by Django 3.1.14 on 2022-03-09 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_superconnectiontoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connectiontoken',
            options={'permissions': [('view_connectiontokensecret', 'Can view connection token secret')], 'verbose_name': 'Connection token'},
        ),
    ]
