# Generated by Django 5.2.13 on 2026-08-17

import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_connectiontoken_input_secret_type'),
        ('rbac', '0005_report_create_delete_permissions'),
        ('users', '0006_user_ukey_sn'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthRoleBinding',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=30, verbose_name='Source')),
                ('owned', models.BooleanField(default=False, verbose_name='Owned')),
                ('role_binding', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='auth_source_bindings',
                    to='rbac.rolebinding', verbose_name='Role binding'
                )),
            ],
            options={
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroupBinding',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=30, verbose_name='Source')),
                ('owned', models.BooleanField(default=False, verbose_name='Owned')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='auth_user_group_bindings',
                    to='users.user', verbose_name='User'
                )),
                ('user_group', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='auth_user_bindings',
                    to='users.usergroup', verbose_name='User group'
                )),
            ],
            options={
                'default_permissions': [],
            },
        ),
        migrations.AddConstraint(
            model_name='authrolebinding',
            constraint=models.UniqueConstraint(
                fields=('source', 'role_binding'),
                name='uniq_auth_role_binding_source'
            ),
        ),
        migrations.AddConstraint(
            model_name='authusergroupbinding',
            constraint=models.UniqueConstraint(
                fields=('source', 'user', 'user_group'),
                name='uniq_auth_user_group_source'
            ),
        ),
    ]
