# Generated by Django 3.2.14 on 2022-10-25 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0110_auto_20221021_1506'),
        ('authentication', '0012_auto_20220816_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectiontoken',
            name='type',
        ),
        migrations.AddField(
            model_name='connectiontoken',
            name='account_display',
            field=models.CharField(default='', max_length=128, verbose_name='Account display'),
        ),
        migrations.AlterField(
            model_name='connectiontoken',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connection_tokens', to='assets.account', verbose_name='Account'),
        ),
    ]
