# Generated by Django 3.2.14 on 2022-10-26 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_auto_20220816_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectiontoken',
            name='type',
        ),
    ]
