# Generated by Django 3.2.14 on 2022-11-22 13:52

from django.db import migrations, models

import common.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0013_connectiontoken_protocol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connectiontoken',
            old_name='account_username',
            new_name='account_name'
        ),
        migrations.AlterField(
            model_name='connectiontoken',
            name='account_name',
            field=models.CharField(max_length=128, verbose_name='Account name'),
        ),
        migrations.AddField(
            model_name='connectiontoken',
            name='input_username',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Input username'),
        ),
        migrations.AddField(
            model_name='connectiontoken',
            name='input_secret',
            field=common.db.fields.EncryptCharField(blank=True, default='', max_length=128,
                                                    verbose_name='Input secret'),
        ),
        migrations.RenameField(
            model_name='connectiontoken',
            old_name='secret',
            new_name='value',
        ),
        migrations.AlterField(
            model_name='connectiontoken',
            name='value',
            field=models.CharField(default='', max_length=64, verbose_name='Value'),
        ),
        migrations.AddField(
            model_name='connectiontoken',
            name='connect_method',
            field=models.CharField(default='web_ui', max_length=32, verbose_name='Connect method'),
            preserve_default=False,
        ),
    ]
