# Generated by Django 3.2.14 on 2022-11-23 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_auto_20221122_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectiontoken',
            name='login',
            field=models.CharField(max_length=128, verbose_name='Login account'),
        ),
    ]
