# Generated by Django 3.2.14 on 2022-12-05 03:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0014_auto_20221122_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connectiontoken',
            old_name='account_name',
            new_name='account',
        ),
    ]
