# Generated by Django 3.2.14 on 2022-11-25 14:40

from django.db import migrations, models

import common.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0015_alter_connectiontoken_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connectiontoken',
            old_name='login',
            new_name='account_name'
        ),
        migrations.RenameField(
            model_name='connectiontoken',
            old_name='secret',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='connectiontoken',
            old_name='username',
            new_name='input_username',
        ),
        migrations.AlterField(
            model_name='connectiontoken',
            name='account_name',
            field=models.CharField(max_length=128, verbose_name='Account name'),
        ),
        migrations.AlterField(
            model_name='connectiontoken',
            name='value',
            field=models.CharField(default='', max_length=64, verbose_name='Value'),
        ),
        migrations.AddField(
            model_name='connectiontoken',
            name='input_secret',
            field=common.db.fields.EncryptCharField(blank=True, default='', max_length=128,
                                                    verbose_name='Input Secret'),
        ),
        migrations.AlterField(
            model_name='connectiontoken',
            name='input_username',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Input Username'),
        ),
    ]
