# Generated by Django 3.2.14 on 2023-01-05 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0028_remove_app_tickets'),
        ('authentication', '0016_auto_20221220_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectiontoken',
            name='from_ticket',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connection_token', to='tickets.applyloginassetticket', verbose_name='From ticket'),
        ),
        migrations.AddField(
            model_name='connectiontoken',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
