# Generated by Django 3.2.16 on 2023-02-14 08:49

import common.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_auto_20230105_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectiontoken',
            name='input_secret',
            field=common.db.fields.EncryptTextField(blank=True, default='', max_length=64, verbose_name='Input secret'),
        ),
    ]
