# Generated by Django 3.2.14 on 2022-11-29 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_connectiontoken_endpoint_protocol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectiontoken',
            name='endpoint_protocol',
        ),
    ]
