# Generated by Django 3.2.17 on 2023-06-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_connectiontoken_is_reusable'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectiontoken',
            name='connect_options',
            field=models.JSONField(default=dict, verbose_name='Connect options'),
        ),
    ]
