# Generated by Django 4.1.10 on 2023-09-08 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0021_auto_20230713_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passkey',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Enabled')),
                ('platform', models.CharField(default='', max_length=255, verbose_name='Platform')),
                ('added_on', models.DateTimeField(auto_now_add=True, verbose_name='Added on')),
                ('date_last_used', models.DateTimeField(default=None, null=True, verbose_name='Date last used')),
                ('credential_id', models.CharField(max_length=255, unique=True, verbose_name='Credential ID')),
                ('token', models.CharField(max_length=255, verbose_name='Token')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
