# Generated by Django 4.1.10 on 2023-10-31 05:37

import authentication.models.access_key
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0023_auto_20231010_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesskey',
            name='ip_group',
            field=models.JSONField(default=authentication.models.access_key.default_ip_group, verbose_name='IP group'),
        ),
    ]
