# Generated by Django 2.1.7 on 2019-09-16 02:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgs', '0002_auto_20180903_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='auditors',
            field=models.ManyToManyField(blank=True, related_name='related_audit_orgs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='related_admin_orgs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='related_user_orgs', to=settings.AUTH_USER_MODEL),
        ),
    ]
