# Generated by Django 3.1.13 on 2021-12-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0010_auto_20210219_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmember',
            name='role',
            field=models.CharField(default='User', max_length=16, verbose_name='Role'),
        ),
    ]
