# Generated by Django 3.1.13 on 2021-12-08 03:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgs', '0010_auto_20210219_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmember',
            name='role',
            field=models.CharField(default='User', max_length=16, verbose_name='Role'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationmember',
            unique_together={('org', 'user')},
        ),
    ]
