# Generated by Django 3.1.13 on 2021-12-02 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0011_auto_20210929_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationmember',
            old_name='role',
            new_name='_role',
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='role',
            field=models.ForeignKey(limit_choices_to={'scope': 'org'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Role'),
        ),
    ]
