# Generated by Django 3.1.13 on 2022-01-18 02:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rbac', '0004_auto_20211201_1901'),
        ('orgs', '0011_auto_20211223_1913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'permissions': (('view_rootorg', 'Can view root org'),), 'verbose_name': 'Organization'},
        ),
        migrations.AlterField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(related_name='orgs', through='rbac.RoleBinding', to=settings.AUTH_USER_MODEL),
        ),
    ]
