# Generated by Django 3.2.14 on 2022-08-11 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0012_auto_20220118_1054'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganizationMember',
        ),
    ]
