name: Issue Close Check

on:
  issues:
    types: [closed]

permissions:
  issues: write

jobs:
  issue-close-remove-labels:
    runs-on: ubuntu-latest
    if: ${{ !github.event.issue.pull_request }}
    steps:
      - name: Remove labels
        run: |
          gh issue edit "${{ github.event.issue.number }}" \
            --remove-label "🔔 Pending processing" \
            --remove-label "⏳ Pending feedback"
        env:
          GH_TOKEN: ${{ github.token }}
