name: Issue Open Check

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  issue-open-add-labels:
    runs-on: ubuntu-latest
    if: ${{ !github.event.issue.pull_request }}
    steps:
      - name: Add labels
        run: |
          gh issue edit "${{ github.event.issue.number }}" \
            --add-label "🔔 Pending processing"
        env:
          GH_TOKEN: ${{ github.token }}
