name: 🔀 Sync mirror to Gitee

on:
  schedule:
    # 每天凌晨3点运行
    - cron: '0 3 * * *'

jobs:
  mirror:
    runs-on: ubuntu-latest
    if: github.repository == 'jumpserver/jumpserver'
    steps:
      - name: mirror
        continue-on-error: true
        uses: wearerequired/git-mirror-action@6bbc55f2f0082bca533b72dc711f7d37154d40cc # v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_SSH_PRIVATE_KEY }}
        with:
          source-repo: 'git@github.com:jumpserver/jumpserver.git'
          destination-repo: 'git@gitee.com:fit2cloud-feizhiyun/JumpServer.git'
