# Generated by Django 3.1 on 2021-04-15 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='app_name',
            new_name='app_label',
        ),
    ]
