# Generated by Django 4.1.13 on 2026-04-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20210909_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagecontent',
            name='display_mode',
            field=models.CharField(choices=[('', 'Default'), ('popup', 'Popup')], default='', max_length=32),
        ),
    ]
