# Generated by Django 3.1 on 2021-04-15 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20210415_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='app_label',
            new_name='app',
        ),
    ]
