# Generated by Django 3.2.14 on 2022-09-30 09:01

import common.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0002_auto_20210909_1946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemmsgsubscription',
            options={'verbose_name': 'System message'},
        ),
        migrations.AlterModelOptions(
            name='usermsgsubscription',
            options={'verbose_name': 'User message'},
        ),
        migrations.AlterField(
            model_name='usermsgsubscription',
            name='receive_backends',
            field=models.JSONField(default=list, verbose_name='receive backend'),
        ),
        migrations.AlterField(
            model_name='usermsgsubscription',
            name='user',
            field=models.OneToOneField(on_delete=common.db.models.CASCADE_SIGNAL_SKIP, related_name='user_msg_subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
