# Generated by Django 3.1 on 2021-04-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20210415_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backend',
            name='org_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='org_id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='org_id',
        ),
        migrations.AlterField(
            model_name='backend',
            name='name',
            field=models.CharField(choices=[('wecom', 'WeCom'), ('email', 'Email')], db_index=True, default='', max_length=64),
        ),
    ]
